dusk-network/rusk

contracts/bid/Cargo.toml
contracts/bid/circuits/Cargo.toml
contracts/bid/circuits/rustfmt.toml
contracts/bid/circuits/src/lib.rs
contracts/bid/rustfmt.toml
contracts/bid/src/lib.rs
contracts/transfer/circuits/Cargo.toml
contracts/transfer/circuits/rustfmt.toml
contracts/transfer/circuits/src/lib.rs

As stated in #73 it would be nice to define better the structure
of the contracts in respect to services.
On this way we have sub-crates for both, circuits and contracts
for each service that rusk contains/works with.
All of this sub-crates derive from a root folder located in the
root of the git repo which is called `contracts/`.
Closes #73

Define modular structure for rusk contracts.

---

.travis.yml
Cargo.toml
Makefile
src/bin/main.rs
src/bin/unix.rs
tests/echo_service_tests.rs
tests/unix.rs

Since rusk will ommunicate with the Golang node and this process can happen on Windows and Unix-based machines, we need to provide UDS for the second ones and TCP/IP for all of them when working with GRPC communications.
- Added tests to generate a client and a server that work through UDS.
- Refactored the bin app to startup using UDS toghether with .
- Added an Arg option to set a custom path for UDS filedescriptor bind.
The solution is a bit messy just for the `unix.rs` mod that I need to define twice. But I don't think we should export it to be able to use it on the tests. That's why I duplicated just this code.
For the rest, it should be OK.
Closes #68 
Closes #69 IMO since we now don't have any address problems with the Travis or local testing at the moment wit the latest addresses …

Support UDS & TCP/IP for ipc

---

build.rs
contracts/bid/circuits/src/lib.rs
contracts/bid/src/lib.rs
contracts/transfer/src/lib.rs
src/bin/main.rs
src/bin/unix.rs
src/bin/version.rs
src/lib/encoding.rs
src/lib/lib.rs
src/lib/services.rs
src/lib/services/echoer.rs
src/lib/services/pki.rs
src/lib/services/pki/keygen.rs
src/lib/services/pki/stealth_gen.rs
tests/echo_service_tests.rs
tests/unix.rs

They were of the wrong format, and have been
changed to the format used by cargo-dusk-analyzer.
Fixes #97

Fix copyright headers

---

Cargo.toml
build.rs
contracts/bid/circuits/src/correctness.rs

We need to pre-compile the blindbid_circuit in order
to have quick access to preprocessed `ProverKey` and
`VerifierKey`.
That will allow us to elaborate proofs and verify them
without preprocessing.
Closes #94
It took 19min to compile `build.rs` and run the Circuit compilation in `release` mode. Idk why TBH because it should take arround a minute aprox considering that it uses the same code that is used inside of the `dusk-blindbid` lib. I'm not sure why this happens since passing `--release` to the `cargo build` command should run that in less than 2 mins aprox in a normal machine.
Do you know which can be the issue guys?

Add BlindBidCircuit compilation to build.rs

---

Cargo.toml
build.rs
contracts/bid/circuits/Cargo.toml

We need to pre-compile the bid correctness_circuit in order to have quick access to preprocessed `ProverKey` and
`VerifierKey`.
That will allow us to elaborate proofs and verify them without preprocessing.
Closes #103

Compile bid correctness proof circuit in build time

---

Cargo.toml
src/lib/lib.rs
src/lib/services/blindbid/score_gen_handler.rs
src/lib/services/blindbid/verify_score_handler.rs

We were previously reading the public parameters from disk
on every call that arrived requiering a proff generation/verification.
It was unoptimal to work on that way since due to the ammount
of checks that are needed to guarantee that the Public Parameters
are correct is massive, it takes like 2min to obtain an instance
of the Public Parameters.
So we've moved the Pub Params read to a lazy_static block which is
executed in the `default` fn call to the Rusk instance that you execute.
This forces to read the pub params just at the time where you
instanciate the Rusk server and therefore no RPC method gets delayed
by this fact.
Closes #112

Optimize & Speed Up Pub Params usage/read

---

build.rs
contracts/bid/circuits/Cargo.toml
contracts/bid/circuits/src/correctness.rs
src/lib/services/blindbid/score_gen_handler.rs
src/lib/services/blindbid/verify_score_handler.rs

After updating the following deps to the latests
releases:
- `dusk-plonk v0.3.1`
- `plonk_gadgets v0.4.0`
- `dusk-blindbid v0.3.0`
We needed to refactor the circuits and it's implementations
acording to the new `Circuit` trait API.
- Refactored `BlindBidCircuit` usage & field renaming.
- Refactored `BidCorrectnessCircuit` usage & field renaming.
- Update build.rs with the new `Circuit` API.

Update bid_circuits & blindbid circuits aligned to the new Circuit trait

---

.github/workflows/dusk_ci.yml
Cargo.toml
build.rs
contracts/bid/circuits/Cargo.toml
contracts/bid/circuits/src/correctness.rs
profile/Cargo.toml
profile/src/lib.rs
rustfmt.toml
src/bin/main.rs
src/bin/version.rs
src/lib/lib.rs
src/lib/services/blindbid.rs
src/lib/services/blindbid/score_gen_handler.rs
src/lib/services/blindbid/verify_score_handler.rs
src/lib/services/echoer.rs
tests/blindbid_service.rs
tests/echo_service_tests.rs
tests/pki_service.rs

- Remove `cargo check` from CI
- Remove tests for stable from CI
- Add CI caching for `.rusk` profile
- Add CI caching for rust dependencies
- Create a sub crate `profile` to handle rusk's profile settings
- Add key's caching mechanism in `rusk_profile`
- Update Rusk to use both at runtime and at compile time `rusk_profile`
- Add `wrap_comments` to `rustfmt.toml`
- Run `cargo fmt`
- Fix all Rusk warnings
Resolves: #123

Add `.rusk` profile folder with local / CI caching

---

.github/workflows/dusk_ci.yml
Cargo.toml
contracts/bid/circuits/Cargo.toml
contracts/transfer/circuits/Cargo.toml

This avoids errors when attempting to download and install rustfmt.

Lock nightly toolchain version in CI

---

contracts/transfer/circuits/Cargo.toml
contracts/transfer/circuits/src/dusk_contract/execute.rs
contracts/transfer/circuits/src/gadgets.rs
contracts/transfer/circuits/src/gadgets/balance.rs
contracts/transfer/circuits/src/gadgets/merkle.rs
contracts/transfer/circuits/src/gadgets/nullifier.rs
contracts/transfer/circuits/src/gadgets/preimage.rs
contracts/transfer/circuits/src/gadgets/range.rs
contracts/transfer/circuits/src/gadgets/schnorr.rs
contracts/transfer/circuits/src/gadgets/secret_key.rs

As per the refactor required in the dusk contract, this PR will address the gadgets which permeate the circuits.
The first of these is the inner workings of the preimage gadget, which cannot be tied to the note in the current specs. This PR will refactor the the preimage gadget and its uses within rust.
The second is a schnorr signature gadget, which allows us to prove the knowledge of DLP given a signature.
This closes #124.

Refactor the gagdets folder 

---

Cargo.toml
build.rs
src/lib/encoding.rs
src/lib/transaction.rs

No implementation of `Default` is possible for a transaction due to the internal keys that must derive from a provided random number generator.
These default implementations are currently used only for serialization purposes. An implementation of to/from bytes will fix that.

Replace `Default` for to/from of TxPayload and Tx

---

Cargo.toml
build.rs
contracts/transfer/circuits/src/builder.rs
profile/src/lib.rs

- Change `set_common_reference_string` to accept a buffer instead a path
- Change `get_common_reference_string` to fail if the cached file's hash
does not match with the expected one
- Change CRS generation in build script to use a seedable rng
- Change `build.rs` to re-run even if only the script itself is updated
- Change `build.rs` to enforce `PUB_PARAMS` initialization despite the
keys generation

Update CRS generation and rusk-profile

---

build.rs
profile/Cargo.toml
profile/src/lib.rs

- Remove the integrity check from `get_common_reference_string`
- Add `verify_common_reference_string` to perform the integrity check
- Change `build.rs`
Resolves: #200

    Decouple the CRS integrity check from `get_common_reference_string`

---

build.rs
profile/src/lib.rs

The code of the integrity check was properly added to the new function
`verify_common_reference_string` but was still kept in the function
`get_common_reference_string` of `rusk_profile`.
This PR removes the check from `get_common_reference_string`.
See also: #200

Complete decoupling of `get_common_reference_string`

---

Makefile
circuits/Makefile
contracts/Makefile

There are various potential problem with doing the sub-make inside a for
loop for a single recipe (e.g. might not exit on failure or not properly
supporting `--keep-going`, as well as parallel builds acresso multiple
directories; etc.)

Remove for loops for sub-make calls

---

circuits/transfer/Cargo.toml
circuits/transfer/src/execute.rs
circuits/transfer/src/send_to_contract_obfuscated.rs
circuits/transfer/src/send_to_contract_transparent.rs
circuits/transfer/src/withdraw_from_obfuscated.rs

Closes #225
Currently, the PLONK circuit API relies on a valid instance to
set the correct public inputs positions so it can run proofs.
The host must be agnostic of the circuit instance because the
public inputs exists only on the contract scope. But, it still
need the circuit instance to call the verify methods of the
plonk traits.

Transfer Circuits - From public inputs

---

rusk-abi/CHANGELOG.md
rusk-abi/Cargo.toml
rusk-abi/src/host.rs
rusk-abi/src/hosted.rs
rusk-abi/src/lib.rs
rusk-abi/src/public_input.rs
rusk-abi/tests/contracts/host_fn/src/lib.rs
rusk-abi/tests/lib.rs

Resolves #247
The verifier key was upgraded to contain also the public input positions
to avoid unnecessary complexity while building the static data of the
used circuits.
This change is transparent to the users of plonk library, so we needed
to remove the public inputs positions as a parameter of the ABI and
treat the verifier agnostically as a vec of u8.

ABI `verify_proof` with Plonk VerifierData

---

.github/workflows/profile_ci.yml

In order to be able to generate the keys and keep them on
the cache, it was needed a fix in the workflow to stop requesting
an old rustc nightly version as well as the need to use rustfmt as a
component of the workflow.
Resolves: #258

Fix key_generation workflow for rusk build

---

rusk-profile/src/lib.rs
rusk/build.rs

- Fix wrong usage of `with_extension` for `get_prover` and `get_verifier`
- Remove nested match patterns to make code more readable using functions
- Replace `for..in` loop with `map` to simplify the code
- Use `with_extension` instead of `set_extension` where needed
- Use `matches!` and functions instead of nested match pattern
- Remove unnecessary `Box::new` (since we don't need to own the type)
Resolves: #290

Fix `get_prover` and `get_verifier` and general clean up

---

circuits/transfer/Cargo.toml
circuits/transfer/Makefile
circuits/transfer/src/error.rs
circuits/transfer/src/execute.rs
circuits/transfer/src/execute/builder.rs
circuits/transfer/src/execute/variants.rs
circuits/transfer/src/lib.rs
circuits/transfer/src/send_to_contract_obfuscated.rs
circuits/transfer/src/send_to_contract_transparent.rs
circuits/transfer/src/withdraw_from_obfuscated.rs
circuits/transfer/tests/execute.rs
circuits/transfer/tests/keys/mod.rs
circuits/transfer/tests/send_to_contract_obfuscated.rs
circuits/transfer/tests/send_to_contract_transparent.rs
circuits/transfer/tests/withdraw_from_obfuscated.rs

Currently the transfer circuit is a single struct implementation that
will iterate its attributes to produce different circuits.
This doesn't work with the new circuit hasher structure because it uses
the gadget code to generate the identifier of a circuit.
The current implementation will produce different circuits with the same
gadget code depending on the inputs.
This commit splits the `ExecuteCircuit` into different concrete
structures and uses an enum mapping to encapsulate the inputs and
outputs operations.
Resolves #275

transfer-circuits: Split ExecuteCircuit into separated instances

---

circuits/transfer/CHANGELOG.md
circuits/transfer/src/error.rs
circuits/transfer/src/execute.rs
circuits/transfer/src/execute/variants.rs
circuits/transfer/src/lib.rs
rusk/Cargo.toml
rusk/build.rs

The transfer circuits keys were removed from the rusk build script while
the update to `dusk-plonk` latest was being performed.
With the recent change on transfer circuits to comply with plonk latest
and implement code-hasher, these keys can be reintroduced to the script.
Resolves #302

rusk: Add transfer circuits in keys build scheme

---

.github/workflows/dusk_ci.yml
.github/workflows/profile_ci.yml
circuits/bid/Cargo.toml
contracts/bid/Makefile
contracts/transfer/Makefile
macros/code-hasher/Cargo.toml
macros/code-hasher/src/lib.rs
rusk/Makefile

Due to the fact that we're not printing directly the AST but we're
stringlyfiyng it, the ID's that the macro was producing were different
IDs for the same circuit when different toolchains were used (most
likely due to padding and formatting issues).
- Fixed the `code-hasher` macro to avoid `String` usage and just use AST prints to avoid formatting.
- Updated Makefiles of the workspace to provide extra-verbose output when calling `rustc`.
Resolves: #314

Fix keys cache process

---

rusk-abi/CHANGELOG.md
rusk-abi/Cargo.toml
rusk-abi/src/host.rs
rusk-abi/src/hosted.rs
rusk-abi/src/lib.rs

- Add `stake_contract` method for host and hosted 
- Add `transfer_contract` method for host
- Add `gen_contract_id` method for host
- Remove `transfer_address` and `stake_address` methods for host
Resolves: #337, #338

rusk-abi: ensure contracts' ids are "BlsScalar-friendly"

---

.github/workflows/dusk_ci.yml
Makefile
circuits/transfer/tests/execute.rs
contracts/bid/src/lib.rs
contracts/transfer/src/transfer/circuits.rs

- Change workflow to run on self hosted
- Change `Makefile` to have more parallels builds and tests
- transfer-contract: Change `execute` test to run in parallel
-  bid-contract: Use `RUSK_PROFILE_PATH` to include the verifier data
- transfer-contract: Use `RUSK_PROFILE_PATH` to include the verifier data
We assumed the profile path for the verifier data was always the
repository root, but this might not be the case.
For example, the rusk profile path on self hosted is outside
the docker container (where the repos are mounted).
Resolves: #367

Improve CI execution time

---

.github/workflows/dusk_ci.yml
rusk/build.rs

The default behavior it's still to remove the old keys, so if the
env var is not set (e.g. locally) nothing is changed.
Resolves: #412

Add `RUSK_KEEP_KEYS` env var to build.rs and CI

---

circuits/transfer/src/send_to_contract_obfuscated.rs
circuits/transfer/src/types.rs
circuits/transfer/src/withdraw_from_obfuscated.rs
circuits/transfer/tests/send_to_contract_obfuscated.rs
circuits/transfer/tests/withdraw_from_obfuscated.rs
contracts/transfer/src/transfer/circuits.rs
contracts/transfer/tests/transfer.rs
contracts/transfer/tests/wrapper/mod.rs
rusk/build.rs

- Avoid using a long list of anonymous parameters in methods.
- Remove anonymous `new` constructors in favour of explicit named parameters
- Regenerate rusk keys
Resolves #407

Use `DeriveKey` in WFO/STCO messages

---

rusk/src/bin/main.rs

If a clap arg is configure to not take a value, the `value_of` is alway `None`
Fix #423

Fix kadcast auto broadcast

---

rusk/CHANGELOG.md
rusk/Cargo.toml
rusk/src/bin/main.rs
rusk/src/lib/services.rs
rusk/src/lib/services/prover.rs
rusk/src/lib/services/prover/handler.rs
rusk/tests/common/mod.rs
rusk/tests/services/mod.rs
rusk/tests/services/pki_service.rs
rusk/tests/services/prover_service.rs
rusk/tests/tests.rs
schema/prover.proto
schema/state.proto

This is an implementation of the prover service for execute transactions. It also introduces some logic to create different socket for each instance of `TestContext`.
Resolves #401

Implement prover service

---

contracts/transfer/Cargo.toml
rusk-abi/Cargo.toml
rusk-recovery/Cargo.toml
rusk-recovery/src/state.rs
rusk/Cargo.toml
test-utils/transfer-wrapper/Cargo.toml

- rusk-recovery: Update rusk-vm from `0.7.0-rc` to `0.8.0-rc`
- rusk: Update rusk-vm from `0.7.0-rc` to `0.8.0-rc`
- test-utils: Update rusk-vm from `0.7.0-rc` to `0.8.0-rc`
- rusk-abi: Update rusk-vm from `0.7.0-rc` to `0.8.0-rc`
- transfer-contract: Update rusk-vm from `0.7.0-rc` to `0.8.0-rc`

Update to Rusk VM 0.8 (release candidate)

---

rusk/src/lib/services/prover.rs
rusk/src/lib/services/prover/handler.rs
rusk/tests/services/prover_service.rs
schema/prover.proto

Introduces prover services for STCT, STCO, WFCT, and WFCO.
The protos for the requests have a single field of bytes containing many variables serialized in sequence. The reason is this will help in the implementation of the extension using the wallet FFI.
Resolves: #437

Implement STCT, WFCT, etc... prover services

---

contracts/stake/Cargo.toml
contracts/transfer/Cargo.toml
contracts/transfer/tests/wrapper/alice/Cargo.toml
contracts/transfer/tests/wrapper/bob/Cargo.toml
rusk-abi/Cargo.toml
rusk-abi/tests/contracts/host_fn/Cargo.toml
test-utils/transfer-wrapper/Cargo.toml

Also bump the versions of other internal crates to reflect the changes
in PR #433.
Resolves: #455

Bump `rusk-abi` to `0.6.0`

---

rusk/Cargo.toml
rusk/src/bin/main.rs
rusk/src/lib/error.rs
rusk/src/lib/lib.rs
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs
rusk/tests/common/mod.rs
rusk/tests/services/state_service.rs

- Add `RuskBuilder` type
This builder helps to construct a `Rusk` instance for both tests and binary
use cases, ensure we're not risking on overwrite the wrong state during tests.
It also ensure we can clone safely a `Rusk` instance, while still retain not
only the state id, but the original backend.
It also include an optional `path` where to store the `state_id`, instead of
having hard coded - this was a problem since a misusage of that feature could
result in the binary state corruption during tests.
- Add private `execute_ephemeral_state_transition` method
This method encapsulate the logic of `execute_state_transition`, returning
both a `Response` for tonic and a `RuskState`.
In this way we can have `execute_state_transition` that discard the state,
`accept` that persist the state, …

rusk: Improve the ergonomics `Rusk` state API

---

contracts/transfer/Cargo.toml
contracts/transfer/src/transfer/host.rs
rusk/src/lib/error.rs
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs

rusk: Handle coinbases correctly
- Add emissions schedule
As defined in the economic paper, the emission schedule is the amount
of Dusk freshly minted each block not coming from spent gas.
- Add checking coinbase values
This checks if the coinbase values are what we expect from both the gas
fees and the emission schedule.
Resolves: #485
Resolves: #483
transfer: Add randomness and lift value logic
This supports lifting the logic of distribution of rewards to rusk to
also allow for checking incoming coinbases, and adds randomness to the
creation of notes.
Resolves: #485

Handle coinbases correctly

---

rusk/src/lib/encoding.rs
rusk/src/lib/services/state.rs
schema/state.proto

- Add Preverify to the state schema
- rusk: Add the Preverify service to rusk
- rusk: Add conversion between phoenix Fee and gRPC Fee type
See also: #458

Initial Preverify implementation

---

rusk-wallet/CHANGELOG.md
rusk-wallet/src/lib/error.rs
rusk-wallet/src/lib/mod.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

Provides users with an interactive mode by default if no subcommand is specified at runtime.
Interactive mode guides the user through the different commands, making it easier for first-timers to get a hang of the CLI tool.
Supports wallet creation, recovery, and all `wallet_core` commands.
Closes #492

Add an interactive mode to the wallet CLI

---

contracts/transfer/src/transfer.rs
contracts/transfer/src/wasm/internal.rs
contracts/transfer/tests/circuits.rs
rusk-abi/Cargo.toml
rusk-abi/src/lib.rs
rusk-abi/src/module/host.rs
rusk/src/lib/services/prover.rs
rusk/src/lib/services/state.rs
test-utils/transfer-wrapper/src/wrapper.rs

- `rusk`: Add `preverify` method
- Add `any_nullifiers_exists` to `RustState`
- Add `preverify` method to `RuskProver`
- `transfer-contract`:  Change `any_nullifiers_exists` scope
- `rusk-abi`: release a new version needed for Rusk's preverify
- Add `contract_to_scalar` function
- Change `verify_proof` to be also in host code not only hosted
Resolves: #458
Co-authored-by: Eduardo Leegwater Simões <eduardo@dusk.network>

Expose a pre-verification of a transaction

---

contracts/stake/Cargo.toml
contracts/stake/src/contract.rs
contracts/stake/tests/stake.rs
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs

This PR implements `GetProvisioners` and `Echo` for the purposes of finalizing the services surface.

Implement the missing gRPCs

---

contracts/transfer/src/transfer/host.rs
contracts/transfer/tests/circuits.rs
rusk-abi/src/module/host.rs
rusk-abi/src/module/public_input.rs
rusk/Cargo.toml
rusk/src/lib/services/network.rs
rusk/src/lib/services/prover.rs
rusk/src/lib/services/prover/execute.rs
rusk/src/lib/services/state.rs
rusk/src/lib/transaction.rs
rusk/tests/common/mod.rs
rusk/tests/services/mod.rs
rusk/tests/services/prover_service.rs
rusk/tests/services/state_service.rs
rusk/tests/services/transactions.rs
schema/transaction.proto

- rusk: Fix typo on check the number of coinbase txs
- transfer-contract: canonicalize Note in `mint`
- rusk: Add `transactions` tests to cover all our gRPC services (but kadkast)
- Add `Block` trait with `Future` auto trait in `tests/common`
This simplify the code in our tests when we're deailing with async
code.
- rusk: Fix issues in `RuskProver`
- Update the code to be compatible with `dusk-wallet-core 0.8`
- Remove cache for `ProverKey` in `RuskProver`
- Change the circuit in `RuskProver` to be instantiated as  `ExecuteCircuit::default()`
- Change the `set_fee` in `RuskProver` to be called only if there is no
`Crossover`.
- rusk: Update `dusk-wallet-core` from `0.6` to `0.8.0-rc`
-  Remove unused message and service for transaction
- Fix a typo for `tx_hash` in `ExecutedTransaction`
- …

Fix prover

---

rusk-wallet/Cargo.toml
rusk-wallet/src/lib/crypto.rs
rusk-wallet/src/lib/error.rs
rusk-wallet/src/lib/mod.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/store.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

Introduce `Export` command to export BLS key-pair into a file.
Refactored `crypto` module to allow for variable sized data encryption.

wallet: Add `Export` command 

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/store.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

Wallet password is optionally retrieved from environment variable `RUSK_WALLET_PWD`.
When this env var is set, the CLI will not ask for interactive user authentication when performing operations that require it.
Added wallet name to the exported key file as well. In multi-wallet scenarios, exported keys were overwritten without this.
Changed to using `serde` for file encoding as suggested by @herr-seppia 
Bumped to `0.1.2`
Resolves: #495

wallet: Add "headless" mode and fix Export in multi-wallet scenarios

---

contracts/stake/Makefile
contracts/transfer/Makefile
rusk-recovery/src/state.rs

This ensures reproducible builds of the genesis contracts by:
- Including a `Cargo.toml` in the repository, ensuring a tracking of dependencies.
- Setting `--remap-path-prefix` to strip system path info from binaries,
in both a local build using `source .env`, and the CI environment.
- Failing the CI if the contract bytecode doesn't equal the included
`wasm.sum` file. This ensures changes of bytecode are tracked.
Resolves: #509

Achieve reproducible build for contracts 

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/crypto.rs
rusk-wallet/src/lib/error.rs
rusk-wallet/src/lib/mod.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

Adds "Offline" mode to the wallet CLI - Commands that don't require Rusk can be executed.
Includes *notable* UX improvements:
- Add live validation to user interactive input
- Better navigation through interactive menus
- Fix bad UX when creating a wallet that already exists
- "Pause" after result to give user time to digest info
- _Disable "Extend stake" command_
Resolves: #499
Resolves: #507

wallet: Add offline mode and improve overall UX

---

.github/workflows/dusk_ci.yml
rusk-recovery/Cargo.toml
rusk-recovery/Makefile
rusk-recovery/src/bin/state.rs
rusk-recovery/src/state.rs

This is accomplished by:
- Changing the `RUSK_OVERWRITE_STATE` flag to `RUSK_BUILD_STATE` and
building the state only on the condition of it being present.
- Adding code to download and unpack the state zip from DigitalOcean
into `RUSK_PROFILE_PATH` - where the state is expected to be.
- Removing the code to check the state root against a known value.
See also: #509
ci: add always building the state
The state should always be built in the CI, therefore the
`RUSK_BUILD_STATE` variable is hardcoded and the now obsolete
`RUSK_OVERWRITE_STATE` removed.

Download the state by default

---

contracts/transfer/src/transfer.rs

This method is needed from rusk and the wallet core to calculate the
balance properly.
See also: dusk-network/wallet-core#41
Resolves: #519

transfer-contract: add `find_existing_nullifiers` to transfer contract

---

contracts/transfer/Cargo.toml
contracts/transfer/src/transfer.rs
rusk-abi/Cargo.toml
rusk-abi/tests/lib.rs
rusk-recovery/Cargo.toml
rusk-recovery/src/state.rs
rusk/Cargo.toml
rusk/src/lib/error.rs
rusk/src/lib/lib.rs
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs
rusk/tests/common/mod.rs
rusk/tests/rusk-state.rs
rusk/tests/services/prover_service.rs
rusk/tests/services/state_service.rs
rusk/tests/services/transactions.rs
schema/state.proto
test-utils/transfer-wrapper/Cargo.toml
test-utils/transfer-wrapper/src/wrapper.rs

- transfer-contract: Update `rusk-vm` from `0.8.0-rc` to `0.10.0-rc`
- rusk-abi: Update `rusk-vm` from `0.8.0-rc` to `0.10.0-rc`
- rusk-recovery: Update `rusk-vm` from `0.8.0-rc` to `0.10.0-rc`
- Add `FindExistingNullifiers` gRPC service to the schema
- test-utils: Update rusk-vm from `0.8.0-rc` to `0.10.0-rc`
- rusk: Update dependencies
- Update `dusk-wallet-core` from `0.8.0-rc` to `0.9.0-rc`
- Update `rusk-vm` from `0.8.0-rc` to `0.10.0-rc`
- Add `hex` version `0.4`
- rusk: Add a `Error::Other` for any `std::error::Error` type
- rusk: Change `Rusk` to keep a shared ref of `NetworkState`
Now `NetworkState` is thread safe, so there is no need to keep just the
`NetworkStateId` and `restore` from disk every call.
- rusk: `RuskState` refactoring
- Change `RuskState` to hold an `Arc` `Mutex` …

E2E Rusk test

---

rusk/src/lib/services/state.rs
schema/state.proto

- rusk: Add implementation for gRPC `Revert` method
- Add `Revert` to the schema
Resolves: #533

 Expose the capability to revert the state via gRCP

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/mod.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

The default gas_price being zero makes it such that a change note is
not generated by default, ensuring the execute proof doesn't pass
verification. Since by default this shouldn't be the case we should
change it to a normal value - the choice here being 1 Dusk.
Resolves: #539
See also: #535
Follow-up of #540

wallet: change default gas price to 0.001 Dusk

---

rusk-wallet/src/lib/mod.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/wallet.rs

The denominations are normalized to always be asked in Dusk from the
user, and converted to μDusk when used internally. Some sane - aka pass
verification - defaults are added.
Gas price is asked from the user as well. The gas price, gas limit and
transfer amount have a lower limit of 1 μDusk, since anything lower is
floored.

wallet: fix denominations and ask for gas price

---

.github/workflows/dusk_ci.yml
rusk-recovery/Cargo.toml
rusk-recovery/src/bin/state.rs
rusk-recovery/src/state.rs

A `force` flag is added, allowing one to always build or download the
state regardless of the existing state in the profile directory. The
flag is added in the CI for good measure.
Resolves: #518

recovery: add forcing the state to build/download

---

rusk/src/lib/services/state.rs
rusk/tests/services/transactions.rs

The new coinbase transaction contains both the note for Dusk and the
note for the block generator serialized in sequence. The transaction
hash is calculated using `rusk_abi::Hasher` instead of the significantly
more expensive `dusk_poseidon::sponge::hash`. This is in line with how
normal transfer transactions are hashed.
Resolves: #529

rusk: reduce number of coinbase transactions to 1

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/clients.rs
rusk-wallet/src/lib/wallet.rs
rusk/Cargo.toml
rusk/src/lib/services/prover/execute.rs
rusk/tests/services/prover_service.rs
rusk/tests/services/transactions.rs
schema/prover.proto

rusk: upgrade to wallet-core `0.10.0-rc.0`
- Change to return proof from `prove_execute` instead of the full tx
- Refactor `wallet_grpc` test to generate blocks outside of `TestProverClient`
Resolves: #556
---
wallet: upgrade to wallet-core `0.10.0-rc.0`
- Change to print transaction hash in main process
- Adapt ProverClient to return tx in `compute_proof_and_propagate`, and take the proof from upstream instead of the full tx
Resolves: #557
Co-authored-by: Abel Elbaile <abel@dusk.network>
---
schema: change ProveExecute to return proof
See also: #556

Change ExecuteProverResponse to contain the proof

---

rusk-wallet/src/lib/clients.rs
rusk-wallet/src/main.rs

Updates help text to clearly state we're using microDusk to transact with the CLI
Removed unused tx hash debug print.
Resolves: #565

wallet: clarify input Dusk unit for all commands

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/README.md
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/main.rs

***Allow for headless wallet creation***
- Adds support for `RUSK_WALLET_PWD` env variable in wallet creation.
- Adds `--skip-recover` flag to prevent the user from being prompted to confirm the safe backup of recovery phrase.
Resolves: #569
---
***Add transaction outputs***
- TX outputs are now in their proper place
See also: https://github.com/dusk-network/wallet-core/pull/43

wallet: Release `0.2.4`

---

rusk/Cargo.toml
rusk/src/lib/services/network.rs
schema/network.proto

- Add `AliveNodes` to network.proto 
- rusk: Add gRPC to retrieve active nodes in the network
- Update minimum version of kadcast dependency to `0.4.0-rc.5`
Resolves #571

Get ActiveNodes through Network service

---

contracts/stake/Cargo.toml
contracts/stake/src/contract.rs
contracts/stake/src/contract/transaction.rs
contracts/stake/src/error.rs
contracts/stake/src/lib.rs
contracts/stake/src/stake.rs
contracts/stake/src/wasm.rs
contracts/stake/src/wasm/bridge.rs
contracts/stake/tests/stake.rs
rusk-recovery/Cargo.toml
rusk-recovery/src/state.rs
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/clients.rs
rusk/src/lib/services/state.rs
rusk/tests/services/state_service.rs
rusk/tests/services/transactions.rs
schema/stake.proto
schema/state.proto

stake: change contract to new specification
- Expiration is deprecated, and all associated functionality is removed.
- The messages to sign are changed, with the notable addition of
`created_at` - meant to be similar but not equal to the block height.
This is done since it is effectively impossible to sign and prove the
transaction in the timespan of a single block.
Resolves: #566

Change stake contract to new specification

---

rusk-recovery/Cargo.toml
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/clients.rs
rusk/Cargo.toml
rusk/src/bin/config.rs
rusk/src/bin/config/grpc.rs
rusk/src/bin/config/kadcast.rs
rusk/src/bin/config/wallet.rs
rusk/src/bin/main.rs
rusk/tests/services/mod.rs
rusk/tests/services/prover_service.rs
rusk/tests/services/stake.rs
rusk/tests/services/transfer.rs

rusk: upgrade to `dusk-wallet-core` `0.11.0`
- Add test performing a stake and stake withdrawal transaction and
passing them through the normal block generator procedure.
Resolves: #560
---
wallet: upgrade to `dusk-wallet-core` `0.11.0`
---
wallet: bump version to `0.3.0`

Add working stake test

---

rusk/Cargo.toml
rusk/src/lib/services/state.rs
schema/state.proto

rusk: persist on command rather than automatically
- Remove `state.persist()` call on `accept`, `finalize`, and `revert`
- Add persist RPC that takes the state root, and calls
`state.persist()` if the current root matches
Resolves: #572

Persist on demand rather than automatically

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/README.md
rusk-wallet/src/lib/store.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

**Enhance `export` command**
- Default to current wallet directory for exported keys.
- Add an additional plain text file with the base58-encoded public key.
Resolves: #574

Wallet: Enhance `export` command

---

contracts/stake/Cargo.toml
contracts/stake/src/lib.rs
contracts/stake/tests/stake.rs
contracts/transfer/src/wasm/internal.rs
rusk-abi/Cargo.toml
rusk-abi/src/dusk.rs
rusk-abi/src/lib.rs
rusk-recovery/Cargo.toml
rusk-recovery/src/state.rs
rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/mod.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/wallet.rs
rusk/src/lib/state.rs
rusk/tests/services/stake.rs

Changes the denomination to nDusk. This is a cross project change, but I try to centralize denomination "logic" in `rusk-abi`. If at some point we want to change this, that is where it would be done.
Resolves: #582

Change denomination to nDusk

---

rusk-wallet/src/lib/store.rs
rusk-wallet/src/main.rs

Prevents interactive wallet selection from displaying non .dat files.
**Note:** It is of course true that one can have a `.dat` file that is not an actual wallet and it will be displayed in the list. However:
1.  We already have the proper checks and errors for that.
2. Reading every file just to display a list seems a bit overkill.
2. Even if we did, files generated with CLI `v0.1` don't have the `magic` prefix that identifies them as a wallet, yet we still support reading them.
Resolves: #585

wallet: fix interactive wallet selection

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/README.md
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/main.rs

Parameter is optional and defaults to Rusk address as one would expect.
Separation of the Prover service is only supported in TCP mode until there is a solid reason to support it in UDS as well. After all, the point here is targeting a different machine with different hardware altogether.
For debugging purposes in a local environment, the user can still use TCP, which on loopback interfaces and `localhost` addresses is highly optimized by the OS anyways.
Resolves #612

rusk-wallet: Add configuration item to specify the prover URL

---

rusk/src/lib/services/state.rs
rusk/src/lib/state.rs
rusk/tests/services/mod.rs
rusk/tests/services/multi_transfer.rs

- Add `fork` method to `RuskState` allowing for copying the underlying
`NetworkState`
- Change `execute_state_transition` to keep transactions based on
`gas_spent` instead of `gas_limit`
Resolves: #605

rusk: fix high gas limit TXs taking longer

---

rusk/src/lib/encoding.rs
rusk/src/lib/services/state.rs
schema/transaction.proto

- Add `Error` type to `ExecutedTransaction`
- rusk: Add Transaction's error conversion and propagation
Resolves  #599

 Transaction failures should be returned upon block acceptance

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/clients.rs
rusk-wallet/src/lib/crypto.rs
rusk-wallet/src/lib/error.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/store.rs
rusk-wallet/src/lib/wallet.rs
rusk-wallet/src/main.rs

This allowed us to:
1. Remove the `Box<_>` "hack" for the wallet core errors that carried the generics implementation with them.
2. Implement better error messages in an elegant, organized manner.
Resolves: #629
---
We're no longer leaving these defaults in Clap derives, because that prevents us from determining if the user actually passed in those arguments or not. We instead handle the defaults manually. As a result, the `LocalStore` is now in charge of everything related to the file system.
This allowed us to:
1. Understand when the user is overriding the wallet file.
2. Actually use `data_dir` for interactive wallet chooser.
*Note:* For wallet creation in interactive mode, we're still using the default path. This can be easily adjusted in the near future.
Resolves: #630 
---
We won't …

rusk-wallet: Better error mgmt, path handling and UX

---

rusk-wallet/Cargo.toml
rusk-wallet/src/lib/wallet.rs
rusk/Cargo.toml
rusk/tests/services/multi_transfer.rs
rusk/tests/services/transfer.rs

The new version adds the `spendable` field to the balance calculation,
which determines the maximum amount a user can spend in a single
transaction, due to there being a maximum number of input notes.
Resolves #636

Upgrade `dusk-wallet-core` to latest version

---

rusk-wallet/src/lib/wallet.rs

rusk-wallet: Remove balance prerequisite for GetBalance operation

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/README.md
rusk-wallet/config.toml
rusk-wallet/src/lib/config.rs
rusk-wallet/src/lib/error.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/lib/store.rs
rusk-wallet/src/main.rs

- `data_dir` is now used across the board
- create configuration file if not exists
- notify user when defaulting configuration
- main flow is easier to understand
- separate prover from rusk address config values
- explicit connection errors
Resolves #647
Resolves #655
Resolves #656
Resolves #659

rusk-wallet: major refactor in path handling and user flow

---

rusk-wallet/CHANGELOG.md
rusk-wallet/Cargo.toml
rusk-wallet/src/lib/clients.rs
rusk-wallet/src/lib/config.rs
rusk-wallet/src/lib/error.rs
rusk-wallet/src/main.rs

Query block height from the GraphQL endpoint.
NOTE: GraphQL can be modified in the `config.toml` under the `[chain]` section. However, it has not been included as a runtime argument for now.
See also #650
See also #651

rusk-wallet: Implement `fetch_block_height` for State client

---

rusk-wallet/Cargo.toml

rusk-wallet: enable `bundled` feature for `rusqlite`

---

rusk-wallet/CHANGELOG.md
rusk-wallet/README.md
rusk-wallet/config.toml
rusk-wallet/src/lib/config.rs
rusk-wallet/src/lib/prompt.rs
rusk-wallet/src/main.rs

Currently we are using a fallback strategy to pick sequences of
configurations until a valid one is found.
This is misleading in the sense of making the user believe he is working
with a valid configuration, when in fact the wallet is using a different
one - possibly with undesirable parameters.
Resolves #670

wallet: Invalid config shouldnt fallback

---

.github/workflows/wallet_build.yml

- Change `build_and_test` step action name to `build_and_publish`
- Add rustfmt as component
- Change action to use toolchain defined in `rust-toolchain` file
- Change action name to be consistent with other actions
- Fix syntax error on build wallet CI: missing name from section
- Fix wrong hyphens in build wallet CI
- Add OS to artifact naming to avoid overwrite
- Add input for building a specific wallet commit/branch
- Add tgz creation for Linux + semver naming
- Fix semver env export by defining it as env in run step
- Fix wrong output grab from shell
- Fix wrong env var export for CI
- Add quotes to packer for env variable interpolation
- Fix path for artifact archive
- Add CHANGELOG and README to release archive
See also #676

Generate wallet binary, upload artifact

---

rusk-profile/Cargo.toml
rusk-profile/src/lib.rs

No need to check if the keys exist, because it's guaranteed to be
checked by the get_verifier and get_prover functions.
Resolves #685

rusk-profile: Remove keys existance duplicated checks

---

rusk-recovery/src/keys.rs

Since `keys_for` doesn't check for key existence, a `get_verifier` is called to check the presence of the keys in the filesystem
Resolves #695

rusk-recovery: Fix key generation

---

contracts/transfer/Cargo.toml
contracts/transfer/src/transfer.rs
contracts/transfer/src/transfer/tree.rs
rusk-schema/CHANGELOG.md
rusk-schema/Cargo.toml
rusk-schema/protos/state.proto
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs
rusk/tests/services/state_service.rs
test-utils/transfer-wrapper/Cargo.toml
test-utils/transfer-wrapper/src/wrapper.rs

To achieve a proper caching strategy, a wallet requires knowledge of which block height it should sync its known notes from. This PR solves this problem by returning the maximum block height of the notes it processes in `GetNotesOwnedBy`.
Resolves #651

Return latest block height from `fetch_notes`

---

rusk-schema/CHANGELOG.md
rusk-schema/Cargo.toml
rusk-schema/protos/state.proto
rusk/src/lib/services/state.rs

The PR adds a check on nullifiers in all state transitions. In the "accepting" set of state transitions Rusk will now error if nullifiers are repeated. In execute state transition the transactions containing nullifiers previously used by the same transaction set will be discarded.
Resolves #704

Add check for repeated nullifiers

---

contracts/transfer/Cargo.toml
contracts/transfer/src/lib.rs
contracts/transfer/src/transfer.rs
rusk-schema/CHANGELOG.md
rusk-schema/Cargo.toml
rusk-schema/protos/state.proto
rusk/Cargo.toml
rusk/src/lib/lib.rs
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/stake.rs
rusk/tests/services/state_service.rs
rusk/tests/services/transfer.rs

The new `GetNotes` RPC is capable of streaming notes starting from a particular block height, and optionally filter them by a given view key. This allows for filtering on the server side (less private) and also on the client side (private) and effectively solves the ever growing memory required to execute `GetNotesOwnedBy`.
We deprecate `GetNotesOwnedBy` by setting `[deprecated=true]` on the fields of `GetNotesOwnedByRequest`. Any client using the new version will get a compiler warning that this request is deprecated.
Resolves #702

Add `GetNotes` allowing for streaming notes to client

---

rusk/Cargo.toml
rusk/src/bin/main.rs
rusk/src/bin/services.rs
rusk/src/lib/services.rs
rusk/src/lib/services/version.rs

This PR introduces two key things:
Every request received on the `State`, `Prover` or `Network` services will go through an `Interceptor` that will extract `x-rusk-version` from the headers and compare it to current Rusk version using _semver_ criteria.
All responses now include a header field ( `x-rusk-version`) containing current Rusk version.
Resolves #717

Introduce versioning gRPC middleware

---

rusk/Cargo.toml
rusk/src/lib/lib.rs
rusk/src/lib/services/state.rs
rusk/src/lib/state.rs
rusk/tests/rusk-state.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/stake.rs
rusk/tests/services/state_service.rs
rusk/tests/services/transfer.rs

This code makes usage of `unsafe` to handle manually the dropping of the raw Mutex.
Basically the whole state is locked until dropped, in order to avoid parallel calls to interfere which each other.
A similar problem was mentioned [here](https://stackoverflow.com/questions/70806839/passing-mutex-and-mutexguard-in-a-struct) and the OP solved using a crate called [lockpool](https://crates.io/crates/lockpool) but it's not well-known and doesn't look solid  and maintained.
The approach used in this PR is a pattern permitted by `parking_lot`, so between the two I would prefer the `unsafe`. But we might look for an `unsafe`-free alternative in the future.
> Note:
> We could improve using an `RwLock` instead of `Mutex` but it will make the API more complex and we will have to repeat the code; so …

rusk: RuskState drops unstaged commits too aggressively

---

contracts/stake/src/contract.rs
contracts/stake/src/contract/transaction.rs
contracts/stake/src/lib.rs
contracts/stake/src/wasm.rs
contracts/stake/src/wasm/bridge.rs
contracts/stake/tests/stake.rs
rusk-recovery/src/provisioners.rs
rusk-recovery/src/state.rs
rusk/tests/services/stake.rs
test-utils/transfer-wrapper/src/lib.rs
test-utils/transfer-wrapper/src/wrapper.rs

Implement TX_ADD_ALLOWLIST operation:
- Stake contract now belong to a `owner`
- The `owner` can allow BLS public keys
- A `stake` transaction fail if it doesn't belong to an allowed key
* Set stake contract ownership
* Allow existing BLS keys
* Support stake contract's allowlist
* Adapt tests to allow the BLS public keys
---------
Resolves #732

Implement stake allowlist

---

.github/workflows/dusk_ci.yml
rusk/Makefile

- rusk: Change Makefile to enable multi-thread tests
The flag was used when the rusk state was shared across multiple tests,
but this is not the case anymore.
- Remove Cargo cache from CI
On the self hosted github action machine, it's actually faster due to
the number of cores rebuild the cargo cache than actually store it and
retrieve it.

Make the CI faster

---

rusk-recovery/Cargo.toml
rusk/Cargo.toml

rusk: change `rustc_tools_utils` dep to always use `0.2.0`
rusk-recovery: change `rustc_tools_utils` dep to always use `0.2.0`
The version `0.2.1` of rustc_tools_utils introduced a breaking change, the 
`get_channel` now returns a `String` instead of an `Option<String>`.
Resolves #745

Fix build after rustc_tools_utils upgraded

---

Makefile
rusk-recovery/Makefile
rusk-recovery/src/state/zip.rs

rusk-recovery: add `INITFILE` to state recipe
- The `INITFILE` default to a `localnet.toml` if not overridden
- Removed a leftover during the unzip
Resolves #747

Add `state` recipe

---

Makefile
rusk-recovery/Cargo.toml
rusk-recovery/config/example.toml
rusk-recovery/config/genesis.toml
rusk-recovery/config/testnet.toml
rusk-recovery/src/bin/state.rs
rusk-recovery/src/state.rs
rusk-recovery/src/state/snapshot.rs
rusk-recovery/src/state/zip.rs

- Add `base-state` to init config
- Remove `build` flag (`RUSK_BUILD_STATE` env)
- Remove `contracts` flag (`RUSK_PREBUILT_CONTRACTS` env)
- Fix `make run`
Resolves #750

rusk-recovery: support external base state

---

rusk-recovery/config/testnet.toml
rusk-recovery/config/testnet_remote.toml
rusk-recovery/src/bin/state.rs
rusk-recovery/src/state/snapshot.rs

Change the default init toml to use the prebuilt testn…
Resolves #755

rusk-recovery: change the default init toml

---

.github/workflows/dusk_ci.yml
contracts/stake/src/contract.rs
contracts/stake/src/wasm.rs
contracts/stake/tests/stake.rs

This PR aim to lower the gas used by the stake contract which double after the allowlist has been introduced.
It remove the allowlist field completely.
With the allowlist field
```
Gas spent 2947384232 [STAKE]
Gas spent 2574033720 [UNSTAKE]
Gas spent 2620889741 [WITHDRAW]
```
Without the allowlist field
```
Gas spent 1753138018 [STAKE]
Gas spent 1678351617 [UNSTAKE]
Gas spent 1725233908 [WITHDRAW]
```
The central point of this PR is to change the `load_mut_stake` to avoid insert a default stake if not found.
A default stake is added only during the allow transaction
P.S: This PR aim to change only the stake-contract crate, so a lot of `Result` are still present in the function's signatures to avoid change the consumer libraries

stake-contract: Remove `allowlist` field

---

Makefile
README.md
circuits/Makefile
circuits/transfer/Makefile
contracts/Makefile
contracts/stake/Makefile
contracts/transfer/Makefile
macros/Makefile
macros/code-hasher/Makefile
rusk-abi/Makefile

This PR implements #782 
With this changes, it is possible to build everything without running tests, allowing to save time.
This is done by running `make all`.
At the same time, for compatibility reasons, the current behavior of `make test` is maintained (i.e., it builds everything first and then run tests).
To give a hint on the performance difference,
on my machine, `make test` takes around 40 minutes to complete (in a new setup),
while 'make all' only takes 15 minutes.

Add 'all' target to 'make'

---

contracts/governance/Cargo.toml
contracts/governance/src/collection.rs
contracts/governance/src/governance.rs
contracts/governance/src/lib.rs

Adds functionality that mints new tokens if balance is insufficient during transfer. Adds a `map` feature for the contract to use a `Vec` instead of a `dusk_hamt::Map`

Add vector feature, mint tokens on tranfers

---

rusk-recovery/Cargo.toml
rusk-recovery/src/bin/state.rs
rusk-recovery/src/state.rs
rusk-recovery/src/state/tar.rs
rusk-recovery/src/state/zip.rs
rusk/Cargo.toml
rusk/src/bin/ephemeral.rs

- Use `tar` module as entry point for all the archive stuff
- Fallback tar to zip
See also #740

rusk-recovery: Add support for tar archives

---

node/Cargo.toml
node/src/bin/main.rs
node/src/chain/mod.rs
node/src/data/mod.rs
node/src/database/mod.rs
node/src/database/rocksdb.rs
node/src/lib.rs
node/src/mempool/mod.rs

fixes #806
With this PR we integrate RocksDB and implement briefly the main database operations  like add/fetch block, add/fetch candidate block.
Basic database transaction attributes are also addressed - like isolation and atomicity (durability is natively provided in RocksDB by enabling Write-Ahead-Log feature) .
In another issue/PR,  Block Transaction data and additional lookup indexes will be added. More Database APIs (like fetch block exists etc) will be also added.
Column families:
- CF_LEDGER - stores verified/accepted blocks and lookup indexes. Persisted to disk.
- CF_CANDIDATES - stores a list of candidates block needed by a consensus round. They will be usually stored in L0 (memtable-only)

node: Integrate RocksDB with two column families

---

contracts/governance/Cargo.toml
contracts/governance/src/governance.rs
contracts/governance/tests/executor.rs
contracts/governance/tests/governance.rs
contracts/governance/tests/tx.rs
test-utils/transfer-wrapper/src/wrapper.rs

Add `unspent_notes` utility method
Add tests
Fix some error in the contract:
- Fix `SeedAlreadyUsed` when transfer insufficient funds
- Fix signature verification when not compiled for wasm
Resolves #833

Add `governance-contract` tests

---

contracts/governance/src/governance.rs
contracts/governance/src/lib.rs
contracts/governance/src/wasm/bridge.rs
contracts/governance/tests/executor/builder.rs
contracts/governance/tests/executor/mod.rs
contracts/governance/tests/executor/tx.rs
contracts/governance/tests/governance.rs

- Update `unspent_notes` to find the better note for the tests
- Change the `broker` to be a `PublicKey`
- Add a new `fee` transaction to the Governance contract
- Change the `Transfer` struct to support optional `from` and `to`, fields, in order to allow for transfers to and from the `broker` account
- Added new utility functions to `executor/builder.rs` to build `Transfer` objects with optional `from` and `to` fields, to simplify test code
- Added a new test case in `governance.rs` to test the `fee` transaction
Resolves #845

governance-contract: Use the `broker` inside the contract's logic

---

node-common/Cargo.toml
node-common/src/ledger.rs
node/Cargo.toml
node/src/database/rocksdb.rs

This remove the `fake` dependency from the node-common crate
In order to use it from `node` tests, a dev-dependency with the feature enabled is used

node: remove fake dependency from library

---

rusk-abi/Cargo.toml

The crates have broken semver, and need to be fixed to the given versions.

Fix `rkyv` and `wasmer` deps semver

---

node/Cargo.toml
node/default.config.toml
node/src/bin/config.rs
node/src/bin/main.rs
node/src/chain/consensus.rs
node/src/chain/genesis.rs
node/src/chain/mod.rs
node/src/database/mod.rs
node/src/database/rocksdb.rs
node/src/databroker/conf.rs
node/src/databroker/mod.rs
node/src/lib.rs
node/src/network/mod.rs

fixes #872 
fixes #887 
fixes #888  
The PR covers also a complete design and implementation of so called DataBroker service. Additionally, for testing purposes it makes it possible to sync-up blockchain state from genesis block (a sort of a basic sync-up procedure)

node: Implement DataBroker service to facilitate catch-up procedures

---

contracts/stake/tests/stake.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/transfer.rs
rusk/src/lib/lib.rs
rusk/tests/services/multi_transfer.rs

The transfer contract now returns the gas charged to a transaction, and
we use that as an input for the rewards calculation, as opposed to the
total gas spent in the execution of a contract.
Since the gas spent in the execution of the transfer contract is a
larger number than the gas charged to a transaction - due to the fact
that some code is executed *after* charging - this prevents a small
inflationary effect from happening.
Resolves https://github.com/dusk-network/rusk/issues/790

Return gas charged to transaction in `execute`

---

contracts/alice/Makefile
contracts/bob/Makefile

Fixes failing `make all` due to missing `all` target

Add 'all' target to alice and bob contracts

---

consensus/CHANGELOG.md
consensus/src/agreement/step.rs
consensus/src/selection/block_generator.rs
node-data/src/encoding.rs
node-data/src/ledger.rs
node-data/src/message.rs
node/src/chain/mod.rs

- Add `iteration` to block header
- Remove `step` from header's certificate
Ps: This is needed in order to reflect protocol changes made in dusk-network/dusk-blockchain#1500
Resolves #848

Add `iteration` to block header

---

consensus/Cargo.toml
consensus/src/lib.rs
consensus/src/merkle.rs
consensus/src/selection/block_generator.rs
consensus/src/selection/handler.rs
node-data/src/ledger.rs
node-data/src/message.rs
node/src/databroker/mod.rs

- Add `txroot` to block header
- Add `dusk-merkle` dependency
- Add `fn consensus::merkle::merkle_root` wrapping `dusk-merkle` to guarantee compatibility with dusk-blockchain's merkle-tree
- Add block header's `txroot` creation/verification
Resolves #847

consensus: add tx_root to block header

---

contracts/stake/src/lib.rs
contracts/stake/src/state.rs
contracts/stake/tests/stake.rs
contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs
contracts/transfer/src/tree.rs
contracts/transfer/tests/transfer.rs
rusk/src/lib/lib.rs
rusk/src/lib/transaction.rs
rusk/tests/config/gas-behavior.toml
rusk/tests/services/gas_behavior.rs
rusk/tests/services/mod.rs
rusk/tests/services/multi_transfer.rs

Transactions are now executed in three steps:
1. Call to "spend" to spend inputs and generate outputs
2. Execute possible contract call
3. Call to "refund" to refund the transaction some amount
This allows the host to specify *exactly* the amount of gas it wants to
charge a transaction. In this case we choose to charge 1_000_000 per
input of a transaction.
Resolves: https://github.com/dusk-network/rusk/issues/939

Split transaction execution in three parts 

---

consensus/src/commons.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/firststep/step.rs
consensus/src/secondstep/step.rs

consensus: Call VST once per a candidate block when this provisioner is extracted for both reductions

---

rusk/Cargo.toml
rusk/src/bin/main.rs
rusk/src/lib/lib.rs
rusk/src/lib/ws.rs

This is an implementation of a simple request-response protocol for querying the state of the chain over WebSockets.
When a stream is estabilished, a task is started to handle incoming requests. Once a request comes in we start a new task. This will report the result of the chain query which the request represents back to the stream handling task. This is done to ensure we don't block before another request can be received.
Resolves #933

rusk: initial impl of request-response queries

---

rusk/src/lib/http.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/http/event.rs
rusk/src/lib/http/rusk.rs

request http
```sh
curl --location --request POST 'http://127.0.0.1:8080/02/Chain' \
--header 'X-requestid: 3' \
--header 'Rusk-gqlvar-myvar: -1' \
--header 'X-asd: "asdasd"' \
--header 'Content-Type: application/json' \
--data-raw '{
"topic": "gql",
"data": "query ($myvar: Int) { block(height: $myvar) {header { height, prevBlockHash}, transactions {id}}}"
}' -v
```
response
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-asd: "asdasd"
< x-requestid: 3
< content-length: 149
< date: Fri, 28 Jul 2023 16:36:14 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
{"block":{"header":{"height":621,"prevBlockHash":"76414e3bd73c4a351ae537fe441b9dfdeb8dc652311affe9e2b5a355435513a3"},"transactions":[]}}           
```

rusk: Add http request impl

---

node/src/database/rocksdb.rs
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/block.rs

- Add blocks by range
- Add transactions by block range
- Fix `block_by_height` to return Option if no block is found
- Fix Transaction deserialization
```graphql
query { blockTxs(range: [288,10000], contract: "0100000000000000000000000000000000000000000000000000000000000000" ) { id, callData {fnName}}}
query { blockTxs(range: [288,10000] ) { id, callData {fnName}}}
query { blockTxs(last: 10, contract: "0100000000000000000000000000000000000000000000000000000000000000" ) { id, callData {fnName}}}
query { blockTxs(last: 10) { id, callData {fnName}}}
```

Add missing graphql handlers

---

consensus/src/aggregator.rs
consensus/src/user/sortition.rs
consensus/tests/sortition.rs

Resolves #907 
This PR changes the sortition hash from $H(round||counter||step||seed)$ to $H(seed||round||step||counter)$, 
to be compliant with Deterministic Sortition specification.
The following tests are also updated: `test_sortition_hash`, `test_generate_sortition_score`, `test_collect_votes`, `test_deterministic_sortition_1`, `test_deterministic_sortition_2`.
Note that `test_collect_votes` code has been also overhauled to make it simpler and easier to update in the future.
| :exclamation:  IMPORTANT: This is a BREAKING CHANGE |
|-|

Make Sortition Hash compliant with specification

---

rusk-prover/Cargo.toml
rusk/Cargo.toml

Upgrade and tag new rusk-prover version required by https://github.com/dusk-network/dusk-prover

Rusk prover 0.2.0

---

rusk/src/bin/config/http.rs
rusk/src/lib/http.rs

This PR allows the HTTP listener to be activated using configuration file.
This fixes the wrong behaviour where the activation flag was read using only the CLI args

rusk: fix http listener activation

---

rusk-abi/Cargo.toml
rusk-recovery/src/state.rs
rusk/src/lib/lib.rs

Upgrading was a simple process. Just bump the version and remove squashing. That and the hours spent debugging together with @herr-seppia and @miloszm to figure out the last things in `piecrust`.
Big thanks to them.

Upgrade to `piecrust@0.9`

---

contract-helpers/src/collection.rs
contracts/license/CHANGELOG.md
contracts/license/Cargo.toml
contracts/license/src/lib.rs
contracts/license/src/state.rs
contracts/license/tests/license.rs

The following changes have been made to the license contract:
- Changed 'use_license' to check if license already nullified
- Changed 'get_licenses' to return values by adding 'pos' to every license returned
- Changed 'issue_license' by removing the 'pos' argument and self position determination
- Added method 'get_info'
- Converted get_licenses to use feeder
This PR implements the following issues: #1051, #1040, #1039, #1052, #1054

License contract changes

---

.env
README.md
circuits/storage/src/lib.rs
contracts/license/Cargo.toml
contracts/license/build.rs
contracts/license/src/lib.rs
contracts/transfer/Cargo.toml
contracts/transfer/build.rs
contracts/transfer/src/circuits.rs
rusk-profile/src/lib.rs
rusk-recovery/src/bin/keys.rs
rusk-recovery/src/bin/state.rs
rusk-recovery/src/bin/task.rs
rusk/build.rs

Additionally, fix the profile folders resolution to be the following
RUSK_PROFILE_PATH | result
-- | -- 
None | $HOME/.dusk/rusk
Set | $RUSK_PROFILE_PATH
RUSK_PROFILE_PATH | RUSK_KEYS_PATH | result
-- | -- | --
None | None | $HOME/.dusk/rusk/keys
Set | None | $RUSK_PROFILE_PATH/keys
_ | Set | $RUSK_KEYS_PATH
RUSK_PROFILE_PATH | RUSK_CIRCUITS_PATH | result
-- | -- | --
None | None | $HOME/.dusk/rusk/circuits
Set | None | $RUSK_PROFILE_PATH/circuits
_ | Set | $RUSK_CIRCUITS_PATH
RUSK_PROFILE_PATH | RUSK_STATE_PATH | result
-- | -- | --
None | None | $HOME/.dusk/rusk/state
Set | None | $RUSK_PROFILE_PATH/state
_ | Set | $RUSK_STATE_PATH
Resolves #1057

Make RUSK_PROFILE_PATH optional

---

rusk-recovery/src/bin/keys.rs
rusk-recovery/src/bin/state.rs
rusk-recovery/src/bin/task.rs
rusk/src/bin/config.rs

With #1057 the rusk-recovery `--profile` argument was removed.
This PR partially revert the removal, but still keeps the argument optional.
In the same way, a new `--profile` arg has been added to `rusk` too

Add `--profile` cli argument

---

Makefile
rusk/Makefile

Fix `all` recipe

---

contracts/license/Makefile
contracts/stake/Makefile
contracts/transfer/Makefile
rusk-abi/Cargo.toml

license-contract: remove `panic` compilation flags
stake-contract: remove `panic` compilation flags
transfer-contract: remove `panic` compilation flags
rusk-abi: upgrade piecrust stack
- Upgrade `piecrust-uplink` to 0.8.0-rc
- Upgrade `piecrust` to 0.10.1-rc
Resolves dusk-network/wallet-cli#207

Contract panic

---

node/Cargo.toml
node/src/databroker.rs
node/src/databroker/conf.rs
rusk-recovery/Cargo.toml
rusk-recovery/src/bin/keys.rs
rusk-recovery/src/bin/state.rs
rusk/Cargo.toml
rusk/src/bin/args.rs
rusk/src/bin/config.rs
rusk/src/bin/config/chain.rs
rusk/src/bin/config/databroker.rs
rusk/src/bin/config/http.rs
rusk/src/bin/config/kadcast.rs
rusk/src/bin/ephemeral.rs
rusk/src/bin/main.rs
rusk/src/bin/version.rs

- remove `clap` dependencies
- update `clap` to 4.x
- update `clap` to 4.x
- use `clap` derive for CLI args
Resolves #778

Migrate to `clap` 4.x

---

rusk-abi/Cargo.toml
rusk/src/bin/config/http.rs

Force `piecrust-uplink` to be on RC #1088
Fix default HTTP_Listener #1087

Fix node compilation

---

contracts/license/Cargo.toml
contracts/license/tests/license.rs

License contract test upgrade to zk_citadel 0.5.0,
Fixes issue with setting public parameters in test.
Implements #1082

License contract test upgrade to zk_citadel 0.5.0

---

node/src/network.rs
rusk/src/lib/chain.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/http/event.rs
rusk/src/lib/http/rusk.rs

Add `info` endpoint
Request: 
```sh
curl --location --request POST 'http://127.0.0.1:8080/02/Chain' \
--header 'Rusk-Version: 0.7.0-rc' \
--header 'Content-Type: application/json' \
--data-raw '{
"topic": "info",
"data": ""
}'
```
Response
```json
{
"bootstrapping_nodes": [],
"chain_id": null,
"kadcast_address": "127.0.0.1:9000",
"version": "0.7.0-rc.0",
"version_build": "0.7.0-rc.0 (be85c229 2023-10-25)"
}
```

Add HTTP Info

---

rusk-recovery/src/bin/keys.rs
rusk-recovery/src/bin/state.rs
rusk-recovery/src/keys.rs
rusk-recovery/src/state.rs
rusk/Cargo.toml
rusk/src/bin/args.rs
rusk/src/bin/args/command.rs
rusk/src/bin/args/state.rs
rusk/src/bin/main.rs

~When `recovery` feature is enable~ According to the enabled features, the following subcommand are available
- `recovery-state`: equivalent to `rusk-recovery-state` binary
- `recovery-keys`: equivalent to `rusk-recovery-keys` binary
Resolves #1126

Embed rusk-recovery binary

---

rusk-profile/src/lib.rs
rusk/src/lib/http.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/http/event.rs
rusk/src/lib/http/rusk.rs

Below the example with the new header
```sh 
curl --location --request POST 'http://127.0.0.1:8080/02/rusk' \
--header 'Accept: application/octet-stream' \
--data-raw '{"topic": "crs","data": ""}' \
-v --output setup.crs
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /02/rusk HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.87.0
> Accept: application/octet-stream
> Content-Length: 27
> Content-Type: application/x-www-form-urlencoded
> 
} [27 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< rusk-version: 0.7.0-rc.0
< crs-hash: …
```

rusk: add hash header to the CRS-via-HTTP api

---

node-data/src/bls.rs
node/src/chain/acceptor.rs

node: add `missing_iterations` logs

---

consensus/src/agreement/verifiers.rs
consensus/src/user/cluster.rs
consensus/src/user/committee.rs
consensus/src/user/provisioners.rs
node/Cargo.toml
node/benches/accept.rs
node/src/chain.rs
node/src/chain/acceptor.rs
node/testbed.sh

node: Add `verify_block_cert` bench.
Create a `Certificate` with all voters signatures aggregated.
Even if this is probably not applicable in our context due to the fact that we short-circuit the certificate creation at 67% of quorum, it's still a valid starting point for benchmark
`cargo bench verify_block_cert -p node`
```
verify_block_cert/verify_block_cert/1 prov
time:   [6.8250 ms 6.8550 ms 6.8912 ms]
verify_block_cert/verify_block_cert/30 prov
time:   [52.643 ms 52.846 ms 53.063 ms]
verify_block_cert/verify_block_cert/64 prov
time:   [78.349 ms 78.666 ms 79.005 ms]
verify_block_cert/verify_block_cert/256 prov
time:   [111.34 ms 111.53 ms 111.75 ms]
verify_block_cert/verify_block_cert/1000 prov
time:   [118.67 ms 119.00 ms 119.39 ms]
```
See also #1149

Add benchmark for certificate verification

---

contracts/stake/src/lib.rs
contracts/stake/tests/stake.rs
contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/transfer.rs
rusk/src/lib/lib.rs
rusk/tests/services/gas_behavior.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/unspendable.rs

We substitute the `spend` function in the transfer contract for a `spend_and_execute` function, that also executes the contract call.
This fixes a bug where it was impossible to inform a genesis contract about whether they're being called in "management mode" by the VM - leading to sensitive functions being reachable by any contract call.
It also removes the fixed fee per transfer, since it was extremely artificial, and the regular transfer fee, while variable, is not much higher regardless.

Remove fixed fee

---

Makefile
contracts/alice/Makefile
contracts/bob/Makefile
contracts/governance/Makefile
contracts/license/Makefile
contracts/stake/Makefile
contracts/stake/tests/stake.rs
contracts/transfer/Makefile
contracts/transfer/tests/transfer.rs
rusk-abi/tests/contracts/host_fn/Makefile
rusk-recovery/src/state.rs
scripts/setup-compiler.sh

We introduce `duskc` to compile the genesis contracts, and all other contracts present in the repository. Following this, we compile *only the transfer contract* to `wasm64-unknown-unknown`.
The transfer contract, so far as I can see, is the only genesis contract with an ever growing state that requires a such a large tree. One possible exception may be the license contract, since it uses such a tree as well. I'll leave it up to @xevisalle or @miloszm to decide whether this is necessary or not.

Compile transfer contract to `wasm64-unknown-unknown`

---

rusk/CHANGELOG.md
rusk/Cargo.toml

- Add gas price API: max, min and mean gas prices
- Add rolling finality
- Add AST benchmarks
- Add common module to benchmark
- Add criterion dependency for benchmarks
- Add `prover` feature flag as default
- Add hash header to the CRS-via-HTTP api
- Add support for HTTP response headers
- Add test for unspendable transaction
- Add HTTP `crs` topic
- Add HTTP support for explicit binary response
- Add `rusk-recovery` subcommands
- Add `info` HTTP endpoint
- Add HTTP support for `application/json` content type
- Add HTTP version handshake
- Add `network_id` config
- Add `build` recipe to Makefile
- Add `--profile` arg
- Add GQL mempool API
- Add `alive_nodes` api
- Add `provisioners` api
- Add GQL block state hash field
- Add blocks by range graphql handler
- Add transactions by block …

Release 0.7.0

---

contracts/Makefile
contracts/stake-types/Makefile
contracts/transfer-types/Cargo.toml
contracts/transfer-types/Makefile

This PR add the *-contract-types crates to the Makefile flow

Add contract-types to CI

---

consensus/src/commons.rs
consensus/src/config.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/iteration_ctx.rs
consensus/src/lib.rs
consensus/src/msg_handler.rs
consensus/src/phase.rs
consensus/src/proposal/handler.rs
consensus/src/proposal/step.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/validation/handler.rs
consensus/src/validation/step.rs
node/src/chain/consensus.rs
node/testbed.sh

fixes #1170 
The provided logics for listed points below will be revised later on accordingly. Currently, the PR only includes a basic implementation.
-  adjust_round_base_timeout
- increasing step_base_timeout
- Default values for step_base_timeout, round_base_timeout and max_step_timeout

Implement adaptive consensus timeout

---

.github/workflows/dusk_ci.yml

Change CI to:
- Run on `ready_for_review`[^1] too 
- Run on manual `workflow_dispatch`
- Run `tests` step only if `manual` or `ready_for_review`
[^1]: By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened _[(src)](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)_

CI: disable tests for draft PRs

---

consensus/src/config.rs
consensus/src/execution_ctx.rs
consensus/src/ratification/step.rs
consensus/src/validation/handler.rs
consensus/src/validation/step.rs

consensus: Handle messages in emergency mode 

---

consensus/src/commons.rs
consensus/src/proposal/step.rs
consensus/src/ratification/handler.rs
consensus/src/step_votes_reg.rs
node-data/src/message.rs

Fix missing collection of failed cert when a valid vote is received firstly
See also #1255

consensus: fix_step_votes_registry

---

node/src/chain/acceptor.rs
node/src/chain/fallback.rs
node/src/chain/fsm.rs

fixes #1168 
As already mentioned, this PR implements issue 1168 by reverting to LastFinalized state. 
In order to, implement the part "then we fallback to $B_H.PrevBlock$ and accept $B'_H$ to our chain ", another DIP issue should be filed where we can refine the concept.
See also:  #1260

node: Allow fallback to lower-round blocks

---

node/src/chain/acceptor.rs
node/src/chain/fsm.rs
node/src/vm.rs
node/testbed.sh
rusk/benches/block_ingestion.rs
rusk/src/lib/error.rs
rusk/src/lib/lib.rs
rusk/src/lib/vm.rs
rusk/tests/rusk-state.rs
rusk/tests/services/transfer.rs

consensus: Revert to last common ancestor

---

consensus/Cargo.toml
consensus/src/commons.rs
consensus/src/quorum/verifiers.rs
node-data/src/ledger.rs
node/Cargo.toml
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/mempool.rs

When a transaction is submitted to the mempool, it is discarded if there is already a transaction in the mempool that uses at least one of the sent nullifiers. 
This means that if a user submits a transaction with a GasLimit that is too low (preventing its execution) or if their transaction is pending due to network congestion, the user cannot submit new transactions.
With this PR, however, if the gasPrice of the submitted transaction is higher than the gasPrice of the transaction in the mempool, the latter is removed in favor of the new one.
In essence, this PR implements a kind of "boost" for one's transactions.
Resolves #914 
Resolves #935

rusk: Add mempool transaction replacement

---

.github/workflows/rusk_ci.yml
.github/workflows/webwallet_ci.yml

As stated by the github docs, if a workflow is skipped due to path filtering, branch filtering or a commit message, then checks associated with that workflow will remain in a "Pending" state.
A pull request that requires those checks to be successful will be blocked from merging.
The solution is skipping those workflow without using the `paths` mechanism, but instead having a job that verifies if something changed in the interested paths and set a variable, to use on other jobs.

Update workflows to be skipped properly

---

README.md

Update node requirements based on the [DO bench runs](https://github.com/dusk-network/rusk/pull/421#issuecomment-1928580875) and memory consumption when proving transactions with up to 4 notes.
The minimum specs should be comfortable for consensus nodes.

Update node requirements

---

consensus/src/aggregator.rs
consensus/src/commons.rs
consensus/src/config.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/msg_handler.rs
consensus/src/phase.rs
consensus/src/proposal/handler.rs
consensus/src/proposal/step.rs
consensus/src/quorum/verifiers.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/step_votes_reg.rs
consensus/src/user/committee.rs
consensus/src/user/sortition.rs
consensus/src/validation/handler.rs
consensus/src/validation/step.rs
node-data/src/encoding.rs
node-data/src/ledger.rs
node-data/src/message.rs
node/benches/accept.rs
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/database/rocksdb.rs
node/testbed.sh

Additionally:
- Change quorum terminology to reflect new names defined in #1268
- Refactor codebase to get rid of unused function arguments
- Refactor codebase to be more idiomatic 
- Fix validation::collect_from_past from returning a final_result even if the quorum is not reached
- Adapt node benches to previous PRs changes
Resolves #1183

consensus: ignore candidate with wrong prev_block_hash

---

node-data/src/message.rs
node/src/chain/fsm.rs
node/src/databroker.rs

`GetData` message has as a payload a list of Inv items. It should always bring `GetData` payload type in order to activate `DataBroker::handle_get_data` handler.

node: Use GetData payload

---

consensus/src/aggregator.rs
consensus/src/commons.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/quorum/task.rs
consensus/src/quorum/verifiers.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/step_votes_reg.rs
consensus/src/validation/handler.rs
consensus/src/validation/step.rs
node-data/src/encoding.rs
node-data/src/ledger.rs
node-data/src/message.rs
node/src/chain/header_validation.rs

consensus: change Quorum to use Certificates with RatificationResult

---

consensus/CHANGELOG.md
consensus/src/config.rs

- Increase `CONSENSUS_ROLLING_FINALITY_THRESHOLD` from 5 to 20.
- Increase `MIN_STEP_TIMEOUT` from 2s to 5s.

Consensus: Increase RFT & MST

---

consensus/src/user/provisioners.rs
node/Cargo.toml
node/src/chain/acceptor.rs
node/src/vm.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/chain/vm.rs

Change the node to call get_provisioners in 3 cases:
1. Startup
2. Rollback
3. Something wrong while inspecting transactions
For any other case described in the issue, a precise `get_provisioner` is performed
See also #1442

Selective provisioners update

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/components/Send/Send.svelte
web-wallet/src/lib/components/__tests__/Send.spec.js
web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
web-wallet/src/lib/dusk/components/Textbox/Textbox.svelte
web-wallet/src/lib/dusk/string/__tests__/validateAddress.spec.js
web-wallet/src/lib/dusk/string/index.js
web-wallet/src/lib/dusk/string/validateAddress.js

Resolves #1377
**Visuals:**
I have followed the same approach as what we have with the Gas Settings component – where the input is red, when invalid, and the reason why the validation has failed is not displayed. To be candid, I am not a huge fan of this approach, as it's not user-friendly. However, we would need to think about how to properly give feedback to the user and apply the same pattern app-wide.

web-wallet: Add Address validation (Transfer flow)

---

web-wallet/CHANGELOG.md
web-wallet/src/routes/(welcome)/setup/create/+page.svelte
web-wallet/src/routes/(welcome)/setup/create/MnemonicValidate.svelte
web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/(welcome)/setup/create/__tests__/page.spec.js
web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js

web-wallet: Add Create Wallet flow tests

---

node/src/chain.rs
node/src/chain/acceptor.rs
node/src/databroker.rs
node/src/lib.rs
node/src/mempool.rs
rusk/src/bin/main.rs

Any services registered may introduce an implementation of `Initialize` in which method any major components/structs/resources can be fully instantiated. On implementing `Initialize`, ChainSrv instantiates `Acceptor` struct by which it can revert to last final state before spawning `DataBroker` service.

Support lazy-initialization for all services

---

rusk/CHANGELOG.md
rusk/Cargo.toml
rusk/src/lib/chain.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/chain/vm/query.rs
rusk/src/lib/test_utils.rs
rusk/tests/rusk-state.rs

State transitions can now be performed in parallel with queries. This solves the issue of the consensus being blocked while the state is queried.
This is achieved by disentangling the `VM` from the current and base commits in the `Rusk` data structure, as well as using a `RWLock` instead of a `Mutex`, allowing for write-locking only at the end of a state transition. This, together with a read-lock and release for when the tip is used, effectively means that queries are never in contention with state transitions when they don't need to be.
We also ensure that, on a `finalize`, commits are deleted on a separate task, such that we don't block execution of the state transition itself, allowing the node to return from a `finalize` before the deletions are processed.
Resolves: #970
See-also: …

Allow queries in parallel with state transitions

---

contracts/stake/CHANGELOG.md
contracts/stake/Cargo.toml
contracts/stake/benches/get_provisioners.rs
contracts/stake/src/state.rs
node-data/src/ledger.rs

get_provisioners optimisation of the stake contract,
implements #1447

stake-contract: optimized get_provisioners

---

contracts/stake/src/lib.rs
contracts/stake/src/state.rs
rusk/src/lib/chain/rusk.rs
rusk/tests/services/stake.rs

Save previous state of provisioners that changed in last block.
See also https://github.com/dusk-network/rusk/pull/1513#discussion_r1516380001
See also #1516

stake-contract: track provisioners change

---

contracts/stake/src/state.rs
rusk/tests/services/stake.rs

- Remove tracking when no hard_slash is performed
- Fix hard_slash panic when unstake is performed in the same block
- Fix slash panic when unstake is performed in the same block
- Change shift eligibility to add a maturity epoch
- Change events order to reflect the doc

stake-contract: fix slash

---

rusk/src/lib/chain/rusk.rs

With the new stake contracts, event are emitted when rewarding or slash.
This PR change the hasher to include those too.
ps: This PR should be safely merged into ITN branch because, even if this can potentially include new events (and disrupt block verification), no events are emitted with the old stake contract
See also https://github.com/dusk-network/rusk/issues/1442#issuecomment-1991115433

rusk: track vm events for reward/slash

---

consensus/src/user/provisioners.rs
node-data/src/ledger.rs
node/src/chain/acceptor.rs
rusk/src/lib/chain/vm.rs

Right now changes in reward are not tracked, since they are not impacting the sortition.
However the rewards needs to be tracked in order to properly migrate rewards during stake contract migration.

ITN migration: track rewards

---

web-wallet/CHANGELOG.md
web-wallet/package-lock.json
web-wallet/package.json

- Add message when no contracts have been enabled [#1317]
- Add `eslint-config-prettier` as explicit dependency [#1509]
- Add format check to CI and `checks` script [#1504]
- Add `vitest-canvas-mock` dependency to replace `canvas` [#1506]
- Add `AppImage` component [#1284]
- Add possibility to serve the web wallet from a sub folder [#1362]
- Update to SvelteKit 2, Vite 5 and Vitest 1 [#1284]
- Update all dependencies [#1284]
- Refactor `mockReadableStore` to be not be writable [#1285]
- Refactor beta notice as constant [#1469]
- Refactor `settingsStore` and create readable `gasStore` to store `limitLower`, `limitUpper`, `priceLower` [#1308]
- Refactor add Prettier for formatting and format all files [#1458]
- Remove box-shadow from components [#1519]
- Remove orphan dependency …

web-wallet: Release 0.4.0

---

rusk-recovery/config/testnet.toml
rusk-recovery/src/state.rs

Data retrieved with
```sh
curl -s -L 'https://nodes.dusk.network/02/rusk' \
--data-raw '{"topic": "provisioners","data": ""}' \ |
jq -r '.[] | select(.amount+.eligibility != 500000000000000) | . + {itn_val: (.amount + .reward)} | select (.itn_val > 5000000000000) | "[[stake]]\naddress = '\''\(.key)'\''\namount = 0\nreward= \(.itn_val | tostring )\n"'
```
1. Get the current provisioner list
2. Filter out our 30 genesis provisioners with `select(.amount+.eligibility != 500000000000000)`
3. Calculating a new field with the sum of staked amount and the accrued reward `{itn_val: (.amount + .reward)}`
4. Filter out member with less of 5k dusk accrued `select (.itn_val > 5000000000000)`
5., Change representation to the one expected by genesis.toml `| "[[stake]]\naddress = '\''\(.key)'\''\namount …

rusk-recovery: add snapshot of ITN2 to testnet.toml

---

rusk-abi/CHANGELOG.md
rusk-abi/Cargo.toml
rusk-abi/src/host.rs
rusk-abi/src/types.rs
rusk/benches/block_ingestion.rs

We memoize the `verify_proof` host function, allowing proof verification to happen only once per equivalent proof being verified in the context of transaction execution.
This is achieved by using a static LruCache, with a configurable maximum limit of entries. These entries are key-value pairs, from the hash of the parameters used to call the proof verification to the outcome of said verification, which allows us to skip verification if we've already performed it once.
Resolves #1228

Memoize `verify_proof` host function

---

web-wallet/CHANGELOG.md
web-wallet/src/style/dusk-components/button.css
web-wallet/src/style/dusk-components/select.css
web-wallet/src/style/dusk-components/textbox.css

- Fix `font-family` and `letter-spacing` on `Button`, `AnchorButton`, `Textbox` and `Select`
Resolves #1565

web-wallet: Different letter spacing on Button and AnchorButton

---

node/Cargo.toml
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/chain/fsm.rs
node/src/chain/header_validation.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/lib.rs
node/src/network.rs
node/src/telemetry.rs
node/testbed.sh
rusk/Cargo.toml
rusk/src/bin/args.rs
rusk/src/bin/config.rs
rusk/src/bin/config/telemetry.rs
rusk/src/bin/main.rs

fixes #1610 
All of the `localnet` nodes exposes metrics data at `localhost` ports 9000..9029
Example output: 
```
dusk_outbound_Candidate_size 18602
dusk_inbound_Candidate_size 21008
dusk_bytes_recv 386842
dusk_txn_count 0
dusk_outbound_Quorum_size 6800
dusk_inbound_GetCandidate_size 371
dusk_bytes_cast 270195
dusk_outbound_Ratification_size 139970
dusk_bytes_sent 7757
dusk_inbound_Quorum_size 27184
dusk_outbound_Validation_size 104823
dusk_inbound_GetBlocks_size 1113
dusk_inbound_Validation_size 138170
dusk_inbound_Ratification_size 198996
dusk_block_Final 22
dusk_block_Attested 3
dusk_block_Accepted 3
dusk_provisioners_eligible 29
dusk_provisioners_all 363
dusk_stored_candidates_count 10
dusk_block_iter{quantile="0"} 0
dusk_slashed_count{quantile="1"} 0 …
```

Implement a basic telemetry service 

---

contracts/license/tests/license.rs
contracts/stake/benches/get_provisioners.rs
contracts/stake/tests/common/utils.rs
contracts/transfer/tests/transfer.rs
rusk-abi/Cargo.toml
rusk/src/bin/config/http.rs
rusk/src/bin/main.rs
rusk/src/lib/chain.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/chain/vm/query.rs
rusk/tests/common/state.rs

We also add a configuration option to be able to stipulate the maximum gas used by feeder calls. The default value is set as `u64::MAX`, but this should probably be discussed.

Upgrade `piecrust` to version `0.18`

---

web-wallet/src/routes/components-showcase/Toasts.svelte

web-wallet: Fix build warning for unused icon

---

web-wallet/src/routes/components-showcase/Buttons.svelte
web-wallet/src/style/dusk-components/button.css
web-wallet/src/style/dusk-components/checkbox.css
web-wallet/src/style/main.css

- Added specific transform for checkbox background-color
- Fixed scaling for icon buttons in active state
- Removed unused transform that was overriding the easing function in buttons
- Updated the scaling up of icon buttons on hover to 1.1
Resolves #1637

web-wallet: Icon scaling issue when used in Button

---

explorer/src/lib/components/__tests__/Navbar.spec.js
explorer/src/lib/components/navbar/Navbar.svelte

explorer: Failed query notices don't disappear

---

explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/block-details/BlockDetails.svelte
explorer/src/lib/components/data-card/DataCard.css

explorer: remove block height from Block Details card header

---

rusk/Cargo.toml
rusk/src/lib/chain.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/http.rs
rusk/src/lib/http/event.rs
rusk/src/lib/http/stream.rs

Allows for the client to dispatch events, and receive "response" events on the connected websocket according to the [RUES specification](https://github.com/dusk-network/rusk/wiki/RUES-(Rusk-Universal-Event-System)). This effectively means the RUES API is, with this PR, just as powerful as the previous API.

Add RUES dispatch

---

explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
explorer/src/lib/components/block-details/BlockDetails.svelte
explorer/src/lib/components/data-card/DataCard.svelte
explorer/src/lib/components/latest-transactions-card/LatestTransactionsCard.svelte
explorer/src/lib/components/transaction-details/TransactionDetails.svelte
explorer/src/routes/blocks/block/+page.svelte

explorer: Fix CTAs on the details page

---

explorer/src/app.html
explorer/src/lib/components/blocks-card/BlocksCard.css
explorer/src/lib/components/navbar/Navbar.svelte
explorer/src/lib/components/transactions-card/TransactionsCard.css
explorer/src/routes/+layout.svelte
explorer/src/routes/blocks/+page.svelte
explorer/src/routes/transactions/+page.svelte

explorer: fix double scrollbar issue

---

explorer/src/lib/components/table/Table.svelte
explorer/src/lib/containers/statistics-panel/StatisticsPanel.svelte
explorer/src/lib/dusk/svelte-stores/__tests__/createDataStore.spec.js
explorer/src/lib/dusk/svelte-stores/__tests__/createPollingDataStore.spec.js
explorer/src/lib/dusk/svelte-stores/createDataStore.js
explorer/src/lib/dusk/svelte-stores/createPollingDataStore.js
explorer/src/lib/dusk/svelte-stores/svelte-stores.d.ts

explorer: Add a `reset` method to data stores

---

explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/__tests__/page.spec.js
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/block/__tests__/page.spec.js
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/page.spec.js
explorer/src/routes/transactions/transaction/+page.svelte
explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/transaction/__tests__/page.spec.js

explorer: add tests for `+page.svelte` routes

---

explorer/src/lib/components/__tests__/AppAnchorButton.spec.js
explorer/src/lib/components/__tests__/__snapshots__/AppAnchorButton.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
explorer/src/lib/components/app-anchor-button/AppAnchorButton.svelte
explorer/src/lib/components/block-details/BlockDetails.svelte
explorer/src/lib/components/index.js
explorer/src/lib/dusk/components/__tests__/AnchorButton.spec.js
explorer/src/lib/dusk/components/__tests__/__snapshots__/AnchorButton.spec.js.snap
explorer/src/lib/dusk/components/anchor-button/AnchorButton.css
explorer/src/lib/dusk/components/anchor-button/AnchorButton.svelte
explorer/src/lib/dusk/components/index.js
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap

explorer: disable block height navigation

---

explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
explorer/src/lib/components/blocks-list/BlocksList.svelte
explorer/src/lib/components/transactions-list/TransactionsList.svelte

explorer: Consistent Display of Relative Time on Desktop and Mobile

---

explorer/src/lib/components/__tests__/BlockDetails.spec.js
explorer/src/lib/components/block-details/BlockDetails.svelte

explorer: Disable "previous" button in blocks when the height is `0`

---

explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksTable.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
explorer/src/lib/components/blocks-list/BlocksList.svelte
explorer/src/lib/components/blocks-table/BlocksTable.svelte
explorer/src/lib/components/transaction-details/TransactionDetails.svelte
explorer/src/lib/components/transactions-list/TransactionsList.svelte
explorer/src/lib/components/transactions-table/TransactionsTable.css
explorer/src/lib/components/transactions-table/TransactionsTable.svelte
explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
explorer/src/style/main.css

Resolves #1789 
Resolves #1793 
Resolves #1794
Resolves #1795

explorer: fix badge width tx fees format optimizing headers

---

consensus/Cargo.toml
execution-core/Cargo.toml

Previous bench
```
verify_block_cert/verify_block_cert/1 prov
time:   [6.8250 ms 6.8550 ms 6.8912 ms]
verify_block_cert/verify_block_cert/30 prov
time:   [52.643 ms 52.846 ms 53.063 ms]
verify_block_cert/verify_block_cert/64 prov
time:   [78.349 ms 78.666 ms 79.005 ms]
verify_block_cert/verify_block_cert/256 prov
time:   [111.34 ms 111.53 ms 111.75 ms]
verify_block_cert/verify_block_cert/1000 prov
time:   [118.67 ms 119.00 ms 119.39 ms]
```
PR bench
_Benchmarked on Apple M1 Pro_
See also #1149

consensus: change `bls12_381-bls` to use parallel feature

---

node/src/chain/header_validation.rs

Ensure the function returns true if all failed iterations (according to the candidate block iteration) have a quorum. 
Fixed a bug where the function incorrectly returned true if no failed attestations were added to the list and the candidate iteration was non-zero.
Resolves #1871

node: fix `verify_failed_iterations`

---

explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/blocks-card/BlocksCard.svelte
explorer/src/lib/components/transactions-card/TransactionsCard.svelte
explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap

explorer: add number of displayed entries on table header

---

contracts/stake/src/lib.rs
contracts/stake/src/state.rs
contracts/stake/tests/common/utils.rs
contracts/stake/tests/events.rs
execution-core/src/stake.rs
rusk-recovery/src/state.rs
rusk/src/lib/chain/rusk.rs
rusk/tests/services/stake.rs

consensus: change soft-slash mechanism

---

contracts/stake/tests/common/utils.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/common.rs
contracts/transfer/tests/transfer.rs
execution-core/src/transfer.rs
execution-core/src/transfer/transaction.rs
execution-core/tests/serialization.rs
node-data/src/ledger/transaction.rs
node/src/database/rocksdb.rs
node/src/mempool.rs
rusk-prover/src/tx.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/chain/vm.rs
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/data.rs
rusk/src/lib/verifier.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/transfer.rs
test-wallet/src/imp.rs

While working on moonlight, I had the urge to cleanup `execution-core` while working on it and thought it a good idea to make a separate PR.
Some functions are removed/changed, and some fields made public where they were otherwise private. In particular:
Changed:
- Transaction::new now takes a proof as impl Into<Vec<u8>>
- Transaction::proof now returns &[u8]
- Made Fee::stealth_address public
- Made Fee::sender public
Removed:
- Transaction::payload_hash
- Fee::sender
- Fee::stealth_address
- Payload::new
- Payload::tx_skeleton
- Payload::fee
- Payload::contract_call

Small `execution-core` cleanup

---

explorer/src/lib/stores/__tests__/marketDataStore.spec.js
explorer/src/lib/stores/marketDataStore.js
explorer/src/lib/stores/stores.d.ts

explorer: Add service method to check for stale market data

---

explorer/src/lib/stores/__tests__/marketDataStore.spec.js
explorer/src/lib/stores/marketDataStore.js

explorer: Avoid restart market data polling in case of 429 error

---

explorer/src/lib/stores/__tests__/appStore.spec.js
explorer/src/lib/stores/appStore.js

explorer: Give defaults to data fetch intervals

---

web-wallet/src/lib/components/ExistingWalletNotice/ExistingWalletNotice.svelte
web-wallet/src/lib/components/Stake/Stake.svelte
web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
web-wallet/src/lib/containers/Cards/Card.css
web-wallet/src/lib/containers/Cards/IconHeadingCard.svelte
web-wallet/src/lib/containers/Cards/ToggleableCard.svelte
web-wallet/src/lib/containers/Cards/index.js
web-wallet/src/lib/containers/__tests__/IconHeadingCard.spec.js
web-wallet/src/lib/containers/__tests__/ToggleableCard.spec.js
web-wallet/src/lib/containers/__tests__/__snapshots__/IconHeadingCard.spec.js.snap
web-wallet/src/lib/containers/__tests__/__snapshots__/ToggleableCard.spec.js.snap
web-wallet/src/lib/dusk/components/Card/Card.svelte
web-wallet/src/lib/dusk/components/__tests__/Card.spec.js
web-wallet/src/lib/dusk/components/__tests__/__snapshots__/Card.spec.js.snap
web-wallet/src/lib/dusk/components/dusk.components.d.ts
web-wallet/src/routes/(welcome)/forced-logout/+page.svelte
web-wallet/src/routes/(welcome)/forced-logout/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/(welcome)/login/+page.svelte
web-wallet/src/routes/(welcome)/login/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/(welcome)/setup/AllSet.svelte
web-wallet/src/routes/(welcome)/setup/PasswordSetup.svelte
web-wallet/src/routes/(welcome)/setup/TermsOfService.svelte
web-wallet/src/routes/(welcome)/setup/create/MnemonicPhrase.svelte
web-wallet/src/routes/(welcome)/setup/create/MnemonicPreSetup.svelte
web-wallet/src/routes/(welcome)/setup/create/MnemonicValidate.svelte
web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/(welcome)/setup/restore/MnemonicAuthenticate.svelte
web-wallet/src/routes/(welcome)/setup/restore/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/components-showcase/Cards.svelte
web-wallet/src/style/dusk-components/card.css

Resolves #1650, Resolves #1295

web-wallet: Replace Card component

---

explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/blocks-card/BlocksCard.svelte
explorer/src/lib/components/data-card/DataCard.css
explorer/src/lib/components/transactions-card/TransactionsCard.svelte
explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap

explorer: Update DataCard's header

---

contracts/stake/src/lib.rs
contracts/stake/src/state.rs
contracts/stake/tests/events.rs
execution-core/src/stake.rs
rusk-recovery/src/state.rs

Partially Implements #1651 
The second part (enabling generators to include proofs of hard faults) is addressed by #1923

Implement new hard slashing

---

contracts/transfer/src/state.rs
contracts/transfer/src/tree.rs
execution-core/src/transfer.rs
rusk-recovery/src/state.rs

This PR addresses the collected requests for changes to the transfer-contract from #1822.
Most notably:
The deposit, if not picked up by a contract, will be refunded together with the gas-refund
The function `mint` doesn't return a boolean anymore and the comments are adjusted.
Only the stake-contract is allowed to call the `mint` function.

transfer-contract: Add deposit to remainder-note and remove bool return for mint

---

explorer/src/lib/stores/__tests__/marketDataStore.spec.js
explorer/src/lib/stores/marketDataStore.js

explorer: Delay fetching market data if the current data is not stale

---

rusk-abi/src/hash.rs
rusk-abi/src/lib.rs
rusk-abi/tests/lib.rs

rusk-abi: Generate the BlsScalar hash without truncation

---

consensus/src/operations.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/handler.rs
consensus/src/validation/step.rs
node-data/Cargo.toml
node-data/src/bls.rs
node-data/src/encoding.rs
node-data/src/ledger.rs
node-data/src/ledger/attestation.rs
node-data/src/ledger/faults.rs
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/chain/header_validation.rs
rusk/benches/block_ingestion.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/chain/vm.rs
rusk/tests/common/state.rs

This is a followup of #1923 
See also #1651

consensus: handle Faults proof (aka hard slash)

---

node/src/chain/header_validation.rs

Additionally, improve `verify_prev_block_cert` performance:
- Fetch the header instead of fetching the full block
- Use the header hash instead of the block height
Resolves #1905

node: Check Certificate is Success Attestation

---

consensus/src/commons.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs

consensus: Support open-consensus-mode in event_loop

---

node/src/chain.rs
rusk-prover/Cargo.toml
rusk/Cargo.toml

The `tokio::select!` macro seems to have broken its syntax, even if not reflected in the `tokio` version. This PR fixes our syntax to comply with `tokio`.
We also ensure only one version of `tokio` is included at a time, avoiding longer compilation times.

Fix "freed while in use"

---

rusk-abi/CHANGELOG.md
rusk-abi/Cargo.toml
rusk-abi/src/host.rs
rusk-abi/src/host/cache.rs

Cache definition placed in a different file, and abstracted away with a macro, allowing one to generate different cache types according to in-code parameters.
This macro is then leveraged to generate both Plonk proof and BLS signature caches, which are then subsequently used in our code.
To slightly improve the implementation of both, the hash used as a cache key is now computed using the argument buffer contents, as opposed to the deserialized parameters. This allows for a cleaner and more performant implementation.
See-also: #1984

Add BLS signature cache

---

Makefile
circuits/Makefile
circuits/license/Makefile
consensus/Makefile
contracts/Makefile
contracts/alice/Makefile
contracts/bob/Makefile
contracts/host_fn/Makefile
contracts/license/Makefile
contracts/stake/Makefile
contracts/transfer/Makefile
node-data/Makefile
node/Makefile
rusk-abi/Makefile
rusk-profile/Makefile
rusk-prover/Makefile
rusk-recovery/Makefile
rusk/Makefile

Resolves #2008
This makes it possible to call `make doc` in the root dir to run the doc command.
At some point, however, we should find out what the problem is with cargo not working in the base directory. It may be related to a dependency problem with having std & no_std at the same time.

Add doc cmd to Makefiles

---

execution-core/CHANGELOG.md
execution-core/src/transfer.rs
execution-core/src/transfer/transaction/moonlight.rs
execution-core/src/transfer/transaction/phoenix.rs
execution-core/tests/serialization.rs
rusk/CHANGELOG.md
rusk/Cargo.toml
rusk/src/lib/chain/rusk.rs
rusk/src/lib/gen_id.rs
rusk/src/lib/hash.rs
rusk/src/lib/lib.rs
rusk/tests/services/contract_deployment.rs

contract ID generation mechanism
extends current deployment transaction format to support contract nonce
implements issue #1884

Issue 1884 - contract ID generation mechanism

---

explorer/src/lib/dusk/components/tooltip/Tooltip.css

explorer: fix Tooltip overlap with Navbar

---

consensus/src/commons.rs
consensus/src/operations.rs
consensus/src/proposal/block_generator.rs
consensus/src/quorum/verifiers.rs
consensus/src/user/cluster.rs
consensus/src/validation/step.rs
node-data/src/ledger/header.rs
node/benches/accept.rs
node/src/chain.rs
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/chain/header_validation.rs
node/src/vm.rs
rusk/src/lib/chain/rusk.rs
rusk/src/lib/chain/vm.rs

Rename:
- `verify_block_att` to `verify_att`
- `VoterWithCredit` to `Voter`
Add:
- `to_consensus_header` method for `Header`
- `to_voters` method for `Cluster<PublicKey>`
- `get_step_voters`
- `get_step_committee`
- `merge_voters`
Remove: 
- `verify_quorum`
- `verify_success_att`
- `merge_committees`
Refactor:
- `get_voters` is modified to only return voters, without re-verifying the attestation
- `verify_att` is modified to get a `consensus_header` parameter
- `verify_att` is modified to checks the expected result
- `Voter` is modified to be `(PublicKey, usize)` to ease its handling
- `reward_slash_and_update_root` is updated as a consequence
Bugfixes:
- fix `verify_att` to correctly return the set of voters, instead of the whole committees

Refactor Attestation verification

---

contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/common.rs
contracts/transfer/tests/transfer.rs

We add the `convert` function to the contract, leveraging the deposit and withdrawal capabilities to atomically swap Dusk between the Phoenix and Moonlight models.
The function is meant to be called directly - meaning as the first and only call - and takes a `Withdraw` as an argument, such that the user can prove ownership of either the account or address being deposited to.
Resolves: #1994

Allow converting between Phoenix and Moonlight Dusk

---

contracts/stake/src/state.rs
contracts/transfer/src/state.rs
execution-core/src/stake.rs
execution-core/src/transfer/transaction/moonlight.rs

Incremental nonces are meant to increase by 1 on every operation performed. As opposed to "strictly increasing" where any nonce larger than the one present in the state is valid, with incremental nonces only the one present in the state +1 is valid.
We change the genesis contracts - both the transfer contract with Moonlight, and the stake contract with the `stake` operation -  to make use of incremental nonces. This avoids situations where clients could exhaust the bit space in a single transaction, either knowingly or inadvertently locking an account from ever being used again.
Resolves: #2007

Use incremental nonces

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/components/Stake/Stake.svelte
web-wallet/src/lib/components/__tests__/Stake.spec.js

web-wallet: Added gas settings validation (Unstake / Widthdraw Rewards flows)

---

explorer/CHANGELOG.md
explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/DataCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/block-details/BlockDetails.svelte
explorer/src/lib/components/blocks-list/BlocksList.svelte
explorer/src/lib/components/data-card/DataCard.svelte
explorer/src/lib/dusk/components/__tests__/ProgressBar.spec.js
explorer/src/lib/dusk/components/__tests__/__snapshots__/ProgressBar.spec.js.snap
explorer/src/lib/dusk/components/progress-bar/ProgressBar.svelte
explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap

explorer: Add accessible name to Gas Used (Progressbar component)

---

contracts/alice/src/lib.rs
contracts/host_fn/src/lib.rs
contracts/license/src/lib.rs
contracts/stake/src/lib.rs
contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs
rusk-abi/Cargo.toml

We update the version of `piecrust` to `0.23` and of `piecrust-uplink` to `0.16`. This allows us to leverage the clearer `caller` API.
We also take the liberty to clean up the errant `SELF_ID` export from the contracts' code since it is no longer required.

Update to `piecrust@0.23`

---

node/src/chain.rs
node/src/databroker.rs
node/src/lib.rs
node/src/mempool.rs
node/src/telemetry.rs

This is a refactor PR triggered while #2049 
- Remove (unused) TxFilter
- Add default empty `initialize` implementation for `LongLivedService`

node: refactor `LongLivedService` trait

---

web-wallet/src/lib/dusk/components/ExclusiveChoice/ExclusiveChoice.css
web-wallet/src/lib/dusk/components/ExclusiveChoice/ExclusiveChoice.svelte
web-wallet/src/lib/dusk/components/__tests__/ExclusiveChoice.spec.js
web-wallet/src/lib/dusk/components/__tests__/__snapshots__/ExclusiveChoice.spec.js.snap
web-wallet/src/lib/dusk/components/index.js
web-wallet/src/lib/dusk/string/__tests__/randomUUID.spec.js
web-wallet/src/lib/dusk/string/index.js
web-wallet/src/lib/dusk/string/randomUUID.js
web-wallet/src/routes/components-showcase/+page.svelte
web-wallet/src/routes/components-showcase/ExclusiveChoices.svelte
web-wallet/src/style/dusk-components/exclusive-choice.css
web-wallet/src/style/main.css
web-wallet/vite.config.js

web-wallet: Add `ExclusiveChoice` component

---

Cargo.toml
Makefile
wallet-core/Cargo.toml
wallet-core/Makefile
wallet-core/src/keys.rs
wallet-core/src/lib.rs
wallet-core/tests/keys_derive.rs

This adds wallet-core as a workspace-member for rusk.
The PR only focuses on the basic setup and implements the keys generation.
Resolves #2116

wallet-core: Add workspace member with keys generation

---

web-wallet/src/lib/components/DashboardNav/DashboardNav.svelte
web-wallet/src/lib/components/__tests__/DashboardNav.spec.js
web-wallet/src/lib/components/__tests__/__snapshots__/DashboardNav.spec.js.snap
web-wallet/src/lib/components/components.d.ts
web-wallet/src/lib/components/index.js
web-wallet/src/routes/components-showcase/+page.svelte
web-wallet/src/routes/components-showcase/DashboardNavs.svelte

web-wallet: Add DashboardMenu component

---

wallet-core/Cargo.toml
wallet-core/src/lib.rs
wallet-core/tests/balance.rs
wallet-core/tests/keys.rs

wallet-core: Add function to sum the balance for phoenix notes

---

consensus/src/config.rs
consensus/src/user/committee.rs
rusk/src/lib/node/rusk.rs

Fix #2100
- Eliminate `MAJORITY_THRESHOLD` and `SUPERMAJORITY_THRESHOLD` constants
- Define `majority` and `supermajority` functions, which returns `floor(x/2)+1` and `ceil(x/2*3)` respectively
The new definitions eliminate the risk of wrong quorum values for some edge cases.

Re-define Majority and Supermajority

---

rusk/src/lib/http/chain/graphql/data.rs

Required to backward compatibility of the explorer
- rename `contract` back to `contractId`
- rename `fnArgs` back to `data`

rusk: GQL - revert changes in 5112f66

---

node/Cargo.toml
node/default.config.toml
node/src/chain/acceptor.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/mempool.rs
node/src/mempool/conf.rs

node: Periodically remove expired transactions from mempool

---

node-data/src/bls.rs
node-data/src/encoding.rs
node-data/src/ledger/attestation.rs
node-data/src/ledger/block.rs
node-data/src/message.rs

node-data: Fix some comments

---

web-wallet/src/lib/navigation/__tests__/logout.spec.js
web-wallet/src/lib/navigation/logout.js
web-wallet/src/lib/stores/__tests__/walletStore.spec.js
web-wallet/src/lib/stores/walletStore.js

- The store update after the sync now checks if the sync is aborted
- Streamlined wallet store tests
Resolves #2156

web-wallet: Resetting the wallet store should also abort the sync

---

.github/workflows/rusk_ci.yml
Makefile
rusk/Makefile

Resolves #1954 
This is both a good and a bad idea. The good part is that we can frequently check incremental improvements and regressions. I currently set the criterion report retention to 3 days, but that might be too short.
The bad idea about this implementation is that it clogs up CI for ~20 minutes. And the results can be affected by other runs. We can opt to limit the number of tests (1 tx, 5 tx, 10 tx, 50 tx, 100 tx), make it run only as a triggerable action or only run it on merge commits.

Add benchmarks to CI

---

explorer/CHANGELOG.md
explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
explorer/src/lib/components/block-details/BlockDetails.svelte
explorer/src/lib/components/blocks-list/BlocksList.svelte
explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap

explorer: Fix Average Fee Paid label

---

node-data/src/message.rs
node/src/databroker.rs

As per title, GetInv should be Inv, as it is used to send inventory messages in response to GetBlocks and GetMempool, and not to "request an Inv".

Rename GetInv to Inv

---

consensus/src/operations.rs
consensus/src/validation/step.rs
node/src/chain/consensus.rs

Change `verify_block_header` to ` verify_candidate_header`

---

consensus/src/commons.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/iteration_ctx.rs
consensus/src/phase.rs
consensus/src/proposal/step.rs
consensus/src/queue.rs
consensus/src/ratification/step.rs
consensus/src/validation/step.rs
node/src/chain/consensus.rs

Fix #2188 
- Remove `remove_msgs_greater_than`
- Remove `delete_candidate_blocks`
- `CONSENSUS_DELAY_MS` was already removed
- `add` is currently used
- `collect_from_past` is not removed (because part of a trait), but it's not invoked anymore

Remove unused definitions

---

explorer/CHANGELOG.md
explorer/src/lib/components/__tests__/TransactionStatus.spec.js
explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionStatus.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
explorer/src/lib/components/index.js
explorer/src/lib/components/transaction-details/TransactionDetails.svelte
explorer/src/lib/components/transaction-status/TransactionStatus.css
explorer/src/lib/components/transaction-status/TransactionStatus.svelte
explorer/src/lib/components/transactions-list/TransactionsList.svelte
explorer/src/lib/components/transactions-table/TransactionsTable.svelte
explorer/src/lib/dusk/components/__tests__/Badge.spec.js
explorer/src/lib/dusk/components/__tests__/__snapshots__/Badge.spec.js.snap
explorer/src/lib/dusk/components/badge/Badge.svelte
explorer/src/lib/mock-data/gql-transactions.json
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap

explorer: Show the error message for failed transactions

---

contracts/stake/src/state.rs
contracts/stake/tests/common/assert.rs
contracts/stake/tests/events.rs
execution-core/src/stake.rs
rusk-recovery/src/state.rs
rusk/tests/services/stake.rs

* Change slash to lock amount instead of move funds to reward (Resolves #1945)
* Allow for partial withdrawal of stake rewards
* Change unstake to remove the whole amount (active + locked)
* Change events emitted by the stake contract to include receiver only if needed

Stake contract refactor

---

test-wallet/src/lib.rs
wallet-core/src/lib.rs
wallet-core/tests/notes.rs

wallet-core: Also store the block-height for the owned notes

---

web-wallet/src/lib/components/Allocate/Allocate.svelte
web-wallet/src/lib/components/Balance/Balance.svelte
web-wallet/src/lib/components/UsageIndicator/UsageIndicator.svelte
web-wallet/src/lib/components/__tests__/Balance.spec.js
web-wallet/src/lib/components/__tests__/__snapshots__/Balance.spec.js.snap
web-wallet/src/routes/(app)/dashboard/+layout.svelte
web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/components-showcase/Balances.svelte
web-wallet/src/style/dusk-components/balance.css
web-wallet/src/style/dusk/language.css

web-wallet: Add UsageIndicator to Balance component

---

wallet-core/src/ffi.rs
wallet-core/src/keys.rs

- Add `derive_bls_pk`
Resolves #2254

wallet-core: add `generate_profile` function

---

contracts/transfer/src/state.rs
execution-core/src/transfer.rs
node-data/src/ledger.rs
node-data/src/ledger/transaction.rs
node/src/chain/acceptor.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/mempool.rs
rusk/src/lib/node/rusk.rs

- Reuse the current mempool features for moonlight txs too
- Check nonce repetition
- Transaction replacement (according to gas price)
-  Don't discard transactions that are not ready yet (nonce is not the next one)

node: Mempool handling for moonlight txs

---

contracts/stake/Cargo.toml
contracts/stake/tests/common/utils.rs
contracts/transfer/Cargo.toml
contracts/transfer/src/state.rs
contracts/transfer/src/tree.rs
contracts/transfer/tests/common/utils.rs
execution-core/src/transfer/phoenix.rs
execution-core/tests/serialization.rs
rusk/Cargo.toml
rusk/src/lib/test_utils.rs
rusk/tests/common/wallet.rs
rusk/tests/rusk-state.rs
test-wallet/Cargo.toml
test-wallet/src/imp.rs
test-wallet/src/lib.rs
wallet-core/src/transaction.rs

By reexporting we can wrap another dusk-dependency (`poseidon-merkle`) downstream and the type alias highly increase the readability of the code.
Additionally the `NoteLeaf` can replace the `EnrichedNote` in `wallet-core` (see #2241)

execution-core: re-export and type alias poseidon merkle types

---

contracts/bob/Cargo.toml
contracts/bob/src/lib.rs
contracts/bob/src/state.rs
contracts/host_fn/src/lib.rs
rusk-abi/CHANGELOG.md
rusk-abi/src/abi.rs
rusk-abi/tests/lib.rs
rusk/tests/services/mod.rs
rusk/tests/services/owner_calls.rs

This PR makes it possible to implement contract method which will enforce that only contract owner is able to call it.
The PR contains necessary changes in rusk-abi as well as a reference implementation and tests.
Implements #2230

Issue 2230 owner only calls

---

execution-core/src/transfer/phoenix.rs
test-wallet/src/imp.rs
wallet-core/src/lib.rs
wallet-core/tests/notes.rs

wallet-core: Refactor `phoenix_balance` to work with `NoteLeaf`

---

rusk-wallet/Cargo.toml
rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/command/history.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/io/gql.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/bin/settings.rs
rusk-wallet/src/cache.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/clients/sync.rs
rusk-wallet/src/currency.rs
rusk-wallet/src/dat.rs
rusk-wallet/src/error.rs
rusk-wallet/src/lib.rs
rusk-wallet/src/rusk.rs
rusk-wallet/src/store.rs
rusk-wallet/src/wallet.rs
rusk-wallet/src/wallet/address.rs
wallet-core/src/ffi.rs
wallet-core/src/input.rs
wallet-core/src/keys.rs
wallet-core/src/lib.rs
wallet-core/tests/notes.rs

- Port rusk-wallet to new wallet-core
- Add missing features in wallet-core for working with input notes
closes #2143

Port rusk-wallet to new wallet-core

---

contracts/stake/tests/common/utils.rs
contracts/stake/tests/stake.rs
contracts/transfer/tests/common/utils.rs
contracts/transfer/tests/transfer.rs
execution-core/CHANGELOG.md
execution-core/src/error.rs
execution-core/src/transfer.rs
execution-core/src/transfer/data.rs
execution-core/src/transfer/moonlight.rs
execution-core/src/transfer/phoenix.rs
execution-core/tests/serialization.rs
node-data/src/ledger/transaction.rs
rusk/src/lib/error.rs
rusk/src/lib/node/rusk.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/gas_behavior.rs
rusk/tests/services/stake.rs
rusk/tests/services/unspendable.rs
test-wallet/src/imp.rs
wallet-core/src/transaction.rs

In this PR we introduce memos - small pieces of data that a transfer may carry that can be useful in a myriad of situations. Memos are often used by exchanges to be able to target internal accounts whilst using a single key/address for receiving deposits.
This implementation overloads the `ContractExec` enum with an additional `Memo` variant, where the transactor may place at most 512 bytes of information. This has the advantage of not adding an additional optional field in a transaction, but comes at the cost of memos only being available for transactions that don't include a contract call or deployment.
Due to this enum overloading, the name `ContractExec` no longer makes sense, so we rename it to `TransactionData`, together with the `exec` fields in the transaction structures - which …

Introduce transaction memos

---

rusk-recovery/config/testnet.toml

In order to facilitate the usage of the upcoming testnet, we decided to move the ITN rewards (previously locked into the stake-contract) to ready-to-use moonlight accounts

rusk-recovery: move ITN2 rewards to Moonlight

---

contracts/alice/src/lib.rs
contracts/alice/src/state.rs
contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/transfer.rs
execution-core/CHANGELOG.md
execution-core/src/transfer.rs

This PR enables the ability of contracts to send funds directly to a Moonlight account. This facilitates use-cases requiring sending Dusk through a contract to Moonlight accounts, including but not limited to bridging.
To achieve this we add a `transfer_to_account` function to the transfer contract, taking as argument a `TransferToAccount` structure, that can be called by a contract to transfer funds to any Moonlight account they wish. Multiple calls may be chained to make contracts that effectively transfer Dusk to several accounts atomically. The function is the equivalent of `transfer_to_contract` but for accounts, and puts accounts and contracts on the same footing in terms of being able to receive funds directly.
One important asymmetry between accounts and contracts, however, is the …

Support contracts sending funds to a Moonlight Account

---

contracts/transfer/src/state.rs
execution-core/src/transfer/data.rs
execution-core/src/transfer/moonlight.rs
execution-core/src/transfer/phoenix.rs
execution-core/tests/serialization.rs
rusk/src/lib/node/rusk.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/owner_calls.rs

This PR addresses two consistency topics:
1. Every `topic` in rusk_abi::emit events used in Rusk is lower case and according to ZER0 should be lower case. So I changed the "TREE_LEAF" to "tree_leaf" as it was the only topic that used upper case.
2. Piecrust has an init method to run arbitrary initialization logic during deployment. For reasons explained in https://github.com/dusk-network/piecrust/pull/381, we have changed all related naming from constructor_ to init_, this change is now also reflected in the relevant Rusk parts.

Fix minor consistency issues

---

contracts/stake/src/lib.rs
contracts/stake/src/state.rs
contracts/stake/tests/common/assert.rs
contracts/stake/tests/events.rs
contracts/stake/tests/stake.rs
execution-core/CHANGELOG.md
execution-core/src/stake.rs
rusk/src/lib/node/rusk.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/owner_calls.rs

This is not only a performance optimization, but also useful for minimizing the amount of events emitted - which has a storage impact on prospective archivers.

Consolidate `reward` calls into one

---

consensus/src/commons.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/iteration_ctx.rs
consensus/src/phase.rs
node/src/chain/consensus.rs
node/src/database/rocksdb.rs

Implements #1908 
- move the committee generation code from phase `run` function to the new `generate_committee` in IterationCtx
- move get_sortition_config to IterationCtx
- remove save_committee
- if starting from `saved_iteration != 0`, generate all committees from iteration 0 to saved_iteration before running the step loop. This is needed in order to ensure we don't panic due to a missing committee when processing a message from a past iteration[^1].
- extract next generator on Validation/Ratification step instead of Proposal
- fix 'iteration < CONSENSUS_MAX_ITER' bug: last iteration is actually CONSENSUS_MAX_ITER-1, so when iteration = CONSENSUS_MAX_ITER-1 we should NOT extract the next generator
[^1]: This is a naive approach just to be on the safe side and not waste too much time. …

consensus: Start from saved iteration on restart

---

rusk/CHANGELOG.md
rusk/default.config.toml
rusk/src/bin/config/chain.rs
rusk/src/bin/main.rs
rusk/src/lib/node.rs
rusk/src/lib/node/rusk.rs
rusk/tests/common/state.rs
rusk/tests/config/contract_deployment.toml
rusk/tests/services/contract_deployment.rs
rusk/tests/services/owner_calls.rs

This PR improved deployment pricing in such a way that the cost of deployment should not be negligible to the user.
The deployment charging behaviour is controlled by the following configuration items:
```
gas_per_deploy_byte
min_deployment_gas_price
```
Transaction containing deployment will be discarded if the minimum transaction gas price is insufficient.
The defaults are set as follows:
```
const DEFAULT_GAS_PER_DEPLOY_BYTE: u64 = 100;
const DEFAULT_MIN_DEPLOYMENT_GAS_PRICE: u64 = 2000;
```
Current defaults should enforce reasonable deployment costs in the real world.
Implements #2207

Improved deployment pricing

---

contracts/stake/src/state.rs
contracts/stake/tests/common/assert.rs
contracts/stake/tests/events.rs
execution-core/src/stake.rs

> ### Stake Events
> 
> - Stake
> 	* Emit event with the account that staked and the staked amount
> - Unstake
> 	* Remove receiver of the withdraw, relying on the transfer contract to inform of the mint
> - Withdraw
> 	* Remove receiver of the withdraw, relying on the transfer contract to inform of the mint
> - Reward
> 	* Change the `reward` function to take a vector of keys and values, to emit a single event. #2292 
> 	* Add reason for reward - possibly a byte is enough. #2292
> - Slash
> 	* Merge the `suspended` and `slash` events into one
> - Hard Slash
> 	* Merge the `suspended` and `hard_slash` events into one
See also #2265

stake-contract: events

---

consensus/Cargo.toml
consensus/benches/merkle.rs
consensus/src/commons.rs
consensus/src/config.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/handler.rs
rusk/src/lib/node/rusk.rs

consensus: Limit transactions & faults in proposed block 

---

node-data/src/message.rs

Add ConsensusHeader to Candidate signature

---

contracts/transfer/src/state.rs
contracts/transfer/src/transitory.rs
contracts/transfer/src/tree.rs
execution-core/CHANGELOG.md
execution-core/src/transfer.rs
execution-core/src/transfer/withdraw.rs

The following events are added, which are emitted when the function with their same name is successful:
- `mint`, using `WithdrawEvent`
- `withdraw`, using `WithdrawEvent`
- `convert`, using `ConvertEvent`
- `deposit`, using `DepositEvent`
- `transfer_to_contract`, using `TransferToContractEvent`
- `transfer_to_account`, using `TransferToAccountEvent`
Additionally an event is emitted at the end of any transaction ingestion. This event will either be `phoenix` or `moonlight`, using either `PhoenixTransactionEvent` or `MoonlightTransactionEvent` respectively, depending on the model used, and are emitted during the host's call to `refund`. This is so that the event data can contain both the change and gas spent.
As a consequence of the above changes, we needed to slightly change the way in …

transfer-contract: add richer event emissions

---

rusk/src/lib/http.rs
rusk/src/lib/http/event.rs
rusk/src/lib/node.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs

"Just to" improve the info available to the Archival
This PR doesn't impact performance of the VM, since the TX_ID is enriched at node level.
When events are dispatched through RUES, the new field is added as `Rusk-Origin` header in the response (without changing the event data) ensuring smooth deserialization for backward compatibility.

rusk: Enrich contract events with transaction id

---

contracts/stake/src/state.rs

Fix a bug where the previous state were overwritten during a Stake Operation
Even if this had no consequence for the sortition (having `None` or `Some( Stake {amount: None} )` is the same) it was conceptually wrong since it's going to erase the previous state fields like `faults`, `nonce`

stake-contract: fix prev_stake for Stake operation

---

contracts/transfer/src/state.rs
execution-core/src/transfer.rs

We decided against placing the full result of a contract call, or the contract ID of a deployment contract in the transaction events. However we did agree that it would be nice if the optional memo was available to any event listener.
This PR adds a `memo` field to `PhoenixTransactionEvent` and `MoonlightTransactionEvent`, and adjust the transfer contract to emit an empty `Vec<u8>` in said field if there is no memo, and the memo included with the transaction if it exists.

Add memo to transaction events

---

consensus/src/commons.rs
consensus/src/config.rs
consensus/src/operations.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/handler.rs
node-data/src/encoding.rs
node-data/src/ledger.rs
node-data/src/ledger/block.rs
node-data/src/ledger/faults.rs
node-data/src/ledger/header.rs
node-data/src/ledger/transaction.rs
node-data/src/message.rs
node/src/chain/header_validation.rs
rusk/benches/block_ingestion.rs
rusk/src/lib/node/rusk.rs
rusk/tests/common/state.rs

consensus: check block size

---

rusk-wallet/src/dat.rs
rusk-wallet/src/store.rs
wallet-core/.cargo/config.toml
wallet-core/Cargo.toml
wallet-core/src/ffi.rs
wallet-core/src/ffi/debug.rs
wallet-core/src/ffi/error.rs
wallet-core/src/ffi/panic.rs
wallet-core/src/input.rs
wallet-core/src/keys.rs
wallet-core/src/lib.rs
wallet-core/src/notes.rs
wallet-core/tests/notes.rs

- Change notes test to be close to SDK ones
- Add `map_owned` FFI
- Add `balance` FFI
- Add `OwnedList` serializable type
- Add `ErrorCode` usage
- Move `map_owned` in `notes` module with `OwnedList`
- Add FFI's ErrorCode enum and codes handling (requires `try_trait_v2`)
- Add debugging capabilities
- Add `dbg!` and `eprintln!` macros implementation for WASM host
- Add panic handling for debug builds
- Add rkyv
- Add compiler optimizations
- `rusk-wallet:` remove unnecessary `Seed` structure
Resolves #2315
Resolves #2317

wallet-core: work on FFI

---

rusk/tests/config/convert.toml
rusk/tests/services/conversion.rs
rusk/tests/services/mod.rs
test-wallet/src/imp.rs
wallet-core/src/transaction.rs

As advertised, this PR introduces two functions in `wallet-core` to be able to convert Dusk between Moonlight and Phoenix. The functions are:
- `moonlight_to_phoenix`
- `phoenix_to_moonlight`
The tests occur in `rusk` in the context of block ingestion, so we're sure that the transactions these two functions create can be ingested properly by the chain.
As a consequence, a totally generic `moonlight` function is created, mirroring the `phoenix` function, that allows for creating a Moonlight transaction in a similar way to Phoenix.

Add conversions between Moonlight and Phoenix to `wallet-core` and test them

---

.github/workflows/rusk_ci.yml

As per request by the core team, adding in the main CI a section to copy the artifact on the host machine via a shared folder.
The runners have already been updated to mount the shared folder on launch.

CI: Add section to copy rusk artifact to shared folder on the CI host

---

contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs

- Add `sync_accounts`
- Add `sync_contract_balances`
- Add `sync_nullifiers`
Additionally:
- Change max_roots to 2*EPOCH (just to remove magic number)
⚠️ Change state to store AccountPublicKey as raw_bytes ⚠️
To improve the sync performance, we need to avoid PublicKey::from_bytes() during the feed (exactly like we do for the stake_contract)
Using PublicKey::from_raw_bytes() is way faster
```
test benches::deser::bench_deser_compressed       ... bench:     235,719 ns/iter (+/- 8,456)
test benches::deser::bench_deser_uncompressed     ... bench:          50 ns/iter (+/- 2)
```

transfer-contract: add sync methods (alternative version)

---

consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/iteration_ctx.rs
consensus/src/msg_handler.rs
consensus/src/proposal/handler.rs
consensus/src/ratification/handler.rs
consensus/src/validation/handler.rs

Resolves #2247 
Protocol Changes:
- Disable repropagation of future-round messages
- Pre-verify future-iteration messages for the current round, before repropagating them or putting them in the queue
Refactoring
- Add a `generate_iteration_committees` to IterationCtx
- Use `generation_iteration_committees` for:
- re-generating committees when restoring iteration after restart
- generate iteration committees at the beginning of a new iteration
- generate iteration committees before verifying future-iteration messages

Disable future message repropagation

---

execution-core/src/transfer/data.rs
rusk/tests/services/multi_transfer.rs
test-wallet/src/imp.rs
wallet-core/Cargo.toml
wallet-core/src/transaction.rs

This PR adds contract deployment transaction generation to `wallet-core`, using either Phoenix or Moonlight, for use in downstream wallets. It gets us a step closer to a wallet that supports all operations on chain.
It also includes a test requested by @herr-seppia to try and perform a deployment that will make the block run out of gas, and ensure that there is no hash mismatch between EST and AST.

wallet-core: add deployment transactions

---

consensus/src/aggregator.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/validation/handler.rs
consensus/src/validation/step.rs
node-data/src/ledger/faults.rs
node-data/src/message.rs
node/src/chain/header_validation.rs

- Don't slash on emergency iterations
- Don't aggregate failing votes on emergency
- Restore iteration at emergency if last_iter was higher (Fix restart at max_iter)
- On emergency cast votes only if they are valid

consensus: relax emergency iterations checks

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/dusk/components/Mnemonic/Mnemonic.svelte

web-wallet: Restrict mnemonic step input to alphabetical characters (Restore Flow)

---

rusk/src/bin/args/state.rs
rusk/src/lib/lib.rs
rusk/src/lib/node/rusk.rs

When a node is restarted during a commit deletion, some folder are dirty.
This lead to rusk-recovery to not be able to load the VM
This PR flags the commit folder for deletion, and remove them (if needed) while restoring the state

rusk: remove dirty state folders

---

rusk/Cargo.toml
rusk/Makefile
rusk/src/bin/config.rs
rusk/src/bin/config/kadcast.rs
rusk/src/bin/main.rs
rusk/src/lib/builder.rs
rusk/src/lib/builder/http_only.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/error.rs
rusk/src/lib/http.rs
rusk/src/lib/http/event.rs
rusk/src/lib/lib.rs
rusk/src/lib/node.rs
rusk/src/lib/node/rusk.rs

This PR aims to embed the HTTP server instantiation inside the rusk builder.
This is required in order to test the whole "binary" inside the rust test suite, and without rely on external testbed

rusk: refactor rusk builder

---

node/src/chain.rs
node/src/chain/genesis.rs
rusk/src/bin/config/chain.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/node.rs

Resolves #2431 
This is a best effort PR
Proper solution would be to move the chain settings from rusk.toml to rusk.settings
Those settings should contain:
- Genesis Timestamp (default to UNIX_EPOCH for tests)
- Genesis Seed (default to [0u8;48] for tests
- ChainId (default to 0 for tests)
- Genesis state root (default ask to VM)
See #2430

node: use external timestamp to generate genesis_block

---

wallet-core/src/ffi.rs
wallet-core/src/notes/balance.rs

- Add `ITEM_SIZE` and `KEY_SIZE` globals
- Change `balance:calculate` to check the notes' ownership
- Add `balance::calculate_unchecked` to skip the ownsership's check
- Change FFI `map_owned` to return also max `block_height` and `last_pos`

wallet-core: adjust lib for FFI usage

---

consensus/src/aggregator.rs
consensus/src/commons.rs
consensus/src/config.rs
consensus/src/execution_ctx.rs
consensus/src/msg_handler.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/handler.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/validation/handler.rs
consensus/src/validation/step.rs
node-data/src/message.rs
node/src/chain.rs
node/src/chain/consensus.rs
node/src/chain/fsm.rs
node/src/chain/header_validation.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/databroker.rs
node/src/network.rs

When a node joins an emergency iteration:
- If Proposal step times out and the provisioner is a committee member of Validation step then the node should request the candidate. If candidate is received then it is handled by `on_emergency_mode` and a vote can be casted.

Facilitate voting in emergency mode

---

rusk/src/lib/http/chain.rs

Currently the endpoint returns the rust's debug string that is useless to the client.

rusk: add serialization to graphql error returned to clients

---

.gitignore
node-data/Cargo.toml
node-data/src/archive.rs
node-data/src/events.rs
node-data/src/events/blocks.rs
node-data/src/events/contract.rs
node-data/src/lib.rs
node/.env
node/.sqlx/query-14e22bec4a8a50d407955a5db5fdf66138a9e1a0f14967134e3f2370d12d3173.json
node/.sqlx/query-56e2b507ef0b75a8ce74c034caa97c769a0fdd06dd02daf0a589f94191104333.json
node/.sqlx/query-92d1fbef465114b1b5cf9fd4bd2c5de7cf64f166957e61082f1a02b9b1988ae2.json
node/.sqlx/query-d9caf75d1a861747219f81ab0badbd7f8c96b61ba05f051db1ca653618cf7ae2.json
node/Cargo.toml
node/README.md
node/migrations/20240908201150_archive.sql
node/src/archivist.rs
node/src/chain/acceptor.rs
node/src/database.rs
node/src/database/archive.rs
node/src/lib.rs
rusk/Cargo.toml
rusk/benches/block_ingestion.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/http.rs
rusk/src/lib/http/event.rs
rusk/src/lib/node.rs
rusk/src/lib/node/events.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs

This PR introduces the "archive" feature flag to rusk and node. Another PR would build on top of this and introduce serving them through an http api.
When run with:
`DUSK_CONSENSUS_KEYS_PASS=password cargo r --release --features archive -p rusk  -- -s /tmp/example.state`, the archive feature is active and starts archiving contract events from the vm into an SQLite database.
This was done by adding a new service, ArchivistSrv, to the node's service_list. This service listens on a channel that receives the VM events from a sender that sends them during the execution of the `accept_transactions` function of the Rusk struct (the same place where VM events are sent to RUES).
The ArchivistSrv, upon receiving new VM events, calls the SQLiteArchive (which manages a SQLite db) and stores all …

Archive node feature

---

node/src/chain/acceptor.rs
node/src/chain/fsm.rs
node/src/chain/stall_chain_fsm.rs

If the node receives a block with higher iteration than the local block, it sends back the local block. The peer is expected to revert and accept it, unless the block sent to us has been finalized.
This commit also refactors on_block_event to unify the handling of remote_blk.height < tip.height and remote_blk.height == tip.height. These two cases are in fact equivalent and should be treated the same.
The unification of the two cases greatly improves readability and maintenance. A bug is also fixed, due to which  the node erroneously switched to OutOfSync if reverting a block lower than the tip.
---
To test this PR we need to:
- have a node N accept a block at iteration I > 0
- have the network produce a block at iteration J < I
- send the block at iteration J to node N
- if N sends back …

node: Send local block if iteration is lower

---

rusk/default.config.toml
rusk/src/bin/config/http.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/http_only.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/http.rs

This commit adds support for using `rusk`'s TOML configuration file to specify headers to be sent as a response to *every* HTTP response.
It is useful for any number of possible scenarios, such as setting CORS for a specific site, providing IDs to nodes in larger infrastructure, etc...
Resolves: #2454

rusk: add support for configurable HTTP headers

---

Dockerfile
README.md
node/src/chain.rs
node/src/lib.rs
node/testbed.sh
rusk-recovery/config/example.toml
rusk/Makefile
rusk/src/bin/args.rs
rusk/src/bin/args/command.rs
rusk/src/bin/args/command/chain.rs
rusk/src/bin/args/command/recovery.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/node.rs

- Move `recovery-keys` to `recovery keys`
- Move `recovery-state` to `recovery state`
- Add `chain revert`
This PR is just MVP, future refactor should pass the Command to the right component (to avoid expose any single function needed like I did for the revert)
Additionally, moving the command into distinct subcommand activated by features, will allow us to add commands related to features like:
- `rusk archive compress`
- `rusk wallet unstake`
and so on...

rusk: refactor CLI sub commands

---

rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs

Closes #2468 
- Add memo calls for each tranaction type
- Add categorization for each trasnaction type
It looks like this @HDauven @herr-seppia test it out let me know how it feels in terms of UX
With selected transaction type:

Add memo support

---

node/src/database.rs
node/src/database/rocksdb.rs
node/src/mempool.rs
rusk-wallet/src/error.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/http/rusk.rs

Allow preverification of transactions based on the full mempool acceptance

rusk: fix HTTP preverification

---

rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs

rusk-wallet: Accept string instead of bytes for Memo

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/components/Allocate/Allocate.svelte
web-wallet/src/lib/components/Send/Send.svelte
web-wallet/src/lib/components/Stake/Stake.svelte
web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/style/dusk-components/button.css
web-wallet/src/style/dusk-components/textbox.css
web-wallet/src/style/dusk/language.css

Resolves #2498
**Note:** Look at the issue for details on the context and the proposed solution.

web-wallet: Update textfield to use the small sizing

---

Cargo.toml
consensus/src/execution_ctx.rs
consensus/src/iteration_ctx.rs
consensus/src/msg_handler.rs
consensus/src/proposal/step.rs
consensus/src/queue.rs
consensus/src/ratification/handler.rs
consensus/src/validation/handler.rs
node-data/src/ledger.rs
node-data/src/message.rs
node/src/chain.rs
node/src/chain/consensus.rs
node/src/network.rs

- Improve logs related to messages
- Repropagate past-iteration messages in the current round
- Repropagate future messages if signed by eligible provisioners
- Repropagate Candidate messages before the Proposal delay

Improve message propagation and tracing

---

contracts/transfer/src/state.rs
contracts/transfer/src/transitory.rs
execution-core/src/transfer.rs
execution-core/src/transfer/moonlight.rs
execution-core/tests/serialization.rs
node-data/src/events/transactions.rs
node-data/src/ledger/transaction.rs
rusk-wallet/src/wallet.rs
rusk/src/lib/node/vm.rs
rusk/src/lib/verifier.rs
test-wallet/src/imp.rs

Changes:
- Use consts for event topics in transfer contract events, so that we can also use that const imported elsewhere to match on topics.
- Renamed "from" & "to" to "sender" & "receiver" for `MoonlightTransactionEvent` and related logic, so that it is consistently called sender/receiver in every context.
- Standardized the field order to sender, receiver, value in all transfer event structs.
- Changed "CONVERT" to "convert" in the self.mint_withdrawal call as it is also lower case for "mint" & "withdraw" calls.
The new sender, receiver, value ordering of fields (as `MoonlightTransactionEvent` already had with from, to, value) made the most sense to me, but I have no hard opinion on it. If there is a problem with it, I can change it back.

Update transfer events

---

contracts/alice/src/lib.rs
contracts/alice/src/state.rs
contracts/transfer/src/lib.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/transfer.rs
execution-core/src/transfer.rs

Rename:
- `transfer_to_contract` to `contract_to_contract`
- `transfer_to_account` to `contract_to_account`
Note that the `transfer` prefix is not needed since we are in the transfer-contract and hence the `transfer` is name-spaced anyway.

transfer-contract: Rename functions where a contract sends funds

---

rusk-wallet/Cargo.toml
rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/wallet.rs
rusk-wallet/src/wallet/gas.rs

- Check if the db is synced with the network 
- If not display placeholder on balance and don't allow wallet operations
Closes #2488

rusk-wallet: Add is_sycned() function call to estimate sync completion

---

rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/wallet.rs

Cherry picks the relevant commits from https://github.com/dusk-network/rusk/pull/2540 with minor changes in the displayed message when the wallet is not synced yet.

rusk-wallet: Add `is_synced()` function call to estimate sync completion

---

rusk-prover/Cargo.toml
rusk-prover/src/lib.rs
rusk/Cargo.toml

We need to print the circuit-bytes in the rusk tests to be able to update rusk-prover/test/tx_circuit_vec.hex in case of a change of the circuits.
This functionality was lost with the merge of #2135 specifically with the deletion of [line 149 in rusk/tests/common/wallet.rs](https://github.com/dusk-network/rusk/pull/2135/files#diff-f6f5e387d55a9a47a0c1dcac1842bea467aa86a5b0aba2064acc29d8c9fef62dL149).

rusk-prover: Add debug feature to print the circuit-bytes

---

rusk/src/lib/builder/node.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/block.rs
rusk/src/lib/http/chain/graphql/data.rs
rusk/src/lib/http/chain/graphql/tx.rs
rusk/src/lib/node.rs

This PR introduces the Archive to RuskNode & DBContext (if the Archive feature is set). This change allows us to use the archive within the graphql logic to retrieve data from it (by adding functions which can use the ctx to access the archive).

Make archive available in graphql

---

examples/genesis.toml

I've upped the default staked amount for local development because I sometimes stake from a secondary wallet. The 50/50 split online/offline is not ideal.

rusk: Add Moonlight account to genesis

---

node/.sqlx/query-dc6d1bfa595b7545e8a1bfdaa68f8b408b2bda1142934f2e36bd81135ab7b5c5.json
node/README.md
node/src/archive/moonlight.rs
node/src/archive/sqlite.rs
node/src/archive/transformer.rs
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/block.rs
rusk/src/lib/http/chain/graphql/data.rs
rusk/src/lib/http/chain/graphql/tx.rs

This PR introduces three new GraphQL queries for the node.
The three calls on the /on/graphql/query are:
``query { fullMoonlightHistory(address: "") { json } }``
``query { blockEvents(height: -1) { json } }``
``query { transactionsByMemo(memo: "") { json } }``
The address in the first query takes a base58 encoded moonlight address. For now, the only fields available are "json", which returns all the data from that endpoint.
NB: There are already breaking changes planned for these endpoints. Especially the allMoonlightTxs is an interim solution.

rusk: add preliminary archive graphql endpoints

---

node/src/mempool.rs
node/src/vm.rs
rusk/CHANGELOG.md
rusk/default.config.toml
rusk/src/bin/config/chain.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/node.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs
rusk/tests/common/state.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/owner_calls.rs

Enforce minimum gas limit for transactions in such a way that transactions are not propagated if they do not satisfy the minimum gas limit requirement.
Implements issue #2597

Enforce minimum gas limit for transactions

---

node-data/src/ledger/transaction.rs
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/mempool.rs
node/src/vm.rs
rusk/src/lib/node/vm.rs

Mempool allows moonlight txs if they satisfy one of the following:
- tx.nonce() is equal to state.account.nonce()+1
- tx.nonce() is greater of state.account.nonce()+1 and all the intermediate nonces are in the mempool
Additionally:
- Fixed a bug that was preventing mempool secondary index to be populated with moonlight txs
- Improve mempool pruning to remove dependant transactions for expired or discarded txs
Resolves #2605

node: mempool - reject moonlight txs with non consecutive nonce

---

node-data/src/ledger/transaction.rs

Replace BlsScalar hash with faster sha3
`Transaction::hash` is only used for the merkle_tree root inside the block header

node-data: change `Transaction::hash` to use Sha3

---

consensus/src/proposal/block_generator.rs
node-data/src/ledger/header.rs

- Add `iteration` to header debug 
- Add candidate signature
- Remove txs bytes from log (this actually remove all the deploy data from logs)

consensus: improve log for candidate generation

---

contracts/stake/tests/common/utils.rs
contracts/transfer/src/state.rs
contracts/transfer/tests/common/utils.rs
contracts/transfer/tests/transfer.rs
execution-core/src/transfer.rs
execution-core/src/transfer/moonlight.rs
execution-core/src/transfer/phoenix.rs
execution-core/tests/serialization.rs
node-data/src/events/transactions.rs
rusk-wallet/src/wallet.rs
rusk/tests/services/deploy.rs
test-wallet/src/imp.rs
wallet-core/src/transaction.rs

This PR add a `Fee` struct to the moonlight transaction payload to specify a `refund_address` that can be used to send the gas-refund to an account other than the sender.
The refund-info is also added to the phoenix- and moonlight-transaction-events so that the fee refunds are trackable.
Ideally, I would like to add a few other minor changes to the moonlight and phoenix transaction-generation API to this PR, so that they both mirror one another as much as possible.
Most notably:
- adjust the parameter in `Transaction::new` for both phoenix and moonlight transactions so that the sender, receiver and refund-address are equivalent
- rename the `stealth_address` field of the `phoenix::Fee` to `refund_address` to match the `moonlight::Fee` as much as possible
But because we are in an API …

execution-core: Add refund-address to moonlight transaction

---

rusk-wallet/Cargo.toml
rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/wallet.rs
rusk-wallet/src/wallet/gas.rs

This pick up the changes to the deploy-transaction creation from #2540 after it has been reverted and separated from the changes made to the syncing (#2558)

rusk-wallet: Fix creation of deploy-transaction

---

rusk-wallet/src/bin/interactive.rs

rusk-wallet: Move is_synced inside the loop of interactive

---

rusk/src/lib/bloom.rs

This commit adds the `(contract, topic, data)` triple to the bloom filter present in each block. This allows someone observing a block being emitted to both check for a `(contract, topic)` *and* the `(contract, topic, data)` triple being included the block. This facilitates the following workflow:
- Listener receives a block, and checks for `(contract, topic)`
- If exists, listener asks for full event data
- Listener checks that the `(contract, topic, data)` is also in the block

Add `(contract, topic, data)` to bloom

---

contracts/transfer/src/state.rs
contracts/transfer/src/tree.rs
execution-core/src/transfer.rs

Moves the filter for transparent notes with value 0 to `tree.push`

transfer-contract: Fix tree-filter for transparent notes with 0 value

---

contracts/stake/src/state.rs
execution-core/src/stake.rs

The culprit of the gas expenditure was the "in-contract" aggregation of bls public keys.
The following function was consuming more than 540M gas points
```rust
/// Return the `MultisigPublicKey` associated to this `StakeKeys`
///
/// # Errors
///
/// Look at `MultisigPublicKey::aggregate`
pub fn multisig_pk(&self) -> Result<BlsMultisigPublicKey, BlsError> {
BlsMultisigPublicKey::aggregate(&[self.account, self.funds])
}
```
Removing the BlsMultisig in favor of a (less elegant) DoubleSignature struct resulted in a way less gas spent
| **Operation**                                      | **Gas Cost (before)**                          | **Gas Cost (now)** | **Saving**
|----------------------------------------------------|---------------------------------------|-----------|-----|
| STAKE …

stake-contract: lower gas expenditure

---

node/src/archive.rs
node/src/archive/moonlight.rs
node/src/archive/sqlite.rs
node/src/archive/transformer.rs
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/data.rs
rusk/src/lib/http/chain/graphql/tx.rs

This pull request introduces a new endpoint, `moonlightTransfers`, which allows explicit querying of sender & receiver, but also block-height ranges and the ability to use pagination. 
An example query body for the new graphQL endpoint can now look like this:
```graphql
query { moonlightHistory(
sender: "pR8NnsQ9Le2hyuEgx2fk4RuZTngkz9T7WfkdDKSJmnfRYMmkNUPhFYXNAeatxsYiixgqq4iKfSCVuo7NhFkLgrbn1VTTweLhPXocUQ4rfxMLRajebdCcPxp46ddSVMpu2Nf",
receiver: "pR8NnsQ9Le2hyuEgx2fk4RuZTngkz9T7WfkdDKSJmnfRYMmkNUPhFYXNAeatxsYiixgqq4iKfSCVuo7NhFkLgrbn1VTTweLhPXocUQ4rfxMLRajebdCcPxp46ddSVMpu2Nf"
fromBlock: 100
toBlock: 21000
maxCount: 10
pageCount: 2
) { json } }
```
To achieve this, the previous address to tx_hash CF has been split into two, one for inflows and one for outflows. The CF now also contains …

node: split moonlight db CFs into inflows and outflows

---

rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/clients/sync.rs
rusk-wallet/src/lib.rs
rusk-wallet/src/rusk.rs
rusk-wallet/src/wallet.rs
rusk-wallet/src/wallet/address.rs

Add `Profile` struct that holds a `Shielded` (phoenix) and a `Public` (bls) public-key that can be used for generating transactions and staking operations.
This is in line with the terminology used in w3sper.

rusk-wallet: Add `Profile` and fix how addresses are shown

---

execution-core/src/transfer/phoenix.rs
wallet-core/src/transaction.rs

wallet-core: Always create transparent notes if the transfer-value is 0

---

rusk-wallet/src/bin/io/args.rs

Resolves #2647 by signalling we're talking about a "new" product here, letting go of the Dusk wallet versioning from the past.

rusk-wallet: Update clap wallet name and about

---

rusk-wallet/src/clients.rs
rusk-wallet/src/wallet.rs

rusk-wallet: Split `prove` and `propagate`

---

rusk-wallet/src/bin/interactive/command_menu.rs

Removes the duplicate stake-info item when running the wallet in interactive mode.
Also move the contract-deploy menu item one option down so that it comes before calculating the contract-id.

rusk-wallet: Remove duplicate stake-info item in interactive

---

rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/wallet.rs

rusk-wallet starts properly when no connection is available, allowing the users to perform basic operations like keys exporting 
If the connection is back, the wallet automatically restore and let the user to continue operate with it
in the future we can increase the allowed operation to new features like:
- change password
- offline history
- etc...
Additionally, the menu is the same for both synced and unsyced status, letting the user to perform moonlight operation while syncing with phoenix status
Resolves https://github.com/dusk-network/rusk/issues/2655

rusk-wallet: handle reconnection without restart

---

explorer/src/lib/components/__tests__/__snapshots__/ProvisionersCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/ProvisionersList.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/ProvisionersTable.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
explorer/src/lib/components/provisioners-list/ProvisionersList.css
explorer/src/lib/components/provisioners-list/ProvisionersList.svelte
explorer/src/lib/components/provisioners-table/ProvisionersTable.css
explorer/src/lib/components/provisioners-table/ProvisionersTable.svelte
explorer/src/lib/components/transactions-list/TransactionsList.svelte
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/provisioners/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap

explorer: Provisioners Page Updates

---

explorer/src/lib/url/__tests__/makeNodeUrl.spec.js
explorer/src/lib/url/makeNodeUrl.js

explorer: Add tests for makeNodeUrl

---

node/src/chain.rs
node/src/chain/acceptor.rs

Solves #2171 
REFACTORING:
- `execute`: merge handling of Quorum with other Consensus messages (avoids duplicated logic)
- `reroute_msg`:
- discard non-consensus messages at the beginning
- check if consensus task is running at the beginning and repropagate all (consensus) messages if not running
BUGFIX:
- `reroute_msg`: change `msg_round >= tip_height` to `msg_round > tip_height` check to avoid passing to the consensus task messages for the previous round (current round is tip+1)
CHANGES:
- Do not rebroadcast Quorum messages from the future (unless we are synchronizing)

Disable future quorum propagation

---

consensus/src/user/provisioners.rs
consensus/src/user/stake.rs
node/src/chain/acceptor.rs
node/src/vm.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs
rusk/tests/common/state.rs

Remove the need to query VM to update provisioners status

node: change provisioners according to stake events

---

consensus/src/execution_ctx.rs
consensus/src/proposal/step.rs
consensus/src/ratification/step.rs
consensus/src/validation/step.rs

Fix the edge case where next_slot is greater than the event_loop duration

consensus: fix proposal early timeout

---

node/src/chain.rs
node/src/chain/fsm.rs
node/src/chain/fsm/outofsync.rs

With the current PR the target block for sync is properly derived from the incoming blocks/quorum
below the log for a fresh new start, where the first 100blocks are received after the triggered request during acceptor::spawn, and the next batch is derived from the quorum produced by the living cluster
```
Process started
Wed Oct 23 15:55:26 2024 /opt/dusk/bin/rusk 
{"timestamp":"2024-10-23T15:55:30.875494Z","level":"INFO","event":"entering","from":10,"to":10,"peer_addr":"104.248.89.168:9000","mode":"out_of_sync","target":"node::chain::fsm::outofsync"}
{"timestamp":"2024-10-23T15:55:31.157365Z","level":"DEBUG","event":"sync target reached","height":10,"mode":"out_of_sync","target":"node::chain::fsm::outofsync"}
{"timestamp":"2024-10-23T15:55:31.371270Z","level":"DEBUG","event":"sync target …
```

node: fix OutOfSync handler

---

rusk-wallet/src/bin/command.rs

When constructing a tx that is not a transfer, we call `find_index` twice (once in `claim` and then again to get the index of the returned address).
This PR eliminates this double call.

rusk-wallet: Remove double call to find_index

---

rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/data.rs
rusk/src/lib/http/chain/graphql/tx.rs

Related to: #2704
This is an interim solution to provide the moonlight event data in json instead of bytes until execution-core has a feature for that.

node: add transfer event deserialization

---

contracts/host_fn/src/lib.rs
execution-core/src/lib.rs
rusk-abi/src/abi.rs
rusk-abi/src/host.rs
rusk-abi/tests/lib.rs

This PR changes `rusk_abi::verify_bls_multisig` to take multiple public keys and signatures. These then get aggregated in the host function and the aggregations verified against the message.
By introducing this, we effectively allow contracts to implement threshold signature schemes that rely on the aggregation capabilities of the host. For example, the contract could expose `fn pay_to(from: Id, from_keys: Vec<PublicKeyAndSignature>, to: PublicKey)` that only moves funds to the `to` account if the signatures included are valid over some message, and if the number of included keys is sufficient up to some configurable number.

Change `rusk_abi::verify_bls_multisig` to take multiple keys and signatures

---

rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/gas.rs

Check whether transfer, stake, shield and unshield operations are possible with the users given balance. If not, the user will be direct back to the menu of the selected profile.
Resolves #2396

rusk-wallet: Add balance check validation

---

rusk/Cargo.toml
rusk/default.config.toml
rusk/src/bin/config/http.rs

- Updated `toml` version in Rusk to workspace version
- Fixed u64 (de)serialization due to `toml` limitations (see: https://github.com/toml-rs/toml/issues/512 https://github.com/toml-rs/toml/issues/705 https://github.com/toml-rs/toml/issues/540)
- Ingest `feeder_call_gas` as String, update example.toml accordingly
I considered this approach to be the most pragmatic. I tried multiple different approaches, but most of them would push the problem deeper into our code base. This approach keeps it at the edges and only introduces a slight annoyance in that we need to push a numerical value as a string in our configuration files.
Resolves #2494

rusk: Upgrade toml to workspace version

---

contracts/host_fn/src/lib.rs
execution-core/src/lib.rs
rusk-abi/src/abi.rs
rusk-abi/src/host.rs
rusk-abi/tests/lib.rs

To save on space for each verification, we only take a single `MultisigSignature` as opposed to as many of them as keys.
While technically not required, using as many signatures as keys for each verification is a bit strange when we can use just one.

Use only one `MultisigSignature` in `rusk_abi::verify_bls_multisig`

---

wallet-core/Cargo.toml
wallet-core/src/ffi.rs
wallet-core/src/ffi/debug.rs
wallet-core/src/ffi/error.rs
wallet-core/src/ffi/mem.rs
wallet-core/src/notes/owned.rs
wallet-core/tests/notes.rs

- Add `debug` feature to Cargo.toml for debugging in release mode
- Add `derive_bls_sk` in `ffi.rs` to support BLS secret key operations.
- Add new modules for handling `MoonlightTransaction` and refactored note balance calculations.
- Add `display_scalar` in FFI for better formatting of BlsScalar types.
- Add `accounts_into_raw` in FFI to convert account buffers into raw bytes.
- Add `into_proved` in FFI for proving Phoenix transactions with a NoOp prover.
- Add `phoenix` and `moonlight` functions for handling Phoenix and Moonlight transactions.
- Change `map_owned`: now returns a `Vec<NoteList>` for multiple owners.
- Change `pick_notes` to handle bookmarks in a vectorized manner.
- Change error handling by adding new error codes for deserialization, Phoenix, and Moonlight transaction …

wallet-core: Add support for new tx types and improve note handling

---

.github/workflows/rusk_ci.yml

Resolves #2804 
This PR:
- Splits clippy check and nightly tests into a separate job, resulting in failing faster on clippy check errors
- Adds caching for Rust dependencies 
- Removes the artifact caching, since we already do this on merge (see: https://github.com/dusk-network/rusk/blob/master/.github/workflows/binary_copy.yml)
This results in a [~50% drop](https://github.com/dusk-network/rusk/actions/runs/11597109358) in total run duration on Rusk CI.

CI: Split Rusk CI tests and clippy check

---

web-wallet/src/routes/+layout.js

web-wallet: Reinstate the Safari polyfill that was removed by mistake

---

scripts/install-hooks.sh
scripts/pre-push.sh

Resolves #2813
Changes:
- `scripts/pre-push.sh`: Contains pre-push hook logic for modified workspace members
- `scripts/install-hooks.sh`: Script to install the pre-push hook
This PR introduces a pre-push hook that automatically runs `clippy` checks
only on the modified workspace members before each push
To install the hook, run `./scripts/install-hooks.sh` from the project root

scripts: Add pre-push Git hook clippy run on updated workspace members

---

execution-core/CHANGELOG.md
execution-core/src/error.rs
execution-core/tests/transaction.rs

Add tests for the creation of transactions, making sure that the correct errors are emitted.

execution-core: Add tests for transaction-creation

---

w3sper.js/src/network/components/blocks.js
w3sper.js/src/network/components/node.js
w3sper.js/src/network/mod.js
w3sper.js/src/transaction.js
w3sper.js/tests/network_test.js

- Add `blocks` component with `gasPrice` getter
- Change `network.node.info` as a getter instead of a function for consistency
Resolves #2842

w3sper: Add high-level API to retrieve gas price

---

Cargo.toml
rusk-abi/Cargo.toml

This solve the compiling issue related to the new `1.4.0` arbitrary version
```
error[E0658]: use of unstable library feature 'error_in_core'
--> /home/docker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arbitrary-1.4.0/src/lib.rs:52:6
|
52 | impl core::error::Error for MaxRecursionReached {}
|      ^^^^^^^^^^^^^^^^^^
|
= note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information
= help: add `#![feature(error_in_core)]` to the crate attributes to enable
```

rusk-abi: freeze `arbitrary` to `1.3.2`

---

Makefile

This pull request introduces 3 new Makefile commands in the top most Makefile.
make prepare-dev
make run-dev
make run-dev-archive
This is a mirror of the commands listed in the README to make it easier to run the node without having to type more than 2 commands. To run a node, all you need to do is entering `make prepare-dev` & then either `make run-dev` or `make run-dev-archive`. Once `make prepare-dev` has been run, there is no need to run it again, unless, for example the contracts change.

rusk: add makefile dev commands

---

w3sper.js/src/bookkeeper.js
w3sper.js/src/mod.js
w3sper.js/src/network/gas.js
w3sper.js/src/network/mod.js
w3sper.js/src/protocol-driver/mod.js
w3sper.js/src/transaction.js
w3sper.js/tests/balances_test.js
w3sper.js/tests/harness.js
w3sper.js/tests/transfer_test.js

- Remove `Bookkeeper#transfer()`
- Add `Bookkeeper#as()` method that returns a `BookEntry`
- Add private class `BookEntry` with `balance`, `transfer`, `unshield`, `shield` methods
- Add private class `BasicTransfer`, and public classes `Transfer`, `UnshieldTransfer`, `ShieldTransfer`
- Remove `TransactionBuilder` class
- Change `Gas` class to enforce `limit` and `price` conversion to `BigInt` when possible
- Change `Network#execute` to build a given `transaction` only if it has a `build` method
- Rename `intoProved` in `intoProven`, and `into_proved` in `into_proven`
- Add `ProtocolDriver#unshield()` method
- Add `ProtocolDriver#shield()` method
- Change tests accordingly to the new APIs
- Fix dupes error on Treasury test implementation by implementing a lookup table of nullifiers
- Add …

w3sper: Add `shield` / `unshield` API and transaction's type

---

w3sper.js/src/transaction.js
w3sper.js/tests/transfer_test.js

- Update `to` method to convert address to string and decode to bytes when transfer is built.
- Adjust one test to explicitly set string
Resolves #2903

w3sper: enable `transfer` to accept string for receiver's address

---

consensus/src/errors.rs
consensus/src/execution_ctx.rs
consensus/src/msg_handler.rs
consensus/src/proposal/handler.rs
consensus/src/proposal/step.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/validation/handler.rs

Resolves #2834
- Moves `verify_validation_result` from `verify` to `collect`
- Ensure Ratification vote matches vote in ValidationResult
Refactor:
- Rename `verify_new_block` to `verify_candidate_msg`
- Improve comments in `verify_candidate_msg`

Improve ratification propagation

---

consensus/src/execution_ctx.rs
consensus/src/ratification/handler.rs
consensus/src/step_votes_reg.rs
node/src/chain/header_validation.rs

Change the Ratification collect to only verify the ValidationResult in the Ratification vote if it has a quorum and our result is NoQuorum. 
If the verification succeeds, we also replace our result with the received ValidationResult.
We also change the Quorum message to use the local ValidationResult (possibly updated from the one from a Ratification vote) instead of the ValidationResult from the last vote we received.

Skip unncessary ValidationResult verification

---

node-data/src/events/contract.rs
node/src/archive/moonlight.rs
node/src/archive/transformer.rs
rusk/src/lib/http.rs
rusk/src/lib/http/chain/graphql/archive/data.rs
rusk/src/lib/http/event.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs

To have data consistency for available fields and to avoid NULL or None handling, I have removed the optionality of an origin for `ContractTxEvent`. 
Now the origin field always enriches a `ContractEvent` with an origin hash. This is the block hash for the three possible coinbase events. In all other cases, it is still the tx hash (tx id).

Remove Option<> on origin field for ContractTxEvent

---

web-wallet/src/lib/stores/__tests__/networkStore.spec.js
web-wallet/src/lib/stores/networkStore.js

web-wallet: The network store doesn't always use the cached connection

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/dusk/components/Mnemonic/Mnemonic.svelte

Resolves #2879
- Update Mnemonic (Authenticate) Enter key behavior
- Suggested words in the Mnemonic (Authenticate) are accessible using Tab

web-wallet: Update Mnemonic (Authenticate) behavior

---

rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/gas.rs
rusk-wallet/src/wallet.rs

Closes [#2622 ](https://github.com/dusk-network/rusk/issues/2622)

rusk-wallet-2622 | Set default gas price to the average mempool gas price

---

rusk-wallet/src/clients.rs
rusk-wallet/src/wallet/transaction.rs
wallet-core/src/notes/pick.rs
wallet-core/tests/notes.rs

The function `pick_notes` selects up to 4 input notes to be included in a phoenix-transaction.
With a spendable value lower than the total value of the notes, and the transaction target value higher than the spendable, `pick_notes` still returned 4 input-notes even though the transaction-costs weren't covered with those four notes.
To give an example:
Let's assume we have 5 unspent notes each with a value of 2 DUSK.
This means the max spendable is 8 DUSK (4 * 2).
For a transaction that costs 9 DUSK, `pick_notes` should return an empty list indicating that there is no combination of the input-notes where the transaction-costs is covered.
The old behavior of `pick_notes` however was to still return a  list of 4 input-notes, even though the values of those notes combined was lower than the …

wallet-core: Fix pick_notes function for selecting the input-notes for a transaction

---

execution-core/src/stake.rs
execution-core/src/transfer.rs
execution-core/src/transfer/data.rs
execution-core/src/transfer/moonlight.rs
execution-core/src/transfer/phoenix.rs
execution-core/src/transfer/withdraw.rs
execution-core/tests/serialization.rs
execution-core/tests/transaction.rs

execution-core: reorder imports to align with convention

---

web-wallet/CHANGELOG.md
web-wallet/src/routes/(app)/dashboard/+page.svelte

web-wallet: Add Link to Block Explorer on Wallet

---

wallet-core/src/ffi.rs
wallet-core/src/ffi/error.rs
wallet-core/src/transaction.rs

- Add `moonlight_stake` in FFI module
- Add `moonlight_unstake` in FFI module
- Add `moonlight_stake_reward` in FFI module
- Add `ErrorCode::ContractCallError`
- Change the visibility of `stake_reward_to_moonlight` to `pub(crate)`
- Change the visibility of `unstake_to_moonlight` to `pub(crate)`
Resolves #2955

wallet-core: expose staking capabilities via FFI

---

w3sper.js/src/bookkeeper.js
w3sper.js/src/network/mod.js
w3sper.js/src/protocol-driver/mod.js
w3sper.js/src/transaction.js
w3sper.js/tests/assets/genesis.toml
w3sper.js/tests/transfer_test.js

- Add `WithdrawStakeRewardTransfer` class in `transaction`
- Add `BookEntry#withdraw` method
- Add `withdraw` function in `protocol-driver`
- Add withdraws tests
Resolves #2952

w3sper: Add withdraw stake's reward method

---

.github/workflows/rusk_ci.yml
.github/workflows/w3sperjs_ci.yml

Compile wallet-core wasm in the CI run docker container and run w3sper tests
Resolves #2255

w3sper.js: Add CI

---

node/.sqlx/query-0ea0095fd1d173e4d259bce7877000866b46c0e5c5bdbc39721dd993b831533e.json
node/src/archive/archivist.rs
node/src/archive/moonlight.rs
node/src/archive/sqlite.rs
node/src/archive/transformer.rs
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/archive/data.rs
rusk/src/lib/http/chain/graphql/archive/events.rs

The main change is adding the graphQL endpoint for finalized contract events from a specific contract id to the archive gql endpoint now.
This pull request also includes a small refactor with changes to rename methods, types, and variables for shorter names, better clarity and consistency. An unused, redundant function also got removed. Additionally, the archive block events endpoint and type is now called contract events (as it sends out events emitted by a contract).

rusk: add gql endpoint for events from specific contract id

---

web-wallet/CHANGELOG.md
web-wallet/package-lock.json
web-wallet/package.json

Resolves #3020
- Added gas settings validation on Unstake / Widthdraw Rewards flows [#2000]
- Add temporary link to the block explorer on the dashboard [#2882]
- Add Staking-Related Functionality Utilizing w3sper [#3006]
- Add minimum stake amount supplied by w3sper instead of using an env var [#3010]
- Update `Stake` to use `Stepper` [#2436]
- Update Mnemonic (Authenticate) Enter key behavior [#2879]
- Enhance Error Handling on Wallet Access Page [#2932]
- Suggested words in the Mnemonic (Authenticate) are accessible using Tab [#2879]
- Enhance Allocate flow on full amount allocation [#2938]
- Broken link in the stake warning [#2990]
- Change "Transaction created" copy [#2991]
- Fix Dashboard navigation menu padding [#3000]

web-wallet: Release v.0.8.0

---

rusk-wallet/src/bin/command/history.rs
rusk-wallet/src/bin/config.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/bin/settings.rs
rusk-wallet/src/cache.rs
rusk-wallet/src/clients.rs
rusk-wallet/src/currency.rs
rusk-wallet/src/error.rs
rusk-wallet/src/gql.rs
rusk-wallet/src/lib.rs
rusk-wallet/src/rues.rs
rusk-wallet/src/wallet.rs

- Enhance error handling in the `inquire` menu. For non-critical errors, provide users with options to retry the failed operation or return to the previous menu, rather than always exiting with an error message.

Bugfix-2512 | rusk-wallet: Remove all panics in the codebase

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/dusk/currency/__tests__/duskToLux.spec.js
web-wallet/src/lib/dusk/currency/__tests__/luxToDusk.spec.js
web-wallet/src/lib/dusk/currency/duskToLux.js

- added test cases to `luxToDusk` function
Resolves #3032

web-wallet: fix edge case in Dusk to Lux conversion

---

w3sper.js/src/network/mod.js

- Remove unused private functions from network module

w3sper: Add `query { ... }` to argument given to `network.query`

---

w3sper.js/deno.json
w3sper.js/src/mod.js
w3sper.js/src/protocol-driver/mod.js
w3sper.js/tests/balances_test.js
w3sper.js/tests/harness.js
w3sper.js/tests/index.html
w3sper.js/tests/network_test.js
w3sper.js/tests/notes_test.js
w3sper.js/tests/profile_test.js
w3sper.js/tests/stake_info_test.js
w3sper.js/tests/transfer_test.js

- Add `@dusk/w3sper`  to import map for integration-like testing
- Add `useAsProtocolDriver` to avoid exposing full `ProtocolDriver`
- Fix `ProtocolDriver` leftover to use cryptographically secure `rng`
- Change tests to avoid automagically WASM loading

w3sper: Align tests with actual library usage

---

rusk/tests/services/finalization.rs
rusk/tests/services/mod.rs

This PR add tests to ensure that roots calculation is not influenced by the finalization strategy

rusk: add test for finalized roots

---

w3sper.js/src/lux.js
w3sper.js/src/mod.js
w3sper.js/tests/harness.js
w3sper.js/tests/index.html
w3sper.js/tests/lux_test.js

w3sper: add lux module for parsing and formatting in Dusk

---

explorer/CHANGELOG.md
explorer/src/lib/containers/statistics-panel/StatisticsPanel.css

Using `display: contents;` between `992px` and `1330px` width suppresses the effect of the wrapper element, putting the items next to each other.
This should give the desired responsive behavior and resolve https://github.com/dusk-network/rusk/issues/3034

explorer: Fix Cluster Location Layout

---

.github/workflows/docker_image_build.yml
Dockerfile
Makefile
README.md

This pull request introduces changes to support building and running the `rusk` binary in Docker with the archive feature
- add CARGO_FEATURES build-arg to Dockerfile
- change README to include new docker build command
- adjust workflow to use "archive" build-arg
- small improvement on Makefile commands

rusk: add new feature & change Dockerfile

---

rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/lib.rs

Add proper check for wasm file location

rusk-wallet: Fix contract deploy properly serialize init args

---

explorer/CHANGELOG.md
explorer/src/lib/components/data-card/DataCard.svelte
explorer/src/lib/components/transaction-details/TransactionDetails.svelte
explorer/src/lib/dusk/components/banner/Banner.css
explorer/src/lib/dusk/components/banner/Banner.svelte
explorer/src/lib/dusk/components/dusk.components.d.ts
explorer/src/lib/dusk/components/index.js
explorer/src/lib/services/__tests__/duskAPI.spec.js
explorer/src/lib/services/duskAPI.js
explorer/src/lib/services/gql-queries.js
explorer/src/routes/transactions/transaction/+page.svelte
explorer/src/style/dusk/colors.css
explorer/src/style/dusk/language.css

explorer: Get transaction from mempool

---

rusk-abi/src/abi.rs
rusk-abi/src/host.rs
rusk-abi/tests/lib.rs
rusk-profile/src/circuit.rs
rusk-profile/src/lib.rs
rusk-prover/src/lib.rs
rusk-recovery/src/keys.rs
rusk-recovery/src/keys/circuits.rs
rusk-recovery/src/state.rs
rusk-recovery/src/state/http.rs
rusk-recovery/src/state/snapshot.rs
rusk-recovery/src/state/snapshot/stake.rs
rusk-recovery/src/state/tar.rs

https://github.com/dusk-network/rusk/issues/2947 for rusk-abi, rusk-profile, rusk-prover, rusk-recovery

Reorder rusk-xxx imports

---

w3sper.js/src/bookkeeper.js
w3sper.js/src/network/syncer/account.js
w3sper.js/src/protocol-driver/mod.js
w3sper.js/src/transaction.js
w3sper.js/tests/assets/genesis.toml
w3sper.js/tests/harness.js
w3sper.js/tests/stake_info_test.js
w3sper.js/tests/stake_test.js
w3sper.js/tests/transfer_test.js

- Remove `nonce` field from stake transfer and info
- Add support for new stake features: top-ups, partial unstaking, etc.
- Change SDK methods to align with the updated contract structure
- Add validations for stake and top-up operations
- Move stake transfer related tests in its own test file
Resolves #3131

 w3sper: Update the SDK to match Stake contract changes

---

node-data/src/events/blocks.rs
node/src/chain.rs
node/src/chain/acceptor.rs
node/src/mempool.rs

Currently, the block event variant sent when a block is reverted is called "Deleted". We should not use different terminology or phrasing for the same thing to avoid ambiguity.
For that reason I changed the Event variant to "Reverted", to match what actually happens.

node: change Blockevent Deleted variant to Reverted

---

node-data/src/events.rs
node-data/src/events/blocks.rs
node-data/src/events/transactions.rs
node/src/chain/acceptor.rs
rusk/src/lib/node/events.rs

I updated the comments in node-data for further explanation. While doing so, I had the idea to introduce a BlockState enum, which effectively makes it impossible to create StateChange events with non-valid states (arbitrary &str) by restricting it to the types of the enum.

node-data: Add BlockState enum

---

rusk/src/lib/node/rusk.rs

Replace calls to the `hard_slash` method with `soft_slash`.
This is a failsafe measure to guarantee no money is (permanently) lost due to unforseen errors.
Hard slashing should be restored as soon as the network proved to be stable.

stake-contract: relax hard-slash to soft-slash

---

rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive/command_menu.rs

With this PR is not possible to specify a different password for the exported consensus keys

rusk-wallet: add support for export pwd in non-interactive

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/components/BigIntInput/BigIntInput.svelte
web-wallet/src/routes/(app)/settings/+page.svelte

web-wallet: Fix gas settings reset and validation in preferences

---

Cargo.toml
node/src/mempool.rs
node/src/vm.rs
rusk/default.config.toml
rusk/src/bin/config/chain.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/node.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs
rusk/tests/common/state.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/owner_calls.rs

Adds minimum deployment gas points setting, 
enforces a minimum cost for contract deployment even if the contract size is small.
Protects network from spamming with a large number of small contracts.
Implements a top priority #3210

Add minimum deployment gas points setting

---

consensus/src/user/provisioners.rs
contracts/stake/src/lib.rs
contracts/stake/src/state.rs
core/src/stake.rs
rusk-recovery/src/state/snapshot.rs
rusk-wallet/src/bin/io/prompt.rs
rusk/tests/services/contract_stake.rs
rusk/tests/services/moonlight_stake.rs
rusk/tests/services/phoenix_stake.rs
wallet-core/src/ffi.rs

- Change stake contract to use configurable values instead of const
- Deprecate MINIMUM_STAKE (use DEFAULT_MINIMUM_STAKE instead)
- Reorganize imports for stake-contract

stake-contract: use StakeConfig for minimum_stake and slash warning

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/errors/index.js
web-wallet/src/lib/errors/invalid-mnemonic-error.js
web-wallet/src/lib/errors/invalid-password-error.js
web-wallet/src/lib/errors/mismatched-wallet-error.js
web-wallet/src/routes/(welcome)/login/+page.svelte
web-wallet/src/routes/(welcome)/login/__tests__/__snapshots__/page.spec.js.snap

web-wallet: Fix wrong error shown in the login screen

---

consensus/src/aggregator.rs
consensus/src/commons.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/phase.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/handler.rs
node-data/src/message.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/node/vm.rs

- Fix `event_loop` to start Open Consensus Mode at the end of the last Ratification step (instead of the beginning of the last iteration)
Refactors:
- rename `last_step_running` to `is_last_step`
- delete `QuorumMsgSender` (replace `send_quorum` with `try_send`)
- order messages in `message.rs`
- improve logs

Refactor and fix event_loop

---

consensus/src/config.rs
consensus/src/proposal/block_generator.rs
node-data/src/ledger/header.rs
node-data/src/message.rs
node/Cargo.toml
node/src/chain.rs
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/chain/fsm.rs
node/src/chain/header_validation.rs
node/src/lib.rs
rusk/src/lib/node/rusk.rs

Partially implements https://github.com/dusk-network/rusk/issues/1234
New features:
It enables the acceptance of an Emergency Block (EB) with the following properties:
-  `iteration = u8::MAX`
- `timestamp > prev_block.timestamp + MIN_EMERGENCY_BLOCK_TIME`, where `MIN_EMERGENCY_BLOCK_TIME` is  of  `MAX_STEP_TIMEOUT x 3`  (`MAX_ITER_TIMEOUT`) times CONSENSUS_MAX_ITER + 1. This value aims at ensure enough time is given to provisioners to produce a block before an Emergency Block can be accepted.
- signed by Dusk (`DUSK_CONSENSUS_KEY`)
No Attestation is needed to accept an EB. 
For what concerns finality, the Emergency Block is consider as being produced at iteration CONSENSUS_MAX_ITER (i.e., the one after the last consensus iteration)
The EB is repropagated upon acceptance (unlike other …

consensus: accept Dusk-signed Emergency Block

---

rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/wallet.rs
rusk-wallet/src/wallet/address.rs
rusk-wallet/src/wallet/transaction.rs

rusk-wallet: Align shielded address naming with Web wallet terminology

---

.github/workflows/README.md
.github/workflows/rusk_build.yml

ci: Allow flexible Rusk binary building in workflow

---

consensus/src/proposal/block_generator.rs
consensus/src/proposal/handler.rs
node-data/src/ledger/faults.rs
node-data/src/ledger/transaction.rs
node/src/database/rocksdb.rs

node-data: change transaction hash method to digest

---

web-wallet/CHANGELOG.md
web-wallet/README.md
web-wallet/src/lib/components/ApproveMigration/ApproveMigration.svelte
web-wallet/src/lib/components/ExecuteMigration/ExecuteMigration.svelte
web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
web-wallet/src/lib/contracts/contract-descriptors.js
web-wallet/src/lib/migration/walletConnection.js
web-wallet/vite.config.js

Resolves #3267
Follow the linked issue for details on the changes delivered.

web-wallet: Improve Migration Functionality

---

.github/workflows/ruskwallet_build.yml

This PR:
- Updates `actions/upload-artifact` to v4
- Fixes semver use in the artifact
- Removes unnecessary use of compiler in the Matrix strategy
- Removes older Ubuntu versions

ci: Update Rusk wallet binary artifacts

---

web-wallet/CHANGELOG.md
web-wallet/src/routes/(welcome)/setup/PasswordSetup.svelte
web-wallet/src/routes/(welcome)/setup/create/+page.svelte
web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
web-wallet/src/routes/(welcome)/setup/create/__tests__/page.spec.js
web-wallet/src/routes/(welcome)/setup/restore/+page.svelte
web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js
web-wallet/src/routes/components-showcase/Banners.svelte

web-wallet: Change password setting as enabled by default

---

rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/command/history.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/error.rs
rusk-wallet/src/gql.rs

rusk-wallet: Implement moonlight history

---

rusk/CHANGELOG.md
rusk/src/lib/http.rs
rusk/src/lib/http/event.rs

If client is not requesting a strict check we should ignore the prerelease version of the current binary
If instead the client request a strict version we should respect that and check the version as is
This solves the issue when connecting to a node that is in`-dev` mode

rusk: relax `check_version_header`

---

rusk/CHANGELOG.md
rusk/src/lib/builder/node.rs

This change mitigates problems caused by https://github.com/dusk-network/rusk/issues/3359

rusk: increase archive channel capacity

---

rusk-recovery/Cargo.toml
rusk-recovery/build.rs
rusk-recovery/src/keys/circuits.rs

This is a requirmente for having rusk-recovery released on creates.io
When releasing a crate that uses a workspace, the parent cargo isn't available anymore (check [rusk-recovery-1.0.0.zip](https://github.com/user-attachments/files/18476492/rusk-recovery-1.0.0.zip))

rusk-recovery: parse plonk version at build time

---

web-wallet/CHANGELOG.md
web-wallet/src/lib/components/Stake/Stake.svelte
web-wallet/src/lib/components/Stake/Unstake.svelte
web-wallet/src/lib/components/__tests__/Unstake.spec.js
web-wallet/src/lib/components/__tests__/__snapshots__/Unstake.spec.js.snap
web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
web-wallet/src/lib/stores/__tests__/walletStore.spec.js
web-wallet/src/lib/stores/stores.d.ts
web-wallet/src/lib/stores/walletStore.js

web-wallet: Add support for partial unstake/withdraw rewards

---

rusk/CHANGELOG.md
rusk/src/lib/http/rusk.rs

rusk: HTTP - add endpoint for query account status

---

Cargo.lock
rusk/CHANGELOG.md
rusk/Cargo.toml

- Add `/on/account:<address>/status` endpoint [#3422]
- Change dependency declaration to not require strict equal [#3405]
[1.0.2]: https://github.com/dusk-network/rusk/compare/rusk-1.0.1...dusk-rusk-1.0.2

rusk: release `1.0.2`

---

Cargo.lock
Cargo.toml

Due to how Cargo works, we cannot use different versions of the same crate during development, as it results in mismatching types. This happens because they are compiled from two different sources: one from a release and the other from a pre-release.
It is also not possible to have a path dependency pointing to a new ready-to-release version (e.g., having dusk-core released as 1.0.0 and a path dependency pointing to an unreleased version like 1.0.1). Cargo treats them as different crates since their origins differ—one from crates.io and the other as a local path.
To enable the new development flow, all crates must be the same (local path). During the release process, only the changed crates—those with updates in the changelog—will be upgraded. Any untouched crates (e.g., …

workspace: prepare for next development iteration

---

web-wallet/CHANGELOG.md
web-wallet/package-lock.json
web-wallet/package.json

Resolves #3435
- Add support for partial unstake/claim rewards [#3009]
- Add "Unstake" flow validation [#3009]
- Store the wallet creation block height and show it in settings [#3381]
- Change Review step label to "Overview" (Send flow) [#3387]
- Remove gas settings from Overview step (Stake/Unstake flows) [#3009]
- Fix creation of a new wallet causing the sync to start from genesis [#3362]

web-wallet: Release 1.3.0

---

contracts/stake/tests/partial_stake.rs
contracts/stake/tests/stake.rs
contracts/transfer/tests/moonlight.rs
contracts/transfer/tests/phoenix.rs
rusk/benches/block_ingestion.rs
rusk/src/bin/config/chain.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/node.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs
rusk/src/lib/node/vm/config.rs
rusk/tests/common/state.rs
rusk/tests/rusk-state.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/contract_stake.rs
rusk/tests/services/conversion.rs
rusk/tests/services/finalization.rs
rusk/tests/services/gas_behavior.rs
rusk/tests/services/mainnet.rs
rusk/tests/services/moonlight_stake.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/owner_calls.rs
rusk/tests/services/phoenix_stake.rs
rusk/tests/services/transfer.rs
rusk/tests/services/unspendable.rs
vm/CHANGELOG.md
vm/src/execute.rs
vm/src/execute/config.rs
vm/src/lib.rs

This PR refactors the `execution` module to utilize the `vm::execution::Config` structure, enhancing configuration management within the VM. 
1. **Improved Code Modularity**:  
This change eliminates the need to pass individual variables across multiple functions, reducing clutter and ensuring that related parameters are logically grouped together.  
2. **Ease of Adding New Parameters**:  
By centralizing configuration into a single structure, the codebase is better prepared for future expansions, such as incorporating new ABIs or additional VM parameters. (See also #3341)
Additionally, this refactor introduces a new `RuskVMConfig` struct, which consolidates additional VM-related configurations not required by the `execution` module itself. Examples include `generation_timeout` and …

vm: Change `execution` module to use `execution::Config`

---

Cargo.lock
Cargo.toml
core/CHANGELOG.md
core/src/abi.rs
rusk/CHANGELOG.md
rusk/benches/block_ingestion.rs
rusk/default.config.toml
rusk/src/bin/config.rs
rusk/src/bin/config/chain.rs
rusk/src/bin/main.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs
rusk/src/lib/node/vm/config.rs
rusk/tests/common/state.rs
rusk/tests/rusk-state.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/contract_stake.rs
rusk/tests/services/conversion.rs
rusk/tests/services/finalization.rs
rusk/tests/services/gas_behavior.rs
rusk/tests/services/moonlight_stake.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/owner_calls.rs
rusk/tests/services/phoenix_stake.rs
rusk/tests/services/transfer.rs
rusk/tests/services/unspendable.rs
vm/CHANGELOG.md
vm/src/execute.rs
vm/src/execute/config.rs

This PR introduces the `abi::public_sender`, enabling contracts to access the public address of the transaction sender. 
The primary goal is to allow contracts to identify the original sender of a transaction, enhancing both functionality and security. 
This feature is designed to be optional and must be explicitly triggered specifying the feature in the config section
```
[vm.features]
ABI_PUBLIC_SENDER = activation_height
```
Additionally, this PR move the config related to the VM to a specific section 
```diff
[chain]
#db_path = '/home/user/.dusk/rusk'
#consensus_keys_path = '/home/user/.dusk/rusk/consensus.keys'
min_gas_limit = 75000
+[vm]
generation_timeout = '3s'
gas_per_deploy_byte = 100
min_deployment_gas_price = 2000
min_deploy_points = 5_000_000
block_gas_limit = 3_000_000_000
+ …
```

vm: add `public_sender` available to contracts

---

web-wallet/src/lib/components/Send/Send.svelte
web-wallet/src/lib/components/__tests__/Send.spec.js
web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap

web-wallet: Fix memo toggle appearance

---

Dockerfile

The Dockerfile still used the `rusk` package, instead of the new name for the Rusk package: `dusk-rusk`.
This PR should fix the Docker builds on Docker Hub.

rusk: Update Dockerfile to use dusk-rusk

---

rusk/CHANGELOG.md
rusk/src/bin/config/http.rs
rusk/src/lib/node/vm/query.rs

For https://github.com/dusk-network/rusk/issues/3481.
The issue occurred because queries are executed with a gas limit of `u64::MAX`.
This PR changes that to the block gas limit of 3_000_000_000.
When a query takes too long to execute, like in an infinite loop, the new result is a VM out of gas error.

rusk: changed the gas limit for queries to the block gas limit

---

node/src/chain.rs
node/src/chain/acceptor.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/node.rs
rusk/src/lib/node/vm.rs
rusk/src/lib/node/vm/config.rs

Change the finalization order according to the ABI_SENDER feature activation
See also #3341

node: change finalization order to support new piecrust

---

node/CHANGELOG.md
node/src/database.rs
node/src/database/rocksdb.rs

node: add ledger_txs fn to Ledger trait & Backend Ledger DB

---

node/src/archive/moonlight.rs
node/src/archive/sqlite.rs
node/src/archive/transformer.rs
rusk/CHANGELOG.md

node: change archive transformer

---

rusk/CHANGELOG.md
rusk/src/lib/http/chain.rs

This is also required to give users a feedback about their upgrade using `ruskquery info`
Example response
```json
{
"bootstrapping_nodes": [],
"chain_id": null,
"kadcast_address": "127.0.0.1:9000",
"version": "1.1.0-rc.2",
"version_build": "1.1.0-rc.2 (bca9a01a 2025-02-13)",
"vm_config": {
"block_gas_limit": 3000000000,
"features": {
"ABI_PUBLIC_SENDER": 100,
"key": 50
},
"gas_per_deploy_byte": 100,
"generation_timeout": "3s",
"min_deploy_points": 5000000,
"min_deployment_gas_price": 2000
}
}
```
See also #3341

rusk: add `vm_config` section to `/on/node/info`

---

Cargo.lock
Cargo.toml
core/CHANGELOG.md
core/Cargo.toml
node-data/CHANGELOG.md
node-data/Cargo.toml
node/CHANGELOG.md
node/Cargo.toml
rusk-prover/CHANGELOG.md
rusk-prover/Cargo.toml
rusk-recovery/CHANGELOG.md
rusk-recovery/Cargo.toml
rusk/CHANGELOG.md
rusk/Cargo.toml
vm/CHANGELOG.md
vm/Cargo.toml
wallet-core/CHANGELOG.md
wallet-core/Cargo.toml

- Add `abi::public_sender` [#3341]
- Add `[vm]` config section [#3341]
- Add CONTRACT_TO_ACCOUNT inflow case on archive moonlight filtering [#3494]
- Add Dockerfile for persistent state builds [#1080]
- Add `vm_config` section to `/on/node/info` [#3341]
- Deprecate `[chain].gas_per_deploy_byte` config [#3341]
- Deprecate `[chain].min_deployment_gas_price` config [#3341]
- Deprecate `[chain].generation_timeout` config [#3341]
- Deprecate `[chain].min_deploy_points` config [#3341]
- Deprecate `[chain].block_gas_limit` config [#3341]
- Change how Rusk controls the archive for synchronization [#3359]
- Update `bls12_381-bls` to 0.5 [#2773]
- Update `dusk-bls12_381` to 0.14 [#2773]
- Update `dusk-jubjub` to 0.15.0 [#2773]
- Update `dusk-plonk` to 0.21.0 [#2773]
- Update `dusk-poseidon` to 0.41 …

rusk: release `1.1.0`

---

explorer/src/lib/dusk/http/__tests__/failureToRejection.spec.js

explorer: Fix not awaited promises in `failureToRejection` tests

---

web-wallet/src/lib/dusk/http/__tests__/failureToRejection.spec.js

web-wallet: Fix not awaited promises in `failureToRejection` tests

---

rusk/CHANGELOG.md
rusk/src/lib/http/chain.rs

For https://github.com/dusk-network/rusk/issues/1225.
The API executes a transaction without persisting the result and returns the result to the user along with the gas spent and gas limit.

rusk: add simulate transaction API

---

rusk/CHANGELOG.md
rusk/Cargo.toml
rusk/Makefile

rusk: change `prover` to include `recovery-keys` feature 

---

Cargo.lock
Cargo.toml
rusk/tests/config/init.toml
rusk/tests/services/init.rs
rusk/tests/services/mod.rs
vm/CHANGELOG.md

rusk: test for calling contract init method via transaction
implements issue #3553 
relates to Piecrust issue 433 (change init to only be called during deploy)

test for calling contract init method via transaction

---

Cargo.lock
Cargo.toml
consensus/CHANGELOG.md
consensus/Cargo.toml
core/CHANGELOG.md
core/Cargo.toml
node-data/CHANGELOG.md
node-data/Cargo.toml
node/CHANGELOG.md
node/Cargo.toml
node/src/lib.rs
rusk/CHANGELOG.md
rusk/Cargo.toml
vm/CHANGELOG.md
vm/Cargo.toml

- Add Serde JSON support for genesis contract args [#3533]
- Add `create_if_missing` field to `DatabaseOptions`
- Add support for `RUSK_EXT_CHAIN` env
- Add simulate transaction API [#1225]
- Change piecrust version requirement to `0.28.0`
- Change `piecrust-uplink` version to `0.18.0`
- Change plonk verification to use embed verification data by default [#3507]
- Change responses for moonlight gql endpoints (archive node) [#3512]
- Change `prover` feature to include `recovery-keys` feature [#3507]
- Fix `MismatchHeight` error message
- Remove `WrappedContractId` [#3503]
[1.2.0]: https://github.com/dusk-network/rusk/compare/dusk-rusk-1.1.1...dusk-rusk-1.2.0

rusk: release `1.2.0`

---

explorer/CHANGELOG.md
explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
explorer/src/lib/components/transaction-details/TransactionDetails.svelte
explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap

explorer: Add "nonce" to transaction details page

---

w3sper.js/CHANGELOG.md
w3sper.js/src/rues/mod.js
w3sper.js/tests/harness.js
w3sper.js/tests/network_test.js

- Fix Rues not dispatching a "disconnect" event when the socket closes on its own
Resolves #3568

w3sper: Prevent new WebSocket creation if a connection is still active

---

Cargo.lock
Cargo.toml
consensus/CHANGELOG.md
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/ratification/handler.rs
consensus/src/step_votes_reg.rs

Fix #3543
Changes:
- Do not overwrite Validation StepVotes with local ones when building the Quorum message
- This behavior was intended to allow tracing a quorum in Validation even when the Ratification outcome is NoQuorum; however, Validation signatures cannot be verified by other nodes because the Attestation only includes the resutl (i.e., the winning vote) of the Ratification step.
- This also eliminate a duplicate construction of the Quorum message
- Refactor AttestationRegistry:
- change `set_step_votes` to return an Attestation instead of a Quorum message
- Delete duplicate `build_quorum_msg`
- remove unnecessary (now) RoundUpdate clone
- update logs
- Fix some duplicate and wrong Discarded Quorum log messages

consensus: Do not include Validation SV in case of NoQuorum

---

explorer/CHANGELOG.md
explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/BlocksTable.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/ProvisionersCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/ProvisionersTable.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/Table.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
explorer/src/lib/components/provisioners-table/ProvisionersTable.svelte
explorer/src/lib/components/table/Table.css
explorer/src/lib/components/table/TableCell.svelte
explorer/src/lib/dusk/value/createValueFormatter.js
explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/provisioners/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
explorer/src/style/main.css

I'd like to propose some cosmetic enhancements to the explorer, starting with this. This commit changes the *Accumulated Reward* column in the provisioners table so that:
1 - It is right-aligned. Numeric values are usually right-aligned for easier comparison.
2 - It forces the number of decimal places to always be 2. The current version can have fluctuating decimal places, making it harder to read the table as each row's decimal point shuffles around. This also helps with the "easier comparison" from before.
3 - Make the decimal digits less visible compared to the whole number. This is a personal preference and a few people on Discord agreed that it looked nicer :)
Let me know what you think.

explorer: Right-align provisioner rewards with uniform decimal digits

---

Cargo.lock
Cargo.toml
consensus/src/proposal/block_generator.rs
node-data/CHANGELOG.md
node-data/src/ledger/header.rs
node-data/src/ledger/transaction.rs
node/CHANGELOG.md
node/src/mempool.rs
rusk/CHANGELOG.md
rusk/src/lib/node/rusk.rs

- Make `Transaction` and `Header`'s `size` method infallible
- Checks transactions do not exceed the maximum size (MAX_BLOCK_SIZE - MIN_HEADER_SIZE) available in a block

Check transaction size before adding to mempool

---

explorer/CHANGELOG.md
explorer/package-lock.json
explorer/package.json

Resolves #3607
- Add "nonce" to transaction details page (Public transactions) [#3578]
- Add "in/out" indicator for transfer operations (Account page) [#3579]
- Changed provisioner rewards column to be more readable [#3581]
- Fix current balance showing "Loading..." for empty accounts [#3576]
- Fix Account page does not reload content on key change [#3591]

explorer: Version 1.2.0

---

Cargo.lock
Cargo.toml
core/CHANGELOG.md
core/src/transfer/data.rs
rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/bin/main.rs
rusk-wallet/src/gas.rs
rusk-wallet/src/wallet.rs

- Fix contract call non-interactive parsing
- Fix contract call double rkyv for fn_args
- Add output ContractId when deploying a wasm
- Change default deploy gas limit to be accepted by std mempool
Follow up of #3603

rusk-wallet: fix contract call

---

rusk/benches/block_ingestion.rs
rusk/tests/common/state.rs
rusk/tests/common/wallet.rs
rusk/tests/common/wallet/test_wallet/imp.rs
rusk/tests/rusk-state.rs
rusk/tests/services/contract_deployment.rs
rusk/tests/services/contract_stake.rs
rusk/tests/services/conversion.rs
rusk/tests/services/finalization.rs
rusk/tests/services/gas_behavior.rs
rusk/tests/services/init.rs
rusk/tests/services/mainnet.rs
rusk/tests/services/moonlight_stake.rs
rusk/tests/services/multi_transfer.rs
rusk/tests/services/owner_calls.rs
rusk/tests/services/phoenix_stake.rs
rusk/tests/services/transfer.rs
rusk/tests/services/unspendable.rs

Closes #3631 
```bash
cargo test --release --features "testwallet chain archive" -- --nocapture --color=always --show-output --include-ignored
```
**Result:** all tests compile

Bug-3631 | Fix tests compilation errors when archive feature is enabled

---

rusk/src/lib/http.rs

Closes #3633 
```bash
cargo test --release --features "testwallet chain" -- --nocapture --color=always --show-output --include-ignored
```
**Result:** The `http::tests::http_query` test doesn't panicking and passes

Bug-3633 | Fix http::tests::http_query test

---

node/CHANGELOG.md
node/src/archive/moonlight.rs
rusk/CHANGELOG.md
rusk/src/lib/http/chain/graphql.rs
rusk/src/lib/http/chain/graphql/archive/moonlight.rs

rusk: add from_block, to_block params to gql `fullMoonlightHistory` 

---

consensus/src/errors.rs
consensus/src/operations.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/step.rs
consensus/src/validation/step.rs
node/src/chain/consensus.rs
node/src/database.rs
node/src/database/rocksdb.rs
node/src/mempool.rs
node/src/vm.rs
rusk/src/lib/http/chain.rs
rusk/src/lib/http/chain/graphql/tx.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs

- Updates `OperationError`, `HeaderError`, and `VstError`
- Rename `VstError` to `StateTransitionError`
- Updates some Consensus logs
- Reduce log level of `TipChanged` errors from `ERROR` to `WARN`
- Change `execute_state_transition` to return `StateTransitionError` instead of `anyhow::Error`
- Improve EST and VST start logs
- Remove unnecessary `Result` from `mempool_txs_sorted_by_fee`, `mempool_txs_ids_sorted_by_fee`, `mempool_txs_ids_sorted_by_low_fee`
New log examples:
```
#EST
{"timestamp":"2025-04-10T09:35:28.432994Z","level":"INFO","event":"Start EST","height":9,"prev_state":"3b0099f04178207e...ddd94ce17215c35c","gas_limit":5000000000,"to_slash":"[]","target":"rusk::node::rusk","spans":[{"iter":0,"name":"Proposal","pk":"shAky1Dnjxdhy1Hs","round":9,"name":"main"}]}
#VST …
```

Improve State Transition error logs

---

node/src/archive/sqlite.rs
rusk/src/lib/builder/node.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs

Follow up of #3643, adding the migration

node: followup – add active accounts table in archive

---

Cargo.lock
Cargo.toml
consensus/CHANGELOG.md
consensus/Cargo.toml
core/CHANGELOG.md
core/Cargo.toml
data-drivers/data-driver/CHANGELOG.md
data-drivers/data-driver/Cargo.toml
data-drivers/data-driver/src/lib.rs
data-drivers/stake-contract/CHANGELOG.md
data-drivers/stake-contract/Cargo.toml
data-drivers/transfer-contract/CHANGELOG.md
data-drivers/transfer-contract/Cargo.toml
node-data/CHANGELOG.md
node-data/Cargo.toml
node/CHANGELOG.md
node/Cargo.toml
rusk-prover/CHANGELOG.md
rusk-prover/Cargo.toml
rusk-recovery/CHANGELOG.md
rusk-recovery/Cargo.toml
rusk/CHANGELOG.md
rusk/Cargo.toml
vm/CHANGELOG.md
vm/Cargo.toml
wallet-core/CHANGELOG.md
wallet-core/Cargo.toml

- Add `Content-Type: application/json` support for `/on/contracts` endpoint
- Add transaction serialization check
- Add max transaction size check
- Add `/on/driver:<contract>/<method>:<target>` endpoint
- Add from_block & to_block params to `full_moonlight_history` in gql [#3613]
- Upgrade piecrust to `0.28.1`

rusk: release `1.3.0`

---

wallet-core/CHANGELOG.md
wallet-core/src/keys/eip2333.rs

- Make `derive_master_sk` public & return BlsSecretKey
- Let `derive_child_sk` return BlsSecretKey instead of BlsScalar
- Change `derive_bls_sk` to take a BlsSecretKey as arg instead of a Seed
- Adjust tests
Resolves #3681

 wallet-core: change eip2333 public functions 

---

rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/command/history.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/bin/main.rs

Closes #3292
Test it out and let me know

rusk-wallet: Implement history pagenation and search

---

explorer/CHANGELOG.md
explorer/package-lock.json
explorer/package.json

Resolves #3680
- Fix truncated provisioners addresses when copied while on mobile view [#3675]
- Fix line height and letter spacing not being applied to the account balance's container [#3676]

explorer: Release v1.3.2

---

rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/interactive.rs

- Fixes https://github.com/dusk-network/rusk/issues/3192
- Partially fixes https://github.com/dusk-network/rusk/issues/3597.

rusk-wallet: don't exit when command errors in interactive mode

---

consensus/README.md

Due to renaming of `docs-public` to `docs`, the URL needs to change pointing to SA.

consensus: Update docs URL

---

explorer/CHANGELOG.md
explorer/src/lib/components/latest-blocks-card/LatestBlocksCard.svelte
explorer/src/lib/components/latest-transactions-card/LatestTransactionsCard.svelte
explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap

explorer: Fix Transaction and Block entries have different row heights (Home page)

---

consensus/src/aggregator.rs
consensus/src/consensus.rs
consensus/src/execution_ctx.rs
consensus/src/proposal/step.rs
consensus/src/quorum/verifiers.rs
consensus/src/ratification/handler.rs
consensus/src/ratification/step.rs
consensus/src/step_votes_reg.rs
consensus/src/validation/handler.rs
node-data/src/encoding.rs
node-data/src/message.rs
node/src/chain/acceptor.rs
node/src/chain/header_validation.rs

- Removes unused QuorumResult from `verify_step_votes` and `verify_votes`
- Transform `verify_votes` into `verify_quorum_votes` to make it explicit it checks votes reach the quorum threshold
- Move check to skip Validation votes verification (in case of NoQuorum vote) to `verify_step_votes`
---
Tests:

consensus: Refactor verify_att

---

Cargo.lock
rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/command.rs
rusk-wallet/src/bin/interactive.rs
rusk-wallet/src/bin/interactive/command_menu.rs
rusk-wallet/src/bin/io/prompt.rs
rusk-wallet/src/error.rs
rusk-wallet/src/wallet.rs
rusk-wallet/src/wallet/transaction.rs

Pass reward param to withdraw transaction function Add check for withdraw amount
Closes #2538

rusk-wallet: Allow withdrawing of partial rewards

---

rusk-wallet/CHANGELOG.md
rusk-wallet/src/bin/command/history.rs
rusk-wallet/src/bin/command/tests.rs
rusk-wallet/src/bin/command/tests/utils.rs
rusk-wallet/src/gql.rs
rusk-wallet/src/gql/tests/assets/full_moonlight_history.json

For https://github.com/dusk-network/rusk/issues/3712.
PR https://github.com/dusk-network/rusk/pull/3745 fixes the failure after staking.
This PR handles the unstaking.

rusk-wallet: fix transaction history fail after unstaking

---

rusk-wallet/src/bin/command/history.rs
rusk-wallet/src/gql.rs

Follow up on https://github.com/dusk-network/rusk/issues/3712.
Use only events emitted by the transfer contract to make the transaction history.

rusk-wallet: use only transfer contract emitted events in tx history

---

.github/workflows/ruskwallet_build.yml

Resolves #3749
Github-hosted runner macos-latest changed to macos-14, Intel Mac only supports macos-13. For more details, see: [Standard GitHub-hosted runners for public repositories](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)

CI: Lock Rusk wallet Intel Mac to macos-13

---

consensus/src/errors.rs
consensus/src/operations.rs
consensus/src/proposal/block_generator.rs
consensus/src/proposal/step.rs
consensus/src/validation/step.rs
node/src/chain/acceptor.rs
node/src/chain/consensus.rs
node/src/chain/header_validation.rs
node/src/vm.rs
rusk/benches/block_ingestion.rs
rusk/src/lib/error.rs
rusk/src/lib/node/rusk.rs
rusk/src/lib/node/vm.rs
rusk/tests/common/state.rs

RENAMES
- Functions
- `new_state_transition` -> `generate_state_transition`
- `verify_candidate` -> `validate_candidate`
- `check_header_vst` -> `check_transition_result`
- `execute_checks` -> `verify_block_header_fields`
- `verify_basic_fields` -> `verify_block_header_basic_fields`
- `do_accept_state_transition` -> `accept_state_transition`
- `build_state_transition` -> `create_state_transition`
- Errors
- `FailedEST` -> `FailedTransitionCreation`
- `FailedEST` -> `FailedTransitionVerification`
MOVES
- `check_transition_result` to `vm.rs`
- `EventBloomMismatch` and `StateRootMismatch` from `HeaderError` to `StateTransitionError`
- `verify_block_generator` call from `execute_checks`  to `verify_block_header_basic_fields`
ADDS
- `StateTransitionError::SessionError`
- …

Refactor State Transition (Part 2)

---

rusk/mainnet.config.toml
test_mainnet.sh

simply run
`sh test_mainnet.sh` to test current binary against mainnet
or 
`sh test_mainnet.sh --list` to get the lists of the available states and the use `sh test_mainnet.sh <block_number>`
You'll notice some `cannot notify events` but that's ok

workspace: add script to test binary against mainnet history

---

.github/workflows/rusk_ci.yml

Remove the cache step
Initially it was used to reuse test artifacts during the clippy checks
However, those two steps now run in parallel, so no sense at all in having the cache.
This saves 5min in uploading 2GB (twice)

workspace: remove ci cache

---

rusk/CHANGELOG.md
rusk/src/lib/http/chain.rs
rusk/src/lib/http/rusk.rs

This PR allows any client to do multiple sequential transactions without manually inspecting the mempool
>  // Determine the next available nonce not already used in the mempool.
// This ensures that any in-flight transactions using sequential nonces
// are accounted for.
// If the account has no transactions in the mempool, the mempool_nonce
// will be `None`, indicating that the next nonce is the same as the
// account's current nonce.

rusk: add `mempool_nonce` field to `/on/account/status` response

---

consensus/src/lib.rs
consensus/src/validation/step.rs
core/CHANGELOG.md
core/src/error.rs
core/src/lib.rs
core/src/transfer.rs
node/src/mempool.rs
node/src/vm.rs
rusk/src/lib/node/vm.rs
rusk/src/lib/node/vm/config.rs
vm/src/execute.rs
vm/src/execute/config.rs

This PR introduces a minimum gas limit to pay for blobs
Default to 0, it leaves the way open to future tuning
Additionally, this PR refactor how Blob and Deploy txs are verified, introducing a TxPreconditionCheck error variant that's handled in a single code spot (instead of having duplicated code)

rusk: add gas_per_blob configuration

---

Cargo.lock
Cargo.toml
data-drivers/README.md
data-drivers/data-driver/CHANGELOG.md
data-drivers/data-driver/Cargo.toml
data-drivers/data-driver/README.md
data-drivers/stake-contract/README.md
data-drivers/transfer-contract/README.md

- Add `alloc` feature
- Add standard wasm implementation
- Remove wasm-bindgen dependency
https://crates.io/crates/dusk-data-driver/0.2.0

Release dusk datadriver

---

Dockerfile.ephemeral

This PR locks the Dockerfile for Rusk to the Rust version used by our repo.
Resolves #3856

docker: Lock Rust version in Docker image

---

Dockerfile.ephemeral

The DuskC compiler for ARM64/MacOS is built against a base OS that had glibc version 2.39, which isn't the case for the other compiled artifacts.
The rust:1.82 version in our Dockerfile, however, uses glibc version 2.36, which means it fails for Mac users. This PR should resolve this by setting Ubuntu 24.04 explicitly, which comes with glibc version 2.39.

rusk: Fix dockerfiles to >= glibc 2.39

---

node/CHANGELOG.md
node/migrations/20250926044900_add_event_block_hash_and_unfinalized_indexes.sql

Resolves #3874
Rationale for the chosen indexes:
- `finalized_events_block_hash_idx`: Speeds up block lookups by `block_hash`, which is a bottleneck now
- `unfinalized_events_block_hash_idx`: Speeds up finalize/rollback operations that select or delete events by `block_hash`
- `unfinalized_events_block_height_idx`: Makes `MAX(block_height)` queries and `NOT EXISTS ... WHERE block_height=?` checks more efficient for unfinalized events
- `finalized_blocks_phx1_height_idx`: Allows for quick retrieval of the next block where a Phoenix TX is available, after a given height. (`nextPhoenix` GraphQL query)

archive: Add missing indexes to archive node for query performance

---

rusk/CHANGELOG.md
rusk/src/lib/http/rusk.rs

adds endpoint to download contract's data driver
in addition, changes the url path of endpoint for contract's data driver upload
resolves issue #3884
has a follow-up issue #3886

rusk: adds endpoint to download contract's data driver
