- Makefile
- contracts/bid/circuits/Cargo.toml
- contracts/bid/circuits/src/correctness.rs
- contracts/bid/circuits/src/lib.rs
> Implement a circuit for the bid correctness proof

- src/bin/main.rs
- src/lib/lib.rs
- src/lib/services/pki.rs
> Add PKI and blind bid service to rusk server

- src/lib/encoding.rs
- src/lib/lib.rs
- src/lib/services/pki.rs
- tests/pki_service.rs
> Add tests for PKI service

- Cargo.toml
- build.rs
This PR is for the harcoded version of transfer circuits.
This will include: 
- 12 Variants of the execute contract
- Send to contract obfuscated 
- Send to contract transparent
- Withdraw from obfuscated to contract
- Withdraw from obfuscated
> Modularised circuits

- build.rs
- profile/src/lib.rs
> Add `clear_all` method to Keys' profile

- contracts/transfer/circuits/src/send_to_contract_obfuscated.rs
- contracts/transfer/circuits/src/send_to_contract_transparent.rs
- contracts/transfer/circuits/src/withdraw_from_obfuscated.rs
> Implements #183 - Unsafe default transfer circuits

- contracts/transfer/Cargo.toml
- contracts/transfer/src/tests.rs
- contracts/transfer/src/transfer/call.rs
- contracts/transfer/src/wasm/callable.rs
> Closes #203 - Transfer contract agnostic call

- rusk/src/lib/services/blindbid/score_gen_handler.rs
- rusk/src/lib/services/blindbid/verify_score_handler.rs
> Remove warnings from bid service

- rusk-abi/CHANGELOG.md
- rusk-abi/Cargo.toml
- rusk-abi/README.md
- rusk-abi/src/host.rs
- rusk-abi/src/hosted.rs
- rusk-abi/src/lib.rs
- rusk-abi/tests/contracts/host_fn/Cargo.toml
- rusk-abi/tests/contracts/host_fn/src/lib.rs
- rusk-abi/tests/lib.rs
> rusk-abi: Add `verify_schnorr_sign()` host fn

- macros/code-hasher/Cargo.toml
- macros/code-hasher/LICENSE
- macros/code-hasher/README.md
- macros/code-hasher/src/lib.rs
> Prepare code-hasher for publishing

- circuits/blindbid/CHANGELOG.md
- circuits/blindbid/src/proof.rs
- circuits/blindbid/tests/tree_assets.rs
> blindbid-circuits: Change CIRCUIT_ID generation using `code-hasher`

- rusk-profile/src/lib.rs
- rusk/build.rs
> Cleaning up build system and profile

- Cargo.toml
- contracts/stake/Cargo.toml
- contracts/stake/Makefile
- contracts/stake/src/lib.rs
- contracts/stake/src/wasm.rs
- rusk-abi/src/lib.rs
> Stake contract

- Makefile
- circuits/bid/Cargo.toml
- circuits/blindbid/CHANGELOG.md
- circuits/blindbid/Cargo.toml
- circuits/blindbid/src/gadgets.rs
- circuits/blindbid/src/proof.rs
- circuits/blindbid/tests/bid_tests.rs
- circuits/transfer/CHANGELOG.md
- circuits/transfer/Cargo.toml
- circuits/transfer/src/withdraw_from_obfuscated.rs
- rusk/CHANGELOG.md
- rusk/Cargo.toml
- rusk/build.rs
- rusk/src/lib/services/blindbid/score_gen_handler.rs
- rusk/src/lib/services/blindbid/verify_score_handler.rs
> Update circuits to persistance-friendly deps

- Makefile
- contracts/bid/Cargo.toml
- contracts/bid/src/leaf.rs
- contracts/bid/src/map.rs
- contracts/stake/Cargo.toml
- contracts/transfer/Cargo.toml
- contracts/transfer/src/transfer/circuits.rs
- contracts/transfer/src/transfer/tree.rs
- contracts/transfer/tests/wrapper/alice/Cargo.toml
- rusk-abi/CHANGELOG.md
- rusk-abi/Cargo.toml
- rusk-abi/tests/contracts/host_fn/Cargo.toml
> Update contracts to persistence-friendly deps 

- contracts/stake/src/lib.rs
- contracts/stake/src/wasm.rs
- rusk-abi/src/lib.rs
> stake-contract: Move epoch, maturity and validity to the contract definition

- rusk-abi/CHANGELOG.md
- rusk-abi/Cargo.toml
- rusk-abi/src/host.rs
- rusk-abi/src/hosted.rs
- rusk-abi/src/lib.rs
- Add `transfer_address` and `stake_address` methods for hosted
Resolves: #328
> rusk-abi: Add `transfer_contract` method for hosted

- circuits/bid/src/correctness.rs
- circuits/blindbid/src/gadgets.rs
- circuits/blindbid/tests/bid_tests.rs
- circuits/blindbid/tests/tree_assets.rs
- circuits/transfer/src/execute.rs
- circuits/transfer/src/execute/builder.rs
- circuits/transfer/src/execute/input.rs
- circuits/transfer/src/lib.rs
- circuits/transfer/src/send_to_contract_obfuscated.rs
- circuits/transfer/src/send_to_contract_transparent.rs
- circuits/transfer/src/withdraw_from_obfuscated.rs
- contracts/transfer/src/transfer.rs
- contracts/transfer/src/transfer/call.rs
- contracts/transfer/src/transfer/circuits.rs
- contracts/transfer/src/transfer/tree.rs
- contracts/transfer/tests/transfer.rs
- contracts/transfer/tests/wrapper/mod.rs
- macros/code-hasher/src/lib.rs
- rusk-abi/tests/lib.rs
- rusk-profile/src/lib.rs
- rusk/Cargo.toml
- rusk/build.rs
- rusk/src/lib/encoding.rs
- rusk/src/lib/services/blindbid.rs
- rusk/src/lib/services/blindbid/score_gen_handler.rs
- rusk/src/lib/services/blindbid/verify_score_handler.rs
- rusk/src/lib/transaction.rs
- rusk/tests/common/encoding.rs
- test-utils/transfer-wrapper/src/lib.rs
> Cleaning up Rusk code

- contracts/bid/Cargo.toml
- contracts/bid/src/hosted.rs
- contracts/bid/src/hosted/transaction.rs
- contracts/bid/tests/hosted_fns.rs
> Add EXTEND and WITHDRAW tests bor bid-contract

- schema/network.proto
- schema/rusk.proto
> schema: Add proto definition for network service

- schema/network.proto
> Delete optional label in network proto file

- rusk/Cargo.toml
- rusk/src/bin/main.rs
- rusk/src/lib/services.rs
- rusk/src/lib/services/network.rs
- rusk/tests/common/mod.rs
> rusk: Add gRPC service for Network communication

- rusk/Cargo.toml
- rusk/src/bin/main.rs
- rusk/src/lib/services/network.rs
Add kadcast configuration
Include the minimal configuration set required to run both testbed and cluster
Resolves #394
> Update kadcast library to release-0.3

- test-utils/Makefile
- test-utils/transfer-wrapper/Cargo.toml
- test-utils/transfer-wrapper/src/lib.rs
- Upgrade dusk-plonk to 0.9
- Upgrade dusk-poseidon to 0.23.0-rc
- Upgrade phoneix-core to 0.15.0-rc
- Upgrade dusk-pki to 0.9.0-rc
Resolves #406
> test-utils: Reinstate tests into CI

- .github/workflows/dusk_ci.yml
> Enable Clippy in the CI

- rusk/src/lib/services/state.rs
- schema/state.proto
> Add `NodeClient`-defined state service scaffold

- circuits/transfer/Cargo.toml
- contracts/stake/Cargo.toml
- contracts/stake/src/wasm.rs
- contracts/transfer/Cargo.toml
- contracts/transfer/src/wasm/callable.rs
- contracts/transfer/tests/transfer.rs
- contracts/transfer/tests/wrapper/alice/Cargo.toml
- contracts/transfer/tests/wrapper/alice/src/lib.rs
- contracts/transfer/tests/wrapper/bob/Cargo.toml
- contracts/transfer/tests/wrapper/mod.rs
- macros/code-hasher/Cargo.toml
- rusk-abi/Cargo.toml
- rusk-abi/src/hash.rs
- rusk-abi/src/module/hosted.rs
- rusk-abi/tests/contracts/host_fn/Cargo.toml
- rusk-abi/tests/lib.rs
- rusk-profile/Cargo.toml
- rusk/Cargo.toml
- rusk/src/bin/main.rs
- test-utils/transfer-wrapper/Cargo.toml
- test-utils/transfer-wrapper/src/lib.rs
> Updated dependency versions

- rusk/Cargo.toml
- rusk/src/bin/main.rs
- rusk/src/lib/services/network.rs
> rusk: Truncate kadcast test messages

- .github/workflows/dusk_ci.yml
- circuits/transfer/src/send_to_contract_obfuscated.rs
- circuits/transfer/src/send_to_contract_transparent.rs
- contracts/transfer/tests/wrapper/mod.rs
- rusk/src/bin/main.rs
- rusk/tests/common/mod.rs
- Update CI to fails in case of (clippy) warnings
- rusk: Fix (clippy) warnings
- transfer-contract: Fix (clippy) warnings
- transfer-circuits: Fix (clippy) warnings
Resolves: #442
> Fix (clippy) warnings in the code base

- contracts/stake/src/lib.rs
- contracts/stake/src/wasm.rs
> Change stake contract to conform to new spec

- rusk/Cargo.toml
- rusk/default.config.toml
- rusk/src/bin/config.rs
- rusk/src/bin/main.rs
- rusk/src/lib/services/network.rs
- Aggregate CLI args into `rusk::Config`
- Move default configs to `rusk::Config::default()`
- Override config by CLI args
- Update kadcast from 0.3 to 0.4-rc
Resolves #449
> Add TOML config

- contracts/transfer/src/transfer.rs
- contracts/transfer/src/transfer/call.rs
- contracts/transfer/src/wasm/callable.rs
- contracts/transfer/src/wasm/internal.rs
- contracts/transfer/tests/wrapper/mod.rs
> transfer-contract: Validate tx hash

- contracts/stake/Cargo.toml
- contracts/stake/src/lib.rs
- contracts/stake/src/wasm.rs
- rusk/Cargo.toml
- rusk/src/lib/error.rs
- rusk/src/lib/lib.rs
- rusk/src/lib/services/state.rs
- rusk/src/lib/state.rs
- rusk/tests/common/mod.rs
- rusk/tests/services/state_service.rs
- schema/state.proto
> Add a service to get the stake from a public key

- rusk/src/bin/config.rs
- rusk/src/bin/config/grpc.rs
- rusk/src/bin/config/kadcast.rs
- rusk/src/bin/config/wallet.rs
- rusk/src/bin/main.rs
This is prerequisite for internal-wallet PR
See also #470
> rusk: Extend the configuration to include rusk-wallet

- rusk-abi/Cargo.toml
- rusk-abi/src/module.rs
- rusk-abi/src/module/host.rs
- rusk-abi/src/module/hosted.rs
- rusk-abi/tests/contracts/host_fn/Cargo.toml
- rusk-abi/tests/contracts/host_fn/src/lib.rs
- rusk-abi/tests/lib.rs
> rusk-abi: Add BLS signature verification

- rusk-wallet/Cargo.toml
- rusk-wallet/src/lib/crypto.rs
- rusk-wallet/src/lib/errors.rs
- rusk-wallet/src/lib/prompt.rs
- rusk-wallet/src/lib/store.rs
- rusk-wallet/src/main.rs
Functions `from_file()` and `save()` in `store.rs` should be checked for consistency with the last changes.
> Add encrypt_seed and decrypt_seed

- rusk/src/lib/services.rs
- rusk/src/lib/services/network.rs
- rusk/src/lib/services/state.rs
This is a followup of https://github.com/dusk-network/rusk/pull/454#discussion_r792444604
See also dusk-network/dusk-blockchain#1274
> rusk: Serialize tx according to network format

- rusk/src/lib/services/network.rs
- rusk/src/lib/services/state.rs
- schema/state.proto
- schema/transaction.proto
> Change ExecuteStateTransition response to include tx_hash

- rusk/src/lib/services/network.rs
> Fix tx encoding before Network propagation

- rusk/src/lib/services/network.rs
- rusk/tests/services/transactions.rs
Edit transaction tests to check that a local peer receive the correct message
Resolves #526
> rusk: Fix transaction encoding over the network

- rusk/src/lib/encoding.rs
- rusk/src/lib/services/state.rs
- schema/transaction.proto
> Add gas_spent to ExecutedTransaction grpc message

- rusk-wallet/CHANGELOG.md
- rusk-wallet/Cargo.toml
- rusk-wallet/README.md
- rusk-wallet/src/lib/crypto.rs
- rusk-wallet/src/lib/error.rs
- rusk-wallet/src/lib/store.rs
- rusk-wallet/src/main.rs
- Use UDS transport by default (See also: #520)
- Encode file with version tag (See also: #524)
- Add a README (See also: #514)
> wallet: Release 0.2

- schema/state.proto
> Include ExecutedTransactions in the Accept/Finalize response

- rusk-wallet/Cargo.toml
- rusk-wallet/src/lib/clients.rs
> wallet: Update to wallet-core 0.9

- rusk-wallet/CHANGELOG.md
- rusk-wallet/Cargo.toml
- rusk-wallet/src/lib/prompt.rs
- rusk-wallet/src/lib/wallet.rs
- rusk-wallet/src/main.rs
- Added feedback for available balance when creating transactions in interactive mode
- Fixed a bug that paniced when attempting to connect to a non-existent UDS socket
Resolves #547
> wallet: Release 0.2.2

- contracts/transfer/src/wasm/internal.rs
- rusk-wallet/src/lib/mod.rs
- rusk-wallet/src/lib/prompt.rs
- rusk-wallet/src/lib/wallet.rs
Check that inputted Dusks are convertible to uDusk
Resolves #561
> Check the validity of wallet input

- rusk/src/lib/services/state.rs
- rusk/src/lib/state.rs
Computes dusk spent by each transaction and sums it all up, passing it
to coinbase methods accordingly.
Resolves: #592
> rusk: fix coinbase value calculation

- rusk/src/lib/services/state.rs
Transactions returned from `execute_state_transition` are now guaranteed
to have a `gas_limit` smaller than the block gas limit.
Resolves: #591
> rusk: add TX filter on block gas limit

- rusk/src/lib/services/state.rs
> rusk: refactor and correct state transition logic

- rusk-wallet/CHANGELOG.md
- rusk-wallet/README.md
- rusk-wallet/src/lib/prompt.rs
- rusk-wallet/src/lib/wallet.rs
- rusk-wallet/src/main.rs
> rusk-wallet: Add Get Stake command

- rusk-wallet/src/main.rs
> rusk-wallet: auto derive version from Cargo.toml

- rusk-wallet/src/lib/clients.rs
- rusk-wallet/src/main.rs
> rusk-wallet: preverify before proof and propagate

- rusk/src/lib/services/network.rs
- rusk/tests/services/transfer.rs
> Add protocol version to network propagation

- Cargo.toml
The contracts and the user interface will benefit from having overflow
checks.
These might result in inconsistent states depending on user input.
Resolves #645
> Enable overflow checks

- rusk-wallet/src/lib/error.rs
- rusk-wallet/src/lib/wallet.rs
> wallet: Prevent users not running a local rusk instance from staking

- rusk-wallet/CHANGELOG.md
- rusk-wallet/Cargo.toml
- rusk-wallet/src/lib/clients.rs
- rusk-wallet/src/lib/config.rs
- rusk-wallet/src/lib/error.rs
- rusk-wallet/src/lib/gql.rs
- rusk-wallet/src/lib/mod.rs
- rusk-wallet/src/lib/prompt.rs
- rusk-wallet/src/main.rs
> wallet: Add option to wait for transaction confirmation

- rusk/src/lib/services/network.rs
See also dusk-network/dusk-blockchain#1353
> rusk: Fill the txhash while propagating

- rusk-schema/protos/state.proto
- rusk/src/lib/services/state.rs
> rusk-schema: Enable VST call to return state_root on success

- rusk/tests/services/transfer.rs
* Add test to generate empty block
* Add test to partial notes retrieval
> rusk: Improve tests

- rusk-recovery/src/provisioners.rs
> Lower pre staked provisioners to 5

- rusk-profile/src/lib.rs
- rusk/Cargo.toml
- rusk/src/bin/config.rs
- rusk/src/bin/ephemeral.rs
- rusk/src/bin/main.rs
> rusk: implement ephemeral state root

- rusk-recovery/Cargo.toml
- rusk-recovery/src/bin/state.rs
- rusk-recovery/src/state.rs
- rusk-recovery/src/state/zip.rs
> rusk-recovery: implement state output file

- rusk-recovery/src/bin/state.rs
> rusk-recovery: add `init` args

- Makefile
This is fixing also the broken CI on github
> Remove unused `state` recipie from the Makefile

- rusk-recovery/src/keys.rs
> rusk-recovery: initialize PUB_PARAMS

- node/Cargo.toml
- node/src/bin/main.rs
- node/src/chain/mod.rs
- node/src/data/mod.rs
- node/src/database/mod.rs
- node/src/database/rocksdb.rs
- node/src/lib.rs
- node/src/mempool/mod.rs
- node/src/network/frame.rs
- node/src/network/mod.rs
- node/src/utils/mod.rs
> Design n-tier architecture to facilitate node development

- Makefile
> Enable node crate build and test in rusk Makefile

- contracts/governance/src/collection.rs
- contracts/governance/src/governance.rs
- contracts/governance/src/lib.rs
- contracts/governance/src/wasm/bridge.rs
* Remove allowlist
* Change `Default` to be running
Resolves #838
> governance-contract: Remove allowlist

- rusk/Cargo.toml
> rusk: fix compilation by forcing `async-stream` to `0.3.3`

- node/Cargo.toml
- node/default.config.toml
- node/src/bin/config.rs
- node/src/bin/config/kadcast.rs
- node/src/bin/main.rs
- node/src/bin/version.rs
- node/src/build.rs
- node/src/database/mod.rs
- node/src/database/rocksdb.rs
- node/src/lib.rs
- node/src/mempool/mod.rs
- node/src/network/mod.rs
> node: Add TOML configuration

- rusk-recovery/Cargo.toml
- rusk-recovery/config/example_gov.toml
- rusk-recovery/src/state.rs
- rusk-recovery/src/state/snapshot.rs
- rusk-recovery/src/state/snapshot/acl.rs
- rusk-recovery/src/state/snapshot/governance.rs
- rusk-recovery/src/state/snapshot/wrapper.rs
> rusk-recovery-state: support governance contract

- node-data/src/bls.rs
- node-data/src/ledger.rs
- node-data/src/message.rs
> node-data: Add support for read/write a transaction wire message

- node/Cargo.toml
- node/Makefile
- node/src/bin/config.rs
- node/src/bin/main.rs
- node/testbed.sh
fixes #868 
NB: Base branch is fix-866
> Add support for tokio_console

- rusk-profile/src/lib.rs
> rusk-profile: change `crs` hash

- contracts/stake/src/state.rs
This is a porting of the previous implementation #769
Resolves #858
> stake-contract: remove allowlist field

- node-data/src/message.rs
fixes #889 
This PR is a prerequisite to merging #873
> node-data: Impl GetCandidate, GetMempool, GetInv, GetBlocks, GetData and CandidateResp

- consensus/Cargo.toml
- consensus/src/merkle.rs
> consensus: upgrade merkle dependency to `0.4.0`

- node/src/chain/genesis.rs
- node/src/chain/mod.rs
- node/src/database/mod.rs
- node/src/database/rocksdb.rs
> Reload most recent block from persisted ledger state on startup

- rusk/Cargo.toml
- rusk/src/bin/main.rs
- rusk/src/lib/lib.rs
- rusk/src/lib/ws.rs
The branch was never supposed to be merged onto `master`, therefore here's a revert.
> Revert "rusk: initial impl of request-response queries"

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
> Persist both block header and block spent transactions after VM update

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fallback.rs
- node/src/chain/fsm.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
- node/src/vm.rs
- rusk/src/lib/vm.rs
> Introduce fallback procedure

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fallback.rs
- rusk/src/bin/main.rs
- rusk/src/lib/error.rs
- rusk/src/lib/lib.rs
- rusk/src/lib/vm.rs
> Detect inconsistency between ledger and vm states

- rusk/src/lib/lib.rs
- rusk/src/lib/vm.rs
- rusk/tests/common/state.rs
> rusk: change `consistency_check` to `Option`

- contracts/stake/tests/stake.rs
- contracts/transfer/src/lib.rs
- contracts/transfer/src/state.rs
- contracts/transfer/src/tree.rs
- contracts/transfer/tests/transfer.rs
- rusk/src/lib/lib.rs
- rusk/tests/common/keys.rs
- rusk/tests/common/state.rs
- rusk/tests/rusk-state.rs
- rusk/tests/services/gas_behavior.rs
- rusk/tests/services/multi_transfer.rs
- rusk/tests/services/stake.rs
- rusk/tests/services/transfer.rs
> Implement feeding notes from the transfer contract

- contracts/stake/src/lib.rs
- contracts/stake/src/state.rs
- rusk/src/lib/lib.rs
> Implement feeding stakes from the stake contract

- node-data/Cargo.toml
- node-data/src/ledger.rs
- node-data/src/ledger/graphql.rs
- rusk/Cargo.toml
- rusk/src/lib/http/chain.rs
- rusk/src/lib/http/chain/graphql.rs
- rusk/src/lib/http/chain/graphql/block.rs
- rusk/src/lib/http/chain/graphql/tx.rs
- rusk/src/lib/http/event.rs
- rusk/src/lib/http/rusk.rs
* add support for gql variables
* add various gql queries
> Change gql dep to `async-graphql`

- consensus/example/mocks.rs
- consensus/src/commons.rs
- consensus/src/contract_state.rs
- consensus/src/execution_ctx.rs
- consensus/src/firststep/handler.rs
- consensus/src/msg_handler.rs
- consensus/src/selection/block_generator.rs
- consensus/src/selection/handler.rs
- node/src/chain/consensus.rs
> Resolve compatibility issues  

- node-data/src/ledger.rs
- node/src/chain/consensus.rs
- node/src/lib.rs
- node/src/mempool.rs
- node/src/network.rs
- rusk/Cargo.toml
- rusk/src/bin/main.rs
- rusk/src/lib/http.rs
- rusk/src/lib/http/chain.rs
- rusk/src/lib/http/event.rs
- rusk/src/lib/http/rusk.rs
- rusk/src/lib/prover.rs
- rusk/tests/common/state.rs
Implement missing http handlers for waller
> Expose missing http handlers

- consensus/src/commons.rs
- consensus/src/selection/block_generator.rs
- rusk/src/lib/http/event.rs
- rusk/src/lib/vm.rs
- Change VST to use candidate gas_limit
- Change BlockGenerator to produce the correct gas_limit value
> Fix block gas limit

- consensus/src/aggregator.rs
- consensus/src/agreement/accumulator.rs
- consensus/src/agreement/aggr_agreement.rs
- consensus/src/agreement/step.rs
- consensus/src/commons.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/firststep/step.rs
- consensus/src/msg_handler.rs
- consensus/src/phase.rs
- consensus/src/secondstep/step.rs
- consensus/src/selection/block_generator.rs
- consensus/src/selection/step.rs
- consensus/src/user/committee.rs
- node-data/src/message.rs
- node/Cargo.toml
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
- node/src/chain/fsm.rs
- node/src/databroker.rs
- node/src/lib.rs
- node/src/network.rs
- rusk-recovery/config/testnet.toml
- rusk/src/bin/config.rs
- rusk/src/bin/ephemeral.rs
- rusk/src/bin/main.rs
> consensus: Improve debug-level logging 

- consensus/src/agreement/accumulator.rs
- consensus/src/commons.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/firststep/step.rs
- consensus/src/secondstep/step.rs
- node/src/chain/consensus.rs
fixes #987
This branch was deployed and tested on a cluster of 30 provisioners. There are no occurrences of `VST failure/mismatch` error for 22K rounds.
See also: cluster05
> Mitigate the occurrences of a false alarm  'VST failure' error

- consensus/src/aggregator.rs
- consensus/src/agreement/accumulator.rs
- consensus/src/agreement/aggr_agreement.rs
- consensus/src/agreement/verifiers.rs
- consensus/src/commons.rs
- consensus/src/firststep/handler.rs
- consensus/src/secondstep/handler.rs
- consensus/src/selection/block_generator.rs
- consensus/src/selection/handler.rs
- node-data/src/encoding.rs
- node-data/src/ledger.rs
- node-data/src/message.rs
- Rename signed_hash to signature
- Remove a duplicate of marshal_signable_vote
-  #1021 
- Print signature for both reduction vote and ratification vote.
> Refactor a bit node-data

- consensus/src/config.rs
- consensus/src/execution_ctx.rs
- node/src/chain/acceptor.rs
> Broadcast any valid msg from future_msg queue

- rusk/src/lib/http/chain.rs
- rusk/src/lib/http/chain/graphql.rs
- rusk/src/lib/http/chain/graphql/data.rs
- rusk/src/lib/http/chain/graphql/tx.rs
- Add mempool APIs #1035 
- Return SDL if not query is specified #1036
> Mempool API

- Makefile
- circuits/Makefile
- contracts/Makefile
- contracts/governance/Makefile
- contracts/license/Makefile
- contracts/stake/Makefile
- contracts/transfer/Makefile
- macros/Makefile
- macros/code-hasher/Makefile
> Change default Makefile target to 'all'

- rusk-abi/CHANGELOG.md
> rusk-abi: Update changelog

- README.md
> Update README with specs, license, build step & prereqs

- Dockerfile
> Update Dockerfile with ARM targets

- rusk-abi/CHANGELOG.md
- rusk-abi/Cargo.toml
> Upgrade to `piecrust@0.10`

- contracts/license/build.rs
- contracts/license/src/lib.rs
- contracts/transfer/build.rs
- contracts/transfer/src/circuits.rs
- rusk-abi/tests/lib.rs
> Add circuit ID environment variable to fetch verifier data

- Dockerfile
> Fix file path error in Dockerfile

- consensus/src/aggregator.rs
- consensus/tests/sortition.rs
- rusk/tests/config/stake.toml
- rusk/tests/services/stake.rs
I didn't change the DUSK key (the one for accruing the fee) yet, since the wallet-cli is not been updated yet
> Adapt tests

- rusk/Cargo.toml
- rusk/build.rs
- rusk/src/bin/args.rs
- rusk/src/bin/main.rs
- rusk/src/lib/http.rs
- rusk/src/lib/http/event.rs
- rusk/src/lib/lib.rs
- rusk/src/lib/version.rs
> Implement HTTP version Handshake

- Makefile
- rusk-profile/src/lib.rs
- rusk-recovery/src/keys.rs
- rusk-recovery/src/state/snapshot.rs
> Fix crs cache mechanism

- node/src/chain/fsm.rs
fixes #1127
- Enable consensus task when a block is accepted in OutOfSync state
- Try to accept next block after successful fallback execution
- Filter out a blacklisted block in both inSync and OutSync states
- Blacklist block from the wrong branch
- Reset expiry_time only if we receive a valid block from the syncing peer
- Limit size of outSync pool of block
> node: Apply improvements in fallback procedure

- consensus/example/consensus_service.rs
- consensus/example/main.rs
- consensus/src/agreement/aggr_agreement.rs
- consensus/src/agreement/step.rs
- consensus/src/commons.rs
- consensus/src/execution_ctx.rs
- consensus/src/selection/block_generator.rs
- node-data/src/ledger.rs
- node-data/src/message.rs
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
> Add prev_block_cert to ledger::Header

- consensus/src/commons.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/selection/block_generator.rs
- consensus/src/step_votes_reg.rs
- node-data/src/ledger.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
> Start iteration from 0 instead of 1

- contracts/license/Makefile
- contracts/stake/Makefile
- contracts/stake/src/state.rs
- contracts/transfer/Makefile
- contracts/transfer/src/state.rs
Add clippy check for the three genesis contracts
Resolves #1140
> Add Clippy for contracts

- rusk-prover/Cargo.toml
- rusk-prover/src/prover.rs
- rusk-prover/src/prover/execute.rs
- rusk-prover/src/prover/stco.rs
- rusk-prover/src/prover/stct.rs
- rusk-prover/src/prover/wfco.rs
- rusk-prover/src/prover/wfct.rs
- rusk/Cargo.toml
- rusk/tests/services/transfer.rs
**rusk-prover:** 
- add `no_random` feature flag
**rusk:** 
- use rusk-prover `no_random` for tests
Resolves #1141
> Deterministic prover

- consensus/example/consensus_service.rs
- consensus/example/main.rs
- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/consensus.rs
- consensus/src/firststep/step.rs
- consensus/src/phase.rs
- consensus/src/secondstep/step.rs
- consensus/src/user/committee.rs
- consensus/src/user/provisioners.rs
- consensus/src/user/stake.rs
- consensus/tests/sortition.rs
- node/benches/accept.rs
- node/src/chain/acceptor.rs
- node/src/chain/fallback.rs
- rusk/src/lib/vm.rs
> Refactor committee

- consensus/src/config.rs
- consensus/src/user/committee.rs
> consensus: add nil_quorum

- Dockerfile
- scripts/setup-compiler.sh
`docker run -v ./custom_state.toml:/opt/rusk/state.toml rusk`
Resolves #1194
> docker: load custom genesis.toml

- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/execution_ctx.rs
- consensus/src/phase.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/proposal/step.rs
- consensus/src/quorum/task.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/ratification/step.rs
- consensus/src/user/committee.rs
- consensus/src/user/provisioners.rs
- consensus/src/user/sortition.rs
- consensus/src/validation/step.rs
- consensus/tests/sortition.rs
- node-data/src/bls.rs
- node-data/src/message.rs
- node/benches/accept.rs
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
- node/src/database/rocksdb.rs
- node/src/vm.rs
- rusk/src/lib/vm.rs
- rusk/tests/common/state.rs
> Exclude block generator from voting committee

- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/execution_ctx.rs
- consensus/src/ratification/handler.rs
- consensus/src/ratification/step.rs
- consensus/src/validation/handler.rs
- consensus/src/validation/step.rs
- node-data/src/encoding.rs
- node-data/src/message.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
> Transform Second Reduction into Ratification

- consensus/src/commons.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/msg_handler.rs
- consensus/src/phase.rs
- consensus/src/proposal/handler.rs
- consensus/src/proposal/step.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/ratification/handler.rs
- consensus/src/validation/handler.rs
- consensus/src/validation/step.rs
resolves #1202 
resolves #1169
> Verify step votes in validation output on collecting a Ratification msg

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
> Stop consensus while syncing.  Restart it on event of a failure

- consensus/src/config.rs
- node/src/chain/acceptor.rs
> node: Add rolling finality

- contracts/stake/Cargo.toml
- contracts/transfer/Cargo.toml
- contracts/transfer/src/state.rs
- rusk-abi/Cargo.toml
- rusk-recovery/CHANGELOG.md
- rusk-recovery/Cargo.toml
- rusk-recovery/src/state.rs
Removed phoenix-core dependency from rusk-recovery - implements #1139
> rusk-recovery: removed phoenix-core dependency

- node/src/chain.rs
- node/src/chain/fsm.rs
> Recover consensus on an event of timed out sync-up procedure

- node/src/database.rs
- node/src/database/rocksdb.rs
> node: add `get_txs_hashes_sorted_by_fee`

- node/src/database/rocksdb.rs
- rusk/CHANGELOG.md
- rusk/src/lib/http/chain.rs
> Add gas price API

- node-data/src/message.rs
- node/src/chain/fsm.rs
- node/src/databroker.rs
> node: Verify peer before switching to Syncing mode

- contracts/stake-types/src/stake.rs
- node/src/chain/acceptor.rs
> stake-contract-types: change maturity to 1 epoch

- node/benches/accept.rs
- fix bench to check verify_block_cert result
- fix verify_block_cert bench to exclude generator
> Fix node bench

- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/config.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/msg_handler.rs
- consensus/src/phase.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/proposal/handler.rs
- consensus/src/proposal/step.rs
- consensus/src/queue.rs
- consensus/src/quorum/task.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/ratification/handler.rs
- consensus/src/ratification/step.rs
- consensus/src/step_votes_reg.rs
- consensus/src/user/provisioners.rs
- consensus/src/user/sortition.rs
- consensus/src/validation/handler.rs
- consensus/src/validation/step.rs
- consensus/tests/sortition.rs
- node-data/src/lib.rs
- node-data/src/message.rs
- node/benches/accept.rs
- node/src/chain/acceptor.rs
> consensus: Increase iterations to 255

- consensus/src/aggregator.rs
- consensus/src/user/sortition.rs
> consensus: remove `round` from sortition hash

- consensus/src/commons.rs
- consensus/src/proposal/block_generator.rs
- node-data/src/ledger.rs
- node/src/chain/acceptor.rs
- rusk/src/lib/http/chain/graphql/data.rs
> node: remove timestamp validation

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
- rusk/src/lib/http/chain/graphql.rs
- rusk/src/lib/http/chain/graphql/block.rs
- rusk/src/lib/http/chain/graphql/tx.rs
> Improve metadata records in RocksDB

- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/execution_ctx.rs
- consensus/src/iteration_ctx.rs
- consensus/src/lib.rs
- consensus/src/msg_handler.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/proposal/handler.rs
- consensus/src/proposal/step.rs
- consensus/src/quorum/task.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/ratification/handler.rs
- consensus/src/ratification/step.rs
- consensus/src/step_votes_reg.rs
- consensus/src/validation/handler.rs
- consensus/src/validation/step.rs
- node-data/src/encoding.rs
- node-data/src/ledger.rs
- node-data/src/lib.rs
- node-data/src/message.rs
- node/benches/accept.rs
- node/src/chain.rs
- node/src/chain/consensus.rs
- node/src/chain/header_validation.rs
- node/src/database/rocksdb.rs
- node/src/databroker.rs
- node/src/network.rs
- rusk/benches/block_ingestion.rs
- rusk/src/lib/http/chain.rs
- rusk/src/lib/http/chain/graphql/data.rs
> consensus: add support for `Invalid` vote

- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/config.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/iteration_ctx.rs
- consensus/src/operations.rs
- consensus/src/phase.rs
- node-data/src/lib.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
- node/src/chain/metrics.rs
- node/src/database/rocksdb.rs
- node/testbed.sh
> Adjust config parameters of adaptive timeout

- consensus/src/execution_ctx.rs
- consensus/src/phase.rs
> consensus: Report elapsed time on successful step execution only

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/dusk/components/Mnemonic/Mnemonic.svelte
- web-wallet/src/lib/dusk/components/__tests__/Mnemonic.spec.js
- web-wallet/src/lib/dusk/components/__tests__/__snapshots__/Mnemonic.spec.js.snap
- web-wallet/src/style/dusk-components/mnemonic.css
Resolves #1290
The implemented design has been agreed on with @laremas.
> web-wallet: Allow undo of words (Mnemonic)

- web-wallet/CHANGELOG.md
- web-wallet/src/style/dusk-components/words.css
> web-wallet: Fix Seed Phrase words sizes

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/style/dusk-components/tooltip.css
- web-wallet/src/style/dusk/colors.css
- web-wallet/src/style/dusk/language.css
> web-wallet: Fix error tooltip appearance

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/dusk/http/__tests__/failureToRejection.spec.js
- web-wallet/src/lib/dusk/http/failureToRejection.js
- web-wallet/src/lib/dusk/http/index.js
- web-wallet/src/routes/(app)/dashboard/+layout.js
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
> web-wallet: Missing error handling when querying the quote API

- Makefile
- rusk/Makefile
> Fix `make run`

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/Transactions.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Transactions.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/+page.svelte
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/page.spec.js
> web-wallet: Fix Transactions table design

- web-wallet/CHANGELOG.md
- web-wallet/package.json
> web-wallet: Change `package.json` fields to reflect repo change

- web-wallet/CHANGELOG.md
> web-wallet: Fix Changelog to point to issues

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/GasControls/GasControls.svelte
- web-wallet/src/lib/components/__tests__/GasControls.spec.js
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/page.spec.js
> web-wallet: add gas settings validation to settings page

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/GasSettings/GasSettings.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/containers/TransferContract/TransferContract.svelte
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/routes/(app)/dashboard/+page.svelte
> web-wallet:refactor wallet store to receive gas price and limit

- .github/workflows/webwallet_ci.yml
- web-wallet/CHANGELOG.md
> CI: Update to latest actions checkout

- README.md
> Add rust setup and prover node info to README

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/navigation/__test__/logout.spec.js
- web-wallet/src/lib/navigation/index.js
- web-wallet/src/lib/navigation/logout.js
- web-wallet/src/routes/(app)/+layout.svelte
- web-wallet/src/routes/(app)/__tests__/layout.spec.js
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/forced-logout/+page.svelte
- web-wallet/src/routes/(welcome)/forced-logout/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/forced-logout/__tests__/page.spec.js
- web-wallet/src/routes/__tests__/page.spec.js
> web-wallet: Add forced log out on inactive tabs

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/GasControls/GasControls.svelte
- web-wallet/src/lib/components/GasSettings/GasSettings.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/GasControls.spec.js
- web-wallet/src/lib/components/__tests__/GasSettings.spec.js
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/routes/(app)/settings/+page.svelte
> web-wallet: block send and stake if invalid gas settings

- consensus/src/proposal/step.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/step_votes_reg.rs
- node-data/src/bls.rs
- node-data/src/ledger.rs
- node-data/src/message.rs
- node/Makefile
- node/benches/accept.rs
- node/src/chain/acceptor.rs
- node/src/chain/header_validation.rs
- rusk/Cargo.toml
- rusk/Makefile
- rusk/tests/common/state.rs
> node: handle failed quorums to produce attested block

- node/src/chain/fsm.rs
fixes #1382 
Stats after the fix:
```
Setup:
cluster_name: cluster1302
eligible_provisioners: 30
Metrics:
final_blocks: 23042 out of 24475
nonfinal_blocks: 1433 out of 24475
average_block_Time: 3,02578 sec
blocks_with_time_above_11sec: 23
fallbacked_blocks: [2-5]
nodes_on_fork: 0
```
> node: Broadcast message Block after any successful try_accept_block call

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/dusk/components/Card/Card.svelte
- web-wallet/src/lib/stores/settingsStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/style/dusk-components/card.css
> web-wallet: Add Staking Warning

- circuits/license/Cargo.toml
- circuits/transfer/CHANGELOG.md
- circuits/transfer/Cargo.toml
- consensus/CHANGELOG.md
- consensus/Cargo.toml
- contracts/license/CHANGELOG.md
- contracts/license/Cargo.toml
- contracts/stake/CHANGELOG.md
- contracts/stake/Cargo.toml
- contracts/transfer/CHANGELOG.md
- contracts/transfer/Cargo.toml
- contracts/transfer/src/error.rs
- contracts/transfer/src/state.rs
- node-data/CHANGELOG.md
- node-data/Cargo.toml
- node-data/src/bls.rs
- rusk-abi/CHANGELOG.md
- rusk-abi/Cargo.toml
- rusk-abi/src/lib.rs
- rusk/CHANGELOG.md
- rusk/Cargo.toml
- rusk/src/lib/chain/vm/query.rs
- rusk/tests/rusk-state.rs
- rust-toolchain.toml
support bytecheck-secured argument passing
implements #1371
> support bytecheck-secured argument passing

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ContractOperations/ContractOperations.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/ContractOperations.spec.js
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/ContractOperations.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/contracts/contract-descriptors.js
- web-wallet/src/lib/contracts/contracts.d.ts
> web-wallet: Change "withdraw stake" label to "unstake"

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
> web-wallet: Fix wizard progression on Stake flow

- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
- node/src/chain/genesis.rs
- node/src/chain/header_validation.rs
> node: Make sure seed value in candidate block is valid

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/lib/navigation/__test__/logout.spec.js
- web-wallet/src/lib/navigation/logout.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
> web-wallet: Add abortable sync

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ExistingWalletNotice/ExistingWalletNotice.svelte
- web-wallet/src/lib/components/index.js
- web-wallet/src/lib/wallet/initializeWallet.js
- web-wallet/src/routes/(welcome)/login/+page.svelte
- web-wallet/src/routes/(welcome)/login/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/setup/create/+page.svelte
- web-wallet/src/routes/(welcome)/setup/restore/+page.svelte
> web-wallet: Add Existing Wallet Notice

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
> web-wallet: Fix Stake button is always disabled

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Transactions.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Fix Transactions table remains hidden

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/login/__tests__/page.spec.js
> web-wallet: Update login flow tests

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/login/+page.svelte
- web-wallet/src/routes/(welcome)/login/__tests__/page.spec.js
> web-wallet: Fix can't unlock the wallet with upper case words

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/setup/restore/MnemonicAuthenticate.svelte
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js
> Fix restore flow allowing a user to log in with an invalid mnemonic

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
> web-wallet: Remove the use of `checkValidity()` from the Send flow

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
> web-wallet: Fix version number and changelog for 15 Feb release

- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
Currently, a block propagation in the network may be delayed significantly due to a call to `vm::get_provisioners`. Until the bottleneck is optimized, we can simply propagate the block before the specified vm call.
> Broadcast a valid block before the `get_provisioners` call

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/login/__tests__/page.spec.js
> web-wallet: Fix typo in welcome/tests/page.spec.js

- web-wallet/CHANGELOG.md
- web-wallet/src/app.html
- web-wallet/src/routes/(welcome)/setup/+page.svelte
- web-wallet/src/routes/(welcome)/setup/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/vite.config.js
> web-wallet: Add visible version, commit hash and build date

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Transactions/Transactions.svelte
> web-wallet: Fix missing whitespace no Transactions

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
- Add Create Wallet flow tests [#1443]
- Add visible version, commit hash and build date [#1441]
- Add Address validation (Transfer flow) [#1377]
- Change Get Quote API Endpoint to env variable [#1311]
- Remove the use of `checkValidity()` in Send and Stake flow amounts validity checks [#1391]
- Fix typo in routes/welcome/\_\_tests\_\_/page.spec.js [#1445]
- Fix missing whitespace when Transaction list is empty [#1460]
> web-wallet: Release 0.3.0

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/setup/restore/MnemonicAuthenticate.svelte
Resolves #1470
**Visuals:**
https://github.com/dusk-network/rusk/assets/34094428/8992a07f-9df3-4a02-b81e-4df295766d0f
> web-wallet: Remove extraneous block (MnemonicAuth)

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/__tests__/OperationResult.spec.js
> web-wallet: Fix mismatch between param and typedef

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Refactor beta notice as constant

- node/src/chain/consensus.rs
> node: remove discarded txs from mempool

- consensus/src/execution_ctx.rs
- consensus/src/quorum/task.rs
- node-data/src/message.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
- node/src/chain/fsm.rs
- node/src/databroker.rs
- node/src/mempool.rs
- node/src/network.rs
> Any message that cannot be validated should be repropagated

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
- node/src/databroker.rs
- node/src/mempool.rs
- node/src/network.rs
> node: Enqueue consensus messages for up to N rounds ahead

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/vite-setup.js
- web-wallet/vite.config.js
- Add `vitest-canvas-mock` dependency to replace `canvas`
- Remove `canvas` dependency
Resolves #1506
> web-wallet: Replace `canvas` with `vitest-canvas-mock`

- .github/workflows/webwallet_ci.yml
- web-wallet/CHANGELOG.md
- web-wallet/package.json
> web-wallet: Add format check to CI and `checks` script

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Balance/Balance.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Balance.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/page.spec.js
- web-wallet/src/style/dusk-components/balance.css
> web-wallet: Fix layout shift (Balance component)

- contracts/stake-types/src/lib.rs
- contracts/stake/CHANGELOG.md
- contracts/stake/Cargo.toml
- contracts/stake/src/lib.rs
- contracts/stake/src/state.rs
- contracts/stake/tests/common/assert.rs
- contracts/stake/tests/common/init.rs
- contracts/stake/tests/common/mod.rs
- contracts/stake/tests/common/utils.rs
- contracts/stake/tests/events.rs
- contracts/stake/tests/stake.rs
Added events emitting in the stake contract with tests
Implements issue #1472
> Added events emitting in the stake contract with tests

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/contracts/contract-descriptors.js
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Add message for no contracts enabled

- consensus/README.md
- web-wallet/README.md
- web-wallet/src/lib/dusk/components/__tests__/Card.spec.js
- web-wallet/src/lib/dusk/components/__tests__/__snapshots__/Card.spec.js.snap
Resolves https://github.com/dusk-network/rusk/issues/1511
> web-wallet: Fix typos

- web-wallet/CHANGELOG.md
- web-wallet/src/style/main.css
> web-wallet: remove box-shadow from interactable components

- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/vite.config.js
> web-wallet: change vitest coverage provider to istanbul

- web-wallet/src/style/main.css
> web-wallet: fix duplicate border on interactable elements

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Update copy on reset while syncing

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ExistingWalletNotice/ExistingWalletNotice.svelte
- web-wallet/src/lib/dusk/components/Mnemonic/Mnemonic.svelte
- web-wallet/src/lib/stores/index.js
- web-wallet/src/lib/stores/mnemonicPhraseResetStore.js
- web-wallet/src/routes/(welcome)/login/+page.svelte
- web-wallet/src/routes/(welcome)/login/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/login/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/+page.svelte
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js
Resolves #1535, Resolves #1533
> web-wallet: Trigger Restore flow on new wallet

- consensus/src/consensus.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
> consensus: Avoid propagating blocks when achieving a valid quorum

- web-wallet/CHANGELOG.md
- web-wallet/src/style/dusk-components/error-details.css
> web-wallet: fix error message overflowing in ErrorDetails

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/page.spec.js
> web-wallet: Clear login info on Wallet reset

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/Transactions.spec.js
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/+page.svelte
> web-wallet: data load and sync UI appearing at the same time

- .github/workflows/rusk_ci.yml
> update CI workflows

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/__tests__/__snapshots__/AppAnchorButton.spec.js.snap
- web-wallet/src/lib/dusk/components/AnchorButton/AnchorButton.svelte
- web-wallet/src/lib/dusk/components/Button/Button.svelte
- web-wallet/src/lib/dusk/components/__tests__/__snapshots__/AnchorButton.spec.js.snap
- web-wallet/src/lib/dusk/components/__tests__/__snapshots__/Button.spec.js.snap
- web-wallet/src/lib/dusk/components/dusk.components.d.ts
- web-wallet/src/lib/stores/__tests__/settingsStore.spec.js
- web-wallet/src/lib/stores/settingsStore.js
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/+page.svelte
- web-wallet/src/routes/(welcome)/setup/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/+layout.svelte
- web-wallet/src/routes/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/__tests__/layout.spec.js
- web-wallet/src/style/dusk-components/anchor.css
- web-wallet/src/style/dusk-components/badge.css
- web-wallet/src/style/dusk-components/balance.css
- web-wallet/src/style/dusk-components/card.css
- web-wallet/src/style/dusk-components/textbox.css
- web-wallet/src/style/dusk-components/tooltip.css
- web-wallet/src/style/dusk/language.css
- Add dark theme (style, controls and logic)
- Add main layout tests
- Add settings store tests
Resolves #1466
> web-wallet: Add dark theme

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/AddressPicker/AddressPicker.svelte
> web-wallet: Fix keydown behavior (AddressPicker)

- consensus/src/config.rs
- node/src/chain/genesis.rs
* Increase EMERGENCY_ITERATIONS to 50
* Increase MIN_STEP_TIMEOUT to 7secs
* Increase MAX_STEP_TIMEOUT to 40secs
* Change genesis timestamp to `Mon Mar 25 2024 11:00:00 GMT+0000`
> Nocturne tuning

- explorer/package-lock.json
- explorer/src/routes/+layout.svelte
- explorer/src/routes/+page.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/+page.svelte
- explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/+page.svelte
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/+page.svelte
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/+page.svelte
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/style/main.css
> explorer: scaffold page layouts

- web-wallet/CHANGELOG.md
- web-wallet/src/style/dusk/language.css
- web-wallet/src/style/main.css
> web-wallet: Change ribbon's label color

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/AddressPicker/AddressPicker.css
- web-wallet/src/lib/components/AddressPicker/AddressPicker.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/AddressPicker.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/style/dusk-components/button.css
Resolves #1591
https://github.com/dusk-network/rusk/assets/34094428/5c42756b-9422-4ee1-a936-8af90da79a33
Dark mode:
https://github.com/dusk-network/rusk/assets/34094428/47bcdd48-bb60-4130-8a28-1a8762db0eda
> web-wallet: Fix copy button (AddressPicker)

- web-wallet/CHANGELOG.md
- Add dark mode support [#1466]
- Add autocomplete attribute on the login field [#1533]
- Change ribbon's label color [#1598]
- Update font family and letter spacing in buttons, textboxes and selects [#1565]
- Update copy on Reset Wallet while syncing [#1552]
- Trigger the Restore flow if a user tries to access a new wallet [#1535]
- Clear the login info storage on "Reset Wallet" (Settings) [#1551]
- Update `OperationResult` to infer error messages from arbitrary values [#1524]
- Update Tabs to use native scroll behavior [#1320]
- Fix copy button appearance (AddressPicker component) [#1591]
- Fix keydown behavior (AddressPicker component) [#1576]
- Data load and sync UI appearing at the same time [#1545]
- Fix error message overflowing in `ErrorDetails` component [#1547]
- Fix missing …
> web-wallet: Release 0.5.0

- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/quorum/task.rs
- consensus/src/ratification/handler.rs
- consensus/src/validation/handler.rs
- node/src/chain/acceptor.rs
> Filter out equivalent messages

- web-wallet/src/lib/dusk/currency/__tests__/createCurrencyFormatter.spec.js
- web-wallet/src/lib/dusk/currency/__tests__/createFeeFormatter.spec.js
- web-wallet/src/lib/dusk/currency/__tests__/createTransferFormatter.spec.js
> Add missing tests in `dusk/currency` module

- rusk/CHANGELOG.md
- rusk/src/lib/chain/rusk.rs
> rusk: fix corrupted state after restart

- consensus/src/user/provisioners.rs
- node/src/chain/acceptor.rs
- node/src/chain/fallback.rs
- node/src/vm.rs
- rusk/src/lib/chain/rusk.rs
- rusk/src/lib/chain/vm.rs
- rusk/tests/services/stake.rs
Resolves #1516
Unblock #1094 and #1513
> rusk: derive previous provisioners using current state

- explorer/src/lib/dusk/http/__tests__/failureToRejection.spec.js
- explorer/src/lib/dusk/http/failureToRejection.js
- explorer/src/lib/dusk/http/index.js
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/src/lib/services/index.js
- explorer/vite.config.js
> explorer: Add Dusk API service

- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/page.spec.js
> explorer: Dates aren't mocked in blocks page tests

- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/ListItem.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/list-item/ListItem.css
- explorer/src/lib/components/list-item/ListItem.svelte
- explorer/src/routes/+layout.svelte
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
> explorer: `ListItem` should use the main tooltip

- rusk/src/lib/http/chain/graphql/data.rs
Query example
```gql
query { transactions(last:1) { tx {json} }}
```
Result
```gql
{
"transactions": [
{
"tx": {
"json": "{\"anchor\":\"5652abab22a71939a2d0a485411a5be1abc4e39e6d6494031774ffd4c35d8d5d\",\"call\":null,\"crossover\":null,\"fee\":{\"gas_limit\":500000000,\"gas_price\":1,\"stealth_address\":\"33YyPMbYEJmPtrdzJqPKyMHh7S84qqZeLQiWe3njrW9cAFvtXWQfpXC5nVY1WyMLnpwgZnWCWeJmHmFrDZNwBFoi\"},\"notes\":[{\"encrypted_data\":[\"c934c6feb4eced632dbd3e9f97d529e530a84491a1b2b6d619b371c0dab46a52\",\"a5ffce0dbf8fdbd7c06dcc446a2cd3c4806c596b2731cbdd74d4cbaaeaacc56a\",\"14372a88ac77f9cae521438f0baf1711f010d26a03e0b9b8797b7e1db6667d3a\"],\"nonce\":\"dfa1a6083501ac99de9ae784e8734541c417ceb396516a96e0ab38d23cd8b838\",\"note_type\":1,\"stealth_address\":\"RF2rhjf8Viv1Cn7rmhvdkYQJb9byMsuF1uuoa2rfTHfn …
```
> rusk: GQL - add `json` field to Transaction

- explorer/src/lib/components/block-details/BlockDetails.svelte
> explorer: BlockDetails observing element out of scope

- explorer/src/lib/components/__tests__/ListItem.spec.js
- explorer/src/lib/components/__tests__/TransactionDetails.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/ListItem.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.css
- explorer/src/lib/components/index.js
- explorer/src/lib/components/list-item/ListItem.css
- explorer/src/lib/components/navbar/Navbar.css
- explorer/src/lib/components/transaction-details/TransactionDetails.css
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/lib/dusk/components/__tests__/Badge.spec.js
- explorer/src/lib/dusk/components/__tests__/__snapshots__/Badge.spec.js.snap
- explorer/src/lib/dusk/components/badge/Badge.css
- explorer/src/lib/dusk/components/badge/Badge.svelte
- explorer/src/lib/dusk/components/dusk.components.d.ts
- explorer/src/lib/dusk/components/index.js
- explorer/src/lib/dusk/currency/__tests__/createCurrencyFormatter.spec.js
- explorer/src/lib/dusk/currency/createCurrencyFormatter.js
- explorer/src/routes/blocks/block/+page.svelte
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/+page.svelte
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/page.spec.js
> explorer: compose Transaction Details

- rusk/src/lib/http.rs
- rusk/src/lib/http/event.rs
In this PR we make an effort to conform to the way the [RUES] spec defines paths.
`/on/[topic]/[component]/[entity?]`
[RUES]: https://github.com/dusk-network/rusk/wiki/RUES-(Rusk-Universal-Event-System)#list-of-http-headers-2
> Conform to RUES spec on paths

- node/src/chain/acceptor.rs
This is a letfover from #1636 
Resolves #1682
> node: Fix provisioners retrieve while restart

- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/lib.rs
- consensus/src/queue.rs
- consensus/src/quorum/task.rs
- node/default.config.toml
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
> Process buffered messages the belongs to next round

- explorer/src/lib/components/__tests__/BlocksList.spec.js
- explorer/src/lib/components/__tests__/DetailList.spec.js
- explorer/src/lib/components/__tests__/TransactionsList.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/DetailList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
- explorer/src/lib/components/blocks-list/BlocksList.css
- explorer/src/lib/components/blocks-list/BlocksList.svelte
- explorer/src/lib/components/detail-list/DetailList.css
- explorer/src/lib/components/detail-list/DetailList.svelte
- explorer/src/lib/components/index.js
- explorer/src/lib/components/list-item/ListItem.css
- explorer/src/lib/components/list-item/ListItem.svelte
- explorer/src/lib/components/transactions-list/TransactionsList.svelte
- explorer/src/lib/contexts/contexts.js
- explorer/src/lib/contexts/index.js
> Create Detail List component

- explorer/src/lib/components/__tests__/Navbar.spec.js
- explorer/src/lib/components/__tests__/TextboxAndButton.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TextboxAndButton.spec.js.snap
- explorer/src/lib/components/index.js
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/lib/components/textbox-and-button/TextboxAndButton.css
- explorer/src/lib/components/textbox-and-button/TextboxAndButton.svelte
- explorer/src/lib/containers/index.js
- explorer/src/lib/containers/search-field/SearchField.svelte
- explorer/src/lib/dusk/components/__tests__/Button.spec.js
- explorer/src/lib/dusk/components/__tests__/Textbox.spec.js
- explorer/src/lib/dusk/components/__tests__/__snapshots__/Button.spec.js.snap
- explorer/src/lib/dusk/components/__tests__/__snapshots__/Textbox.spec.js.snap
- explorer/src/lib/dusk/components/button/Button.css
- explorer/src/lib/dusk/components/button/Button.svelte
- explorer/src/lib/dusk/components/dusk.components.d.ts
- explorer/src/lib/dusk/components/index.js
- explorer/src/lib/dusk/components/select/Select.css
- explorer/src/lib/dusk/components/textbox/Textbox.css
- explorer/src/lib/dusk/components/textbox/Textbox.svelte
- explorer/src/lib/dusk/ui-helpers/__test__/handlePageClick.spec.js
- explorer/src/lib/dusk/ui-helpers/handlePageClick.js
- explorer/src/lib/navigation/__tests__/goto.spec.js
- explorer/src/lib/navigation/goto.js
- explorer/src/lib/navigation/index.js
- explorer/src/style/dusk/language.css
> explorer: Create SearchField component

- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
Resolves #1698
_**Note:** Not adding to the changelog, as the regression did not make it to prod._
> web-wallet: Fix Stake/Transfer flows CTA variant

- web-wallet/src/lib/components/Receive/Receive.svelte
Resolves #1700
_**Note:** Not adding to the changelog, as the regression did not make it to prod._
> web-wallet: Fix Receive flow buttons layout

- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/stores/__tests__/settingsStore.spec.js
- web-wallet/src/lib/stores/settingsStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/routes/(app)/__mocks__/mockedWalletStore.js
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/(app)/dashboard/__tests__/page.spec.js
- web-wallet/src/routes/(app)/settings/__tests__/page.spec.js
> web-wallet: Simplify usage of types from stores

- explorer/src/lib/components/__tests__/SearchNotification.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/SearchNotification.spec.js.snap
- explorer/src/lib/components/index.js
- explorer/src/lib/components/navbar/Navbar.css
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/lib/components/search-notification/SearchNotification.css
- explorer/src/lib/components/search-notification/SearchNotification.svelte
- explorer/src/lib/containers/search-field/SearchField.svelte
- explorer/src/lib/dusk/components/button/Button.svelte
> explorer: compose search notification

- explorer/src/lib/components/__tests__/ListItem.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/navbar/Navbar.css
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: Remove HTML button instances and use the new Button component

- rusk-abi/CHANGELOG.md
- rusk-abi/src/abi.rs
- rusk-abi/tests/contracts/host_fn/src/lib.rs
- rusk-abi/tests/lib.rs
rusk-abi: new ABIs owner_raw, self_owner_raw
implements #1710
> rusk-abi: new ABIs owner_raw, self_owner_raw

- explorer/src/lib/components/__tests__/TransactionDetails.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/transaction-details/TransactionDetails.css
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/routes/transactions/transaction/+page.svelte
> explorer: integrate Transaction Details payload fetch

- explorer/src/lib/components/data-card/DataCard.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
Resolves #1759 
https://github.com/dusk-network/rusk/assets/34094428/dcb1582b-bad7-4be4-a6bb-1dbe021747d3
> explorer: Fix loading state (Home page)

- explorer/src/lib/containers/__tests__/StatisticsPanel.spec.js
- explorer/src/lib/containers/__tests__/__snapshots__/StatisticsPanel.spec.js.snap
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.svelte
> explorer: fix block height format 

- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/navbar/Navbar.css
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/lib/containers/__tests__/StatisticsPanel.spec.js
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.svelte
- explorer/src/routes/+page.svelte
- explorer/src/routes/blocks/+page.svelte
- explorer/src/routes/blocks/block/+page.svelte
- explorer/src/routes/transactions/+page.svelte
- explorer/src/routes/transactions/transaction/+page.svelte
> explorer: link network select to appStore

- explorer/src/lib/components/__tests__/TransactionsCard.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TextboxAndButton.spec.js.snap
- explorer/src/lib/components/latest-transactions-card/LatestTransactionsCard.svelte
- explorer/src/lib/components/textbox-and-button/TextboxAndButton.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
- explorer/src/lib/containers/search-field/SearchField.svelte
- explorer/src/routes/+page.svelte
- explorer/src/routes/blocks/block/+page.svelte
- explorer/src/routes/transactions/+page.svelte
> explorer: Fix Txs occurrences

- explorer/src/lib/components/navbar/Navbar.css
> explorer: Fix navbar select (Firefox)

- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/routes/blocks/block/+page.svelte
- explorer/src/routes/transactions/transaction/+page.svelte
> explorer: fix navigation bug on detail pages

- explorer/src/lib/containers/statistics-panel/StatisticsPanel.css
> explorer: fix Statistics Panel layout

- explorer/package-lock.json
- explorer/package.json
- explorer/src/lib/chain-info/__tests__/transformAPIBlock.spec.js
- explorer/src/lib/chain-info/index.js
- explorer/src/lib/chain-info/transformAPIBlock.js
- explorer/src/lib/chain-info/transformBlock.js
- explorer/src/lib/components/__tests__/BlockDetails.spec.js
- explorer/src/lib/components/__tests__/BlocksCard.spec.js
- explorer/src/lib/components/__tests__/BlocksList.spec.js
- explorer/src/lib/components/__tests__/BlocksTable.spec.js
- explorer/src/lib/mock-data/gql-block.json
- explorer/src/lib/mock-data/gql-chain-info.d.ts
- explorer/src/lib/mock-data/index.js
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/src/lib/services/gql-queries.js
- explorer/src/routes/__tests__/page.spec.js
- explorer/src/routes/blocks/__tests__/page.spec.js
- explorer/src/routes/blocks/block/__tests__/page.spec.js
> explorer: Replace REST API call with GraphQL for single block

- explorer/src/lib/components/__tests__/AppSource.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/AppSource.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/Footer.spec.js.snap
- explorer/src/lib/components/app-source/AppSource.svelte
- explorer/src/lib/components/footer/Footer.svelte
- explorer/src/lib/components/index.js
> explorer: Source elements not taking base path into account

- explorer/src/routes/blocks/block/__tests__/page.spec.js
- explorer/src/routes/transactions/transaction/__tests__/page.spec.js
> explorer: Block and Tx pages test don't set a system date

- explorer/package-lock.json
- explorer/package.json
- explorer/src/lib/chain-info/__tests__/calculateStats.spec.js
- explorer/src/lib/chain-info/calculateStats.js
- explorer/src/lib/chain-info/index.js
- explorer/src/lib/dusk/array/__tests__/arraySum.spec.js
- explorer/src/lib/dusk/array/__tests__/arraySumByKey.spec.js
- explorer/src/lib/dusk/array/arraySum.js
- explorer/src/lib/dusk/array/arraySumByKey.js
- explorer/src/lib/dusk/array/index.js
- explorer/src/lib/mock-data/host-provisioners.json
- explorer/src/lib/mock-data/host.d.ts
- explorer/src/lib/mock-data/index.js
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/src/lib/stats/stats.d.ts
> explorer: Replace REST API call with GraphQL for stats

- explorer/package-lock.json
- explorer/package.json
> explorer: Remove unused `luxon` dependency

- explorer/package-lock.json
- explorer/package.json
- explorer/vite.config.js
> explorer: Remove unused NodeJS polyfills

- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: remove `Back` button from detail pages

- explorer/src/routes/+layout.js
- explorer/src/routes/+layout.svelte
- explorer/src/routes/__tests__/__snapshots__/error.spec.js.snap
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
- explorer/src/routes/__tests__/error.spec.js
- explorer/src/routes/__tests__/layout.spec.js
- added tests for main layout
- removed `document.body` check in `toggleScroll` function of main layout
- removed main `+layout.js` from istanbul coverage
- added tests for main error page
Resolves #1850
> explorer: Add missing tests for main routes

- explorer/src/lib/components/__tests__/__snapshots__/Footer.spec.js.snap
- explorer/src/lib/components/footer/Footer.css
- explorer/src/lib/components/footer/Footer.svelte
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
- explorer/vite.config.js
> explorer: add visible version commit hash and build date

- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksTable.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/blocks-list/BlocksList.svelte
- explorer/src/lib/components/blocks-table/BlocksTable.svelte
- explorer/src/lib/components/transactions-list/TransactionsList.svelte
- explorer/src/lib/components/transactions-table/TransactionsTable.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
> explorer: fix inconsistent data presentation

- explorer/src/lib/components/data-card/DataCard.css
> explorer: fix layout issue for latest transactions list

- explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/blocks-card/BlocksCard.svelte
- explorer/src/lib/components/latest-blocks-card/LatestBlocksCard.svelte
- explorer/src/lib/components/latest-transactions-card/LatestTransactionsCard.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/__tests__/page.spec.js
- explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/page.spec.js
- explorer/src/style/main.css
> explorer: refactor client width check to use css

- consensus/src/commons.rs
- consensus/src/config.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/proposal/step.rs
- node/src/chain/acceptor.rs
- node/src/chain/header_validation.rs
> Introduce Minimum Block Time

- rusk/src/bin/ephemeral.rs
> rusk: fix ephemeral state folder

- web-wallet/src/lib/components/Balance/Balance.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
> web-wallet: The `Balance` component is not reactive

- explorer/src/lib/components/table/Table.css
- explorer/src/routes/+page.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/style/main.css
> explorer: fix layout design issues

- explorer/src/routes/+error.svelte
- explorer/src/routes/__tests__/__snapshots__/error.spec.js.snap
- explorer/src/style/main.css
> explorer: Refactor error state page

- consensus/src/config.rs
- node-data/src/encoding.rs
- node-data/src/ledger.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
- node/src/chain/header_validation.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
- node/src/vm.rs
- rusk/src/lib/chain/rusk.rs
- rusk/src/lib/chain/vm.rs
> node: Incremental rolling finality

- explorer/src/lib/components/__tests__/__snapshots__/SearchNotification.spec.js.snap
- explorer/src/lib/components/search-notification/SearchNotification.css
- explorer/src/lib/components/search-notification/SearchNotification.svelte
- explorer/src/lib/containers/search-field/SearchField.svelte
> explorer: Improve SearchNotification appearance

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Receive/Receive.svelte
> web-wallet: Fix Receive tab content overflows

- explorer/src/lib/components/__tests__/TransactionsList.spec.js
- explorer/src/lib/components/__tests__/TransactionsTable.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
- explorer/src/lib/components/latest-transactions-card/LatestTransactionsCard.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
- explorer/src/lib/components/transactions-list/TransactionsList.svelte
- explorer/src/lib/components/transactions-table/TransactionsTable.svelte
- explorer/src/routes/+page.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
> explorer: Tweak media queries for home page tables

- .github/workflows/explorer_ci.yml
- .github/workflows/webwallet_ci.yml
Reverts dusk-network/rusk#1900
> Revert "add Node 22 to CI matrix"

- consensus/src/config.rs
> consensus: remove `CONSENSUS_DELAY_MS`

- explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/DataCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/data-card/DataCard.css
- explorer/src/lib/components/data-card/DataCard.svelte
- explorer/src/lib/dusk/components/progress-bar/ProgressBar.css
- explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: implement loader

- execution-core/CHANGELOG.md
Add a CHANGELOG for `execution-core`
> execution-core: Add CHANGELOG

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/Transactions.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Transactions.spec.js.snap
- web-wallet/src/lib/dusk/components/Suspense/Suspense.svelte
- web-wallet/src/lib/dusk/components/dusk.components.d.ts
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/style/dusk-components/suspense.css
> web-wallet: Update Transactions appearance

- explorer/src/lib/stores/__tests__/marketDataStore.spec.js
- explorer/src/lib/stores/marketDataStore.js
> explorer: Remove market poll restart after an error

- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/DataCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/data-card/DataCard.css
- explorer/src/lib/components/data-card/DataCard.svelte
- explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: update DataCard design

- consensus/Cargo.toml
- consensus/src/aggregator.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/ratification/handler.rs
- consensus/src/user/cluster.rs
- consensus/src/user/committee.rs
- consensus/src/validation/handler.rs
- node-data/src/encoding.rs
- node-data/src/ledger.rs
- node-data/src/ledger/block.rs
- node-data/src/ledger/faults.rs
- node-data/src/ledger/header.rs
- node-data/src/lib.rs
- node-data/src/message.rs
- node/benches/accept.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/genesis.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
- rusk/tests/common/state.rs
> consensus: Add `faults` to Block

- explorer/src/lib/dusk/storage/__tests__/createStorage.spec.js
- explorer/src/lib/dusk/storage/createStorage.js
- explorer/src/lib/dusk/storage/index.js
- explorer/src/lib/dusk/storage/storage.d.ts
- explorer/src/lib/services/__tests__/marketDataStorage.spec.js
- explorer/src/lib/services/index.js
- explorer/src/lib/services/marketDataStorage.js
- explorer/src/lib/services/services.d.ts
- explorer/src/lib/stores/__tests__/marketDataStore.spec.js
- explorer/src/lib/stores/marketDataStore.js
- explorer/vite.config.js
> explorer: Save market data in local storage

- consensus/src/aggregator.rs
- consensus/src/config.rs
- consensus/src/execution_ctx.rs
- consensus/src/iteration_ctx.rs
- consensus/src/msg_handler.rs
- consensus/src/phase.rs
- consensus/src/proposal/handler.rs
- consensus/src/proposal/step.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/ratification/handler.rs
- consensus/src/ratification/step.rs
- consensus/src/user/committee.rs
- consensus/src/user/provisioners.rs
- consensus/src/user/sortition.rs
- consensus/src/validation/handler.rs
- node-data/src/message.rs
- node/benches/accept.rs
- node/src/databroker.rs
- rusk/src/lib/chain.rs
- rusk/src/lib/chain/rusk.rs
> Split Block Generator reward into fixed reward and extra reward

- explorer/package-lock.json
- explorer/package.json
> explorer: Upgrade to Vitest 2.x

- explorer/src/lib/components/blocks-card/BlocksCard.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
> explorer: Refactor isLoadMoreDisabled logic

- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/lib/components/__tests__/ContractOperations.spec.js
- web-wallet/src/lib/components/__tests__/GasControls.spec.js
- web-wallet/src/lib/components/__tests__/GasSettings.spec.js
- web-wallet/src/lib/components/__tests__/OperationResult.spec.js
- web-wallet/src/lib/dusk/components/__tests__/Suspense.spec.js
- web-wallet/src/lib/dusk/test-helpers/__tests__/rejectAfter.spec.js
- web-wallet/src/lib/dusk/test-helpers/__tests__/resolveAfter.spec.js
- web-wallet/src/lib/dusk/test-helpers/rejectAfter.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
> web-wallet: Upgrade to Vitest 2.x

- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Transactions.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/style/dusk-components/suspense.css
> web-wallet: Fix content alignment regression

- consensus/src/aggregator.rs
- consensus/src/config.rs
- consensus/src/execution_ctx.rs
- consensus/src/iteration_ctx.rs
- consensus/src/queue.rs
- consensus/src/user/cluster.rs
- consensus/src/user/provisioners.rs
- consensus/src/user/sortition.rs
- node-data/src/lib.rs
- node-data/src/message.rs
Resolves #1830 
Blocked by #1962
> consensus: Reduce the total number of iterations

- web-wallet/src/lib/dusk/components/__tests__/Tabs.spec.js
> web-wallet: Fix random failure in Tabs test

- explorer/src/style/dusk/language.css
> explorer: Fix low contrast for links

- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/stores/__tests__/appStore.spec.js
- explorer/src/lib/stores/appStore.js
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
> explorer: Remove Devnet Option

- explorer/CHANGELOG.md
- explorer/package.json
> explorer: Bump version to 0.1.0 and add CHANGELOG file

- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
Resolves #2022
**Note:** Not adding to the change log, as it's a regression caused by a change that was not released to the public.
> web-wallet: Fix wrong hover state (Settings)

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/StaleDataNotice.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/StaleDataNotice.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/index.js
- explorer/src/lib/components/stale-data-notice/StaleDataNotice.svelte
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/lib/containers/__tests__/__snapshots__/StatisticsPanel.spec.js.snap
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.svelte
- explorer/src/lib/dusk/components/tooltip/Tooltip.svelte
- explorer/src/lib/dusk/test-helpers/index.js
- explorer/src/lib/dusk/test-helpers/mockReadableStore.js
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: Create and implement stale data warning

- explorer/src/app.html
> explorer: Add meta description

- explorer/CHANGELOG.md
- explorer/src/style/main.css
> explorer: Update font-display to swap for custom fonts to improve performance

- explorer/CHANGELOG.md
- explorer/src/lib/containers/__tests__/__snapshots__/StatisticsPanel.spec.js.snap
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.svelte
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
> explorer: Update Statistics Panel labels

- explorer/CHANGELOG.md
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.css
> explorer: update StatisticsPanel separator lines color

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
> explorer: Add accessible name to Nav Bar button

- explorer/src/lib/stores/__tests__/appStore.spec.js
- explorer/src/lib/stores/appStore.js
- explorer/src/lib/stores/stores.d.ts
- explorer/src/routes/+layout.svelte
- explorer/src/routes/__tests__/layout.spec.js
> explorer: Remove tooltip delay show for touch devices

- explorer/src/lib/dusk/components/__tests__/ProgressBar.spec.js
- explorer/src/lib/dusk/components/__tests__/__snapshots__/ProgressBar.spec.js.snap
> explorer: progress bar tests miss the `ariaLabel` required prop

- web-wallet/src/lib/components/UsageIndicator/UsageIndicator.svelte
- web-wallet/src/lib/components/__tests__/UsageIndicator.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/UsageIndicator.spec.js.snap
- web-wallet/src/lib/components/index.js
- web-wallet/src/routes/components-showcase/+page.svelte
- web-wallet/src/routes/components-showcase/UsageIndicators.svelte
- web-wallet/src/style/dusk/colors.css
- web-wallet/src/style/dusk/language.css
> web-wallet: Add `UsageIndicator` component

- explorer/CHANGELOG.md
- explorer/src/lib/components/detail-list/DetailList.css
> explorer: Fix list items alignment on mobile

- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Transactions.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Fix Transactions component whitespaces

- contracts/stake/tests/common/prove.rs
- contracts/transfer/tests/common/prove.rs
- execution-core/src/transfer.rs
- execution-core/src/transfer/phoenix.rs
- execution-core/tests/serialization.rs
> execution-core: Change `Prove::prove` to return a Result

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/stores/__tests__/appStore.spec.js
- explorer/src/lib/stores/appStore.js
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
> explorer: add new DEVNET entry in navbar dropdown

- node-data/src/ledger/faults.rs
- node-data/src/lib.rs
> node-data: change `Fault` hash algo to SHA3

- explorer/svelte.config.js
> explorer: 'preprocess' is deprecated

- node/benches/accept.rs
> node: fix exclusion list for benches

- consensus/src/commons.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/proposal/step.rs
- consensus/src/ratification/step.rs
- node-data/src/lib.rs
- node-data/src/message.rs
- node/src/chain/acceptor.rs
- node/src/chain/header_validation.rs
- node/src/mempool.rs
- node/src/network.rs
> Create single current timestamp function

- web-wallet/src/lib/navigation/__tests__/redirect.spec.js
> web-wallet: Refactor redirect tests

- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/migration/abi/erc_bep_duskABI.json
- web-wallet/src/lib/migration/abi/migrationABI.json
- web-wallet/src/lib/migration/walletConnection.js
- web-wallet/src/routes/components-showcase/+page.svelte
- web-wallet/src/routes/components-showcase/MigrateContract.svelte
> web-wallet: Support EVM-compatible wallets

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
> explorer: Release v0.2.0

- rusk-recovery/config/testnet.toml
rusk-recovery: testnet moonlight accounts
adding 16 testnet moonlight accounts to enable scalability testing
> rusk-recovery: testnet moonlight accounts

- contracts/transfer/src/lib.rs
- contracts/transfer/src/state.rs
> transfer-contracts: add `sync` method

- rusk/Cargo.toml
- rusk/src/lib/http.rs
> rusk: HTTP - add `/static/drivers/wallet-core.wasm` endpoint

- consensus/src/user/provisioners.rs
- node-data/src/ledger/attestation.rs
- node/src/databroker.rs
fixes [#2125](https://github.com/dusk-network/rusk/issues/2125)
> node: Missing validations

- rusk/src/lib/node.rs
Btw those extra 0.256 dusks really hurt me
If anyone has a better idea LMK
> rusk: adapt emission schedule to emit 500M dusk

- contracts/stake/Cargo.toml
- contracts/transfer/Cargo.toml
- rusk-prover/Cargo.toml
- rusk/Cargo.toml
- test-wallet/Cargo.toml
> rusk-prover: Bump to v0.4.0

- contracts/stake/tests/common/utils.rs
- contracts/transfer/tests/common/utils.rs
- execution-core/src/transfer.rs
- execution-core/src/transfer/phoenix.rs
- execution-core/tests/serialization.rs
- rusk-prover/src/lib.rs
- rusk-wallet/src/clients.rs
- rusk-wallet/src/wallet.rs
- rusk/src/lib/http/prover.rs
- test-wallet/src/imp.rs
- wallet-core/src/transaction.rs
> execution-core: Adjust `Prove.prove` to take a ref to `self`

- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/wallet.rs
- test-wallet/src/imp.rs
- wallet-core/src/transaction.rs
> Rusk wallet sheild unshield

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ApproveMigration/ApproveMigration.svelte
- web-wallet/src/lib/components/ExecuteMigration/ExecuteMigration.svelte
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/dusk/number/getDecimalSeparator.js
- web-wallet/src/lib/dusk/number/index.js
- web-wallet/src/lib/dusk/string/__tests__/cleanNumberString.spec.js
- web-wallet/src/lib/dusk/string/cleanNumberString.js
- web-wallet/src/lib/dusk/string/index.js
- web-wallet/src/lib/migration/migration.js
> web-wallet: fix rounding errors in migration amount input

- explorer/CHANGELOG.md
- explorer/src/lib/chain-info/transformTransaction.js
> explorer: Fix Transactions Fee is not properly computed

- node-data/src/events/transactions.rs
- rusk/src/lib/http/chain/graphql/data.rs
- add `json` to block header
- add `is_deploy`, tx_type and `memo` to transaction
> rusk: Add new graphql fields

- explorer/CHANGELOG.md
- explorer/src/lib/containers/__tests__/__snapshots__/StatisticsPanel.spec.js.snap
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.css
- explorer/src/lib/containers/statistics-panel/StatisticsPanel.svelte
- explorer/src/lib/dusk/value/__tests__/createCompactFormatter.spec.js
- explorer/src/lib/dusk/value/createCompactFormatter.js
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
> explorer: update display value for current and pending stake

- web-wallet/src/lib/containers/Cards/Card.css
- web-wallet/src/lib/containers/Cards/ToggleableCard.svelte
- web-wallet/src/lib/containers/__tests__/__snapshots__/ToggleableCard.spec.js.snap
- web-wallet/src/lib/dusk/components/Card/Card.svelte
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/components-showcase/Cards.svelte
- web-wallet/src/style/dusk-components/card.css
> web-wallet: Fix Cards appearance

- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncSettings.svelte
> web-wallet: Update Network Block Height meta

- web-wallet/src/routes/(welcome)/setup/create/MnemonicPreSetup.svelte
> web-wallet: Reduce gap on MnemonicPreSetup

- web-wallet/src/lib/migration/walletConnection.js
- disabled analytics in Web3Modal config
Resolves #2381
> web-wallet: Tweak Wagmi config to avoid email auth

- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
- explorer/src/lib/components/latest-transactions-card/LatestTransactionsCard.svelte
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/lib/components/transaction-type/TransactionType.css
- explorer/src/lib/components/transaction-type/TransactionType.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
- explorer/src/lib/components/transactions-list/TransactionsList.svelte
- explorer/src/lib/components/transactions-table/TransactionsTable.svelte
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: Disable Moonlight / Phoenix tooltips in polling situations

- node/src/chain.rs
- node/src/chain/fsm.rs
- node/src/chain/stall_chain_fsm.rs
> node: Handle heartbeat event in stalled_fsm

- wallet-core/src/ffi.rs
- wallet-core/src/ffi/mem.rs
- wallet-core/src/notes/owned.rs
- wallet-core/src/notes/pick.rs
- wallet-core/tests/notes.rs
- Add `mem` module
- Add `mem::from_buffer` function
- Add `pick_notes` ffi
- Add `bookmark` ffi
- Fix issue on `map_owned` ffi pointers
> wallet-core: exposing additional functionalities

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/README.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/error.rs
- rusk-wallet/src/wallet.rs
- rusk-wallet/src/wallet/address.rs
> Update rusk wallet docs

- execution-core/src/transfer/moonlight.rs
> execution-core: Support unsigned moonlight transactions

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/dusk/string/__tests__/cleanNumberString.spec.js
- web-wallet/src/lib/dusk/string/cleanNumberString.js
> web-wallet: Update migration balance and amount input shown decimals

- contracts/license/CHANGELOG.md
- contracts/license/tests/license.rs
- rusk-profile/src/lib.rs
- rusk-recovery/CHANGELOG.md
- rusk-recovery/Cargo.toml
- rusk-recovery/src/keys.rs
- rusk/CHANGELOG.md
- rusk/src/bin/args/command.rs
This PR is part of: https://github.com/dusk-network/rusk/issues/2211
> Download CRS from URL

- node/src/chain/fsm.rs
- node/src/chain/stall_chain_fsm.rs
fixes #2410
- node: Ensure that an error in FSM does not affect the stalled_sm
- Use GetBlocks
- Rerequest blocks if it remains too long in STALLED
> Fsm update

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ExistingWalletNotice/ExistingWalletNotice.svelte
- web-wallet/src/lib/components/Receive/Receive.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/containers/Cards/Card.css
- web-wallet/src/lib/containers/Cards/WarningCard.svelte
- web-wallet/src/lib/containers/Cards/index.js
- web-wallet/src/lib/containers/__tests__/IconHeadingCard.spec.js
- web-wallet/src/lib/containers/__tests__/__snapshots__/IconHeadingCard.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/allocate/+page.svelte
- web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/receive/+page.svelte
- web-wallet/src/routes/(app)/dashboard/receive/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/receive/__tests__/page.spec.js
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/staking/+page.svelte
- web-wallet/src/routes/(app)/dashboard/staking/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/forced-logout/+page.svelte
- web-wallet/src/routes/(welcome)/forced-logout/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/login/+page.svelte
- web-wallet/src/routes/(welcome)/login/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/create/MnemonicPhrase.svelte
- web-wallet/src/routes/(welcome)/setup/create/NetworkSync.svelte
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncProgress.svelte
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/components-showcase/Cards.svelte
Resolves #2421
I have refactored the Card based on Giancarlo's comment [here](https://github.com/dusk-network/rusk/issues/2285#issuecomment-2333547169). Mainly, the icon appears on the left for warnings. To capture this requirement better, I have introduced a `WarningCard` component.
Additionally, the `IconHeaderCard` can now accept an array of icons to display on the right.
> web-wallet: Update Receive screen

- explorer/CHANGELOG.md
- explorer/src/lib/chain-info/__tests__/transformBlock.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/BlocksTable.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/blocks-list/BlocksList.svelte
- explorer/src/lib/components/blocks-table/BlocksTable.svelte
- explorer/src/routes/blocks/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
> explorer: display value for average gas price in lux

- web-wallet/src/lib/test-helpers/__tests__/fillCacheDatabase.spec.js
- web-wallet/src/lib/test-helpers/__tests__/getCacheDatabase.spec.js
- web-wallet/src/lib/test-helpers/__tests__/getCacheTableCount.spec.js
- web-wallet/src/lib/test-helpers/__tests__/sortCacheNotes.spec.js
- web-wallet/src/lib/test-helpers/fillCacheDatabase.js
- web-wallet/src/lib/test-helpers/getCacheDatabase.js
- web-wallet/src/lib/test-helpers/getCacheTableCount.js
- web-wallet/src/lib/test-helpers/index.js
- web-wallet/src/lib/test-helpers/sortCacheNotes.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
> web-wallet: Move cache test helpers in a common folder

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Make address field only vertically resizable

- web-wallet/CHANGELOG.md
> web-wallet: Verify and Update Changelog

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
> web-wallet: Update `Stake` to use `Stepper`

- web-wallet/src/lib/constants/documentationLinks.js
- web-wallet/src/lib/constants/index.js
- web-wallet/src/routes/(welcome)/setup/create/NetworkSync.svelte
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncSettings.svelte
> web-wallet: Update Restore Block Height doc link

- node/src/chain/fsm.rs
- node/src/chain/fsm/outofsync.rs
- Increase max_blocks_to_request to 100
- Set pool size to 1000
- Replace pool blocks with high priority one
> node: change outofsync to use pool

- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Refactor `__space-between` usage

- execution-core/src/transfer/data.rs
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/wallet.rs
> rusk-wallet: Add transfer values to memo transaction

- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/wallet.rs
> rusk-wallet: Fix moonlight withdraw function by not asking for amount

- web-wallet/src/lib/components/__tests__/OperationResult.spec.js
> web-wallet: Fix Test Failing with Exception (OperationResult)

- rusk/src/bin/config/chain.rs
- rusk/src/lib/error.rs
- rusk/src/lib/node/vm.rs
> rusk: check for double nullifiers during tx preverify

- node-data/src/events/transactions.rs
This is an addition to PR #2500
> node-data: Change moonlight `from` to `sender` and `to` to `receiver`

- web-wallet/src/hooks.js
- web-wallet/src/routes/(welcome)/+layout.js
> web-wallet: Replace hook reroute

- web-wallet/src/routes/maintenance/+layout.svelte
> Add maintenance layout

- rusk-wallet/Cargo.toml
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/bin/main.rs
- rusk-wallet/src/clients.rs
- rusk-wallet/src/wallet.rs
- rusk-wallet/src/wallet/gas.rs
Reverts dusk-network/rusk#2540
> Revert "rusk-wallet: Add is_sycned() function call to estimate sync completion"

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Fix Address field invalid state modifier not being applied

- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/GasControls/GasControls.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/GasControls.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/GasSettings.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/style/dusk-components/textbox.css
> web-wallet: Move Textbox's Invalid CSS to Global Styles

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/TransactionDetails.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.css
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/list-item/ListItem.css
- explorer/src/lib/components/transaction-details/TransactionDetails.css
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/lib/dusk/string/__tests__/decodeHexString.spec.js
- explorer/src/lib/dusk/string/__tests__/hexToBytes.spec.js
- explorer/src/lib/dusk/string/__tests__/isValidHex.spec.js
- explorer/src/lib/dusk/string/decodeHexString.js
- explorer/src/lib/dusk/string/hexToBytes.js
- explorer/src/lib/dusk/string/index.js
- explorer/src/lib/dusk/string/isValidHex.js
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: add decode `memo` to ascii utf8

- explorer/src/lib/components/list-item/ListItem.css
- explorer/src/lib/components/transaction-type/TransactionType.svelte
- explorer/src/lib/dusk/components/__tests__/Badge.spec.js
- explorer/src/lib/dusk/components/badge/Badge.svelte
> Add maxlength to Badge and break long list items

- consensus/Cargo.toml
- consensus/src/consensus.rs
- node/Cargo.toml
- node/src/chain/acceptor.rs
Move consensus::delay() to node initialization, to avoid start on stalled state
> node: Add init delay

- rusk-wallet/src/bin/interactive.rs
> rusk-wallet: Add confirmation prompts for various transactions

- Cargo.toml
- node/src/chain/acceptor.rs
- rusk/src/lib/builder/node.rs
- Resolves #2650
- Resolves #2639
- Bump kadcast to include https://github.com/dusk-network/kadcast/pull/156
> rusk: chores

- Cargo.toml
- rusk-wallet/src/wallet.rs
> rusk-wallet: fix double stake

- explorer/src/lib/components/__tests__/__snapshots__/Footer.spec.js.snap
- explorer/src/lib/components/footer/Footer.css
- explorer/src/lib/components/footer/Footer.svelte
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
> explorer: Add links to hosted explorers from footer

- node/src/network.rs
- rusk/Cargo.toml
- rusk/src/lib/http/chain.rs
- rusk/src/lib/http/chain/geo.rs
> rusk: RUES - add `/on/network/peers_location` endpoint

- explorer/CHANGELOG.md
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/blocks-list/BlocksList.svelte
> explorer: Fix Gas Used meter if Gas Limit is zero

- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/lib.rs
- node/src/mempool.rs
Fix mempool and missing blocks request at startup
Resolves #2386
> node: improve node startup

- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Add "Shield More Dusk" Button to Address Step (Transfer Flow)

- web-wallet/jsconfig.json
- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/__mocks__/AddressSyncer.js
- web-wallet/src/__mocks__/ProtocolDriver.js
- web-wallet/src/__mocks__/mockedWalletStore.js
- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/dusk/currency/__tests__/luxToDusk.spec.js
- web-wallet/src/lib/dusk/currency/luxToDusk.js
- web-wallet/src/lib/stores/__tests__/networkStore.spec.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/networkStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/vendor/w3sper.js/src/bookkeeper.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
- web-wallet/src/lib/wallet/__tests__/notesArrayToMap.spec.js
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncProgress.svelte
- web-wallet/vite-setup.js
- web-wallet/vite.config.js
> web-wallet: Use `w3sper.js` for sync and balance

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/main.rs
> rusk-wallet: Add more information to stake info

- consensus/src/commons.rs
- consensus/src/consensus.rs
- consensus/src/execution_ctx.rs
- consensus/src/step_votes_reg.rs
- node-data/src/message.rs
- node/benches/accept.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/fsm.rs
- node/src/chain/header_validation.rs
> Handle Fail Quorum messages

- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/lib/test-helpers/__tests__/fillCacheDatabase.spec.js
- web-wallet/src/lib/test-helpers/fillCacheDatabase.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
> web-wallet: Fix data returned by IndexedDB

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/lib/dusk/string/__tests__/validateAddress.spec.js
- web-wallet/src/lib/dusk/string/validateAddress.js
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/style/dusk/colors.css
- web-wallet/src/style/dusk/language.css
> web-wallet: Add validation for public account

- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
> rusk-wallet: Unify profile_idx field in Comand enum

- explorer/CHANGELOG.md
- explorer/src/lib/chain-info/__tests__/calculateStats.spec.js
- explorer/src/lib/components/__tests__/ProvisionersCard.spec.js
- explorer/src/lib/components/__tests__/ProvisionersList.spec.js
- explorer/src/lib/components/__tests__/ProvisionersTable.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/ProvisionersCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/ProvisionersList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/ProvisionersTable.spec.js.snap
- explorer/src/lib/components/blocks-card/BlocksCard.svelte
- explorer/src/lib/components/data-card/DataCard.svelte
- explorer/src/lib/components/index.js
- explorer/src/lib/components/navbar/Navbar.css
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/lib/components/provisioners-card/ProvisionersCard.svelte
- explorer/src/lib/components/provisioners-list/ProvisionersList.svelte
- explorer/src/lib/components/provisioners-table/ProvisionersTable.css
- explorer/src/lib/components/provisioners-table/ProvisionersTable.svelte
- explorer/src/lib/components/textbox-and-button/TextboxAndButton.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
- explorer/src/lib/mock-data/host-provisioners.json
- explorer/src/lib/mock-data/host.d.ts
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
- explorer/src/routes/provisioners/+page.svelte
- explorer/src/routes/provisioners/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/provisioners/__tests__/page.spec.js
- explorer/src/routes/transactions/+page.svelte
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
> explorer: add provisioners page

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/Navbar.spec.js.snap
- explorer/src/lib/components/navbar/Navbar.svelte
- explorer/src/lib/mock-data/api-node-info.json
- explorer/src/lib/mock-data/index.js
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/src/lib/stores/__tests__/appStore.spec.js
- explorer/src/lib/stores/appStore.js
- explorer/src/lib/stores/stores.d.ts
- explorer/src/lib/url/index.js
- explorer/src/lib/url/makeApiUrl.js
- explorer/src/routes/+layout.svelte
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
- explorer/src/routes/__tests__/layout.spec.js
> explorer: Fetch node information for chain ID

- web-wallet/package-lock.json
- web-wallet/src/__mocks__/Network.js
- web-wallet/src/__mocks__/TransactionBuilder.js
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/contracts/__tests__/executeSend.spec.js
- web-wallet/src/lib/contracts/executeSend.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/test-helpers/__tests__/fillCacheDatabase.spec.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
- web-wallet/src/routes/(welcome)/login/__tests__/page.spec.js
- web-wallet/vite-setup.js
> web-wallet: Add phoenix transfer to wallet store services

- explorer/src/lib/components/__tests__/__snapshots__/ProvisionersCard.spec.js.snap
- explorer/src/lib/components/provisioners-card/ProvisionersCard.svelte
- explorer/src/routes/provisioners/__tests__/__snapshots__/page.spec.js.snap
> explorer: Fix typo in Provisioners

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/BlocksCard.spec.js
- explorer/src/lib/components/__tests__/ProvisionersCard.spec.js
- explorer/src/lib/components/__tests__/TransactionsCard.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/BlocksCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/ProvisionersCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/blocks-card/BlocksCard.svelte
- explorer/src/lib/components/provisioners-card/ProvisionersCard.svelte
- explorer/src/lib/components/transactions-card/TransactionsCard.svelte
> explorer: Hide "Show More" Button on Error

- web-wallet/src/lib/components/Receive/Receive.svelte
- web-wallet/src/lib/dusk/components/QrCode/QrCode.svelte
- web-wallet/src/routes/(app)/dashboard/receive/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Flickering while showing receive QR code

- web-wallet/src/__mocks__/mockedWalletStore.js
- web-wallet/src/lib/containers/AllocateContract/AllocateContract.svelte
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
> web-wallet: Rename balance properties to match `w3sper.js`'s

- web-wallet/src/__mocks__/mockedWalletStore.js
- web-wallet/src/lib/components/AddressPicker/AddressPicker.svelte
- web-wallet/src/lib/components/__tests__/AddressPicker.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/AddressPicker.spec.js.snap
- web-wallet/src/lib/containers/AllocateContract/AllocateContract.svelte
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/(app)/dashboard/receive/+page.svelte
> web-wallet: Have the AddressPicker use profiles instead of addresses

- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet/__tests__/nullifiersDifference.spec.js
- web-wallet/src/lib/wallet/index.js
- web-wallet/src/lib/wallet/nullifiersDifference.js
> web-wallet: Add a check for spent notes during the sync

- explorer/src/lib/url/__tests__/makeNodeUrl.spec.js
- explorer/src/lib/url/makeNodeUrl.js
> explorer: Add staging URL into node URL function

- web-wallet/src/__mocks__/mockedWalletStore.js
- web-wallet/src/lib/components/SyncBar/SyncBar.svelte
- web-wallet/src/lib/components/index.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncProgress.svelte
> web-wallet: Sync Improvements

- consensus/src/execution_ctx.rs
- consensus/src/proposal/step.rs
- node/src/chain.rs
- node/src/chain/fsm.rs
> Improve consensus logs

- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/contracts/deductLuxFeeFrom.js
- web-wallet/src/lib/contracts/executeSend.js
- web-wallet/src/lib/dusk/currency/__tests__/duskToLux.spec.js
- web-wallet/src/lib/dusk/currency/__tests__/luxToDusk.spec.js
- web-wallet/src/lib/dusk/currency/duskToLux.js
- web-wallet/src/lib/dusk/currency/luxToDusk.js
Resolves #2736, Resolves #2737
> web-wallet: Update duskToLux and luxToDusk

- explorer/src/lib/containers/statistics-panel/StatisticsPanel.css
> explorer: update StatisticsPanel layout

- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/routes/+layout.js
> web-wallet: Add stream polyfills for Safari

- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/contracts/executeSend.js
- web-wallet/src/lib/stores/stores.d.ts
> web-wallet: Replace GasSettings with w3sper's Gas

- rusk-wallet/CHANGELOG.md
- rusk-wallet/Cargo.toml
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/io/args.rs
> rusk-wallet: Update Clap from v3 to workspace v4

- web-wallet/src/__mocks__/AccountSyncer.js
- web-wallet/src/__mocks__/mockedWalletStore.js
- web-wallet/src/lib/components/Balance/Balance.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Balance.spec.js.snap
- web-wallet/src/lib/containers/AllocateContract/AllocateContract.svelte
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/(welcome)/setup/create/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js
- web-wallet/vite-setup.js
> web-wallet: Add unshielded balance calculation

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/README.md
- rusk-wallet/src/bin/interactive/command_menu.rs
- rusk-wallet/src/bin/io/args.rs
- rusk-wallet/src/bin/main.rs
- rusk-wallet/src/bin/settings.rs
> rusk-wallet: Rename --profile flag to --wallet-dir

- node/src/archive/moonlight.rs
- node/src/archive/transformer.rs
This PR adds the recording of inflows from the refund_info field of the MoonlightTransactionEvent. This is done by adding the necessary steps to take this information into account during the filtering process.
Resolves #2687
> node: add refund flow to moonlight db

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive/command_menu.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/gas.rs
> rusk-wallet: Calculate contract deploy gas limit

- web-wallet/src/__mocks__/AccountSyncer.js
- web-wallet/src/__mocks__/mockedWalletStore.js
- web-wallet/src/lib/stores/__tests__/networkStore.spec.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/networkStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
- web-wallet/src/lib/wallet-treasury/__tests__/index.spec.js
- web-wallet/src/lib/wallet-treasury/index.js
- web-wallet/src/lib/wallet-treasury/wallet-treasury.d.ts
> web-wallet: Separate treasury from the cache

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/BigIntInput/BigIntInput.css
- web-wallet/src/lib/components/BigIntInput/BigIntInput.svelte
- web-wallet/src/lib/components/__tests__/BigIntInput.spec.js
- web-wallet/src/lib/components/index.js
- web-wallet/src/routes/components-showcase/+page.svelte
- web-wallet/src/routes/components-showcase/BigIntInput.svelte
> web-wallet: Add BigIntInput component

- explorer/src/lib/url/__tests__/makeNodeUrl.spec.js
- web-wallet/README.md
- web-wallet/src/__mocks__/Network.js
- web-wallet/src/lib/stores/networkStore.js
- web-wallet/src/lib/url/__tests__/makeNodeUrl.spec.js
- web-wallet/src/lib/url/index.js
- web-wallet/src/lib/url/makeNodeUrl.js
- web-wallet/src/routes/+layout.js
- web-wallet/src/routes/+layout.svelte
- web-wallet/vite.config.js
> web-wallet: Make node URL from local env first

- web-wallet/src/lib/mock-data/cache-balances.js
- web-wallet/src/lib/mock-data/index.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/test-helpers/__tests__/getCacheDatabase.spec.js
- web-wallet/src/lib/test-helpers/fillCacheDatabase.js
- web-wallet/src/lib/test-helpers/getCacheDatabase.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
> web-wallet: Cache balances

- .editorconfig
- Add specific rules for .rs, .md & Makefile
> rusk: add .editorconfig to repository

- web-wallet/src/routes/(welcome)/setup/restore/+page.svelte
- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncSettings.svelte
> web-wallet: Use BigIntInput in NetworkSyncSettings

- scripts/dev-setup.sh
> scripts: Add dev dependency setup script

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/bin/main.rs
- rusk-wallet/src/error.rs
> rusk-wallet: Rename all instances of recovery phrase to mnemonic phrase

- web-wallet/src/__mocks__/Transactions.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/vite-setup.js
> web-wallet:  Update balance when a transaction is removed from mempool

- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/Transactions/Transactions.svelte
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/Transactions.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Transactions.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/transactions/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Update explorer links

- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/page.spec.js
> web-wallet: The listener for `keyChange` event does a pointless check

- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
> web-wallet: Update local `nonce` after a Moonlight transaction

- web-wallet/src/__mocks__/Network.js
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/contracts/contract-descriptors.js
- web-wallet/src/lib/stores/__tests__/networkStore.spec.js
- web-wallet/src/lib/stores/networkStore.js
- web-wallet/src/lib/stores/settingsStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Remove network selection in settings

- explorer/src/lib/url/__tests__/makeNodeUrl.spec.js
- explorer/src/lib/url/makeNodeUrl.js
> explorer: Update subdomains

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/BigIntInput/BigIntInput.svelte
- web-wallet/src/lib/components/GasControls/GasControls.svelte
- web-wallet/src/lib/components/GasFee/GasFee.svelte
- web-wallet/src/lib/components/GasSettings/GasSettings.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/GasControls.spec.js
- web-wallet/src/lib/components/__tests__/GasFee.spec.js
- web-wallet/src/lib/components/__tests__/GasSettings.spec.js
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/GasControls.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/GasSettings.spec.js.snap
- web-wallet/src/lib/contracts/__tests__/areValidGasSettings.spec.js
- web-wallet/src/lib/contracts/__tests__/deductLuxFeeFrom.spec.js
- web-wallet/src/lib/contracts/__tests__/executeSend.spec.js
- web-wallet/src/lib/contracts/areValidGasSettings.js
- web-wallet/src/lib/contracts/contracts.d.ts
- web-wallet/src/lib/contracts/deductLuxFeeFrom.js
- web-wallet/src/lib/contracts/executeSend.js
- web-wallet/src/lib/dusk/currency/luxToDusk.js
- web-wallet/src/lib/stores/__tests__/settingsStore.spec.js
- web-wallet/src/lib/stores/gasStore.js
- web-wallet/src/lib/stores/settingsStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Update GasSettings and related properties to BigInt type

- web-wallet/src/lib/containers/AllocateContract/AllocateContract.svelte
> web-wallet: Update Allocate Page to Display Correct Public Address

- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Remove mock transactions from UI

- web-wallet/CHANGELOG.md
- web-wallet/package.json
> web-wallet: Release 0.6.0

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
> web-wallet: Add missing changelog links, fix lock file version

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Balance/Balance.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Balance.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/layout.spec.js
- web-wallet/src/routes/components-showcase/Balances.svelte
- web-wallet/src/style/dusk-components/balance.css
> web-wallet: Update Balance component

- web-wallet/src/lib/components/Balance/Balance.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
- web-wallet/src/routes/components-showcase/Balances.svelte
> web-wallet: Fix Division By Zero (Balance component)

- w3sper.js/src/network/components/node.js
- w3sper.js/src/network/mod.js
- w3sper.js/tests/network_test.js
- Add `chain` key to `node.info` while keeping `chainId`
See: #2845
> w3sper: Add known chains to `Network`

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/GasControls/GasControls.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/GasControls.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/GasSettings.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Update UI Labels

- wallet-core/src/ffi.rs
- Rename "proved" in "proven"
- Remove rogue comments (`// ?`)
- Add `phoenix_to_moonlight` FFI
- Add `moonlight_to_phoenix` FFI
See #2859
> wallet-core: prepare for `shield` and `unshield` functionalities

- node/src/chain/acceptor.rs
- node/src/database.rs
- node/src/database/rocksdb.rs
- node/testbed.sh
- node/testbed.toml
- Require `mut` reference for storing
- Remove snapshots
- Add support for Read-Your-Own-Writes
> node: change Persistence API

- .github/workflows/webwallet_ci.yml
> web-wallet: Remove unused env var from CI

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/dusk/currency/__tests__/duskToLux.spec.js
- web-wallet/src/lib/dusk/currency/duskToLux.js
> web-wallet: crash after setting high gas price

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/wallet.rs
> rusk-wallet: Fix phoenix balance in interactive loop

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/containers/AllocateContract/AllocateContract.svelte
- web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
Resolves #2913, Resolves #2809
> web-wallet: Integrate Allocate UI with Allocate functionalities

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
> web-wallet: Release 0.7.0

- web-wallet/src/__mocks__/Network.js
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/contracts/contract-descriptors.js
- web-wallet/src/lib/stores/__tests__/networkStore.spec.js
- web-wallet/src/lib/stores/networkStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/migrate/+page.svelte
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/+layout.svelte
- web-wallet/src/routes/components-showcase/MigrateContract.svelte
> web-wallet: Add chain ID detection

- w3sper.js/README.md
- w3sper.js/deno.json
- w3sper.js/src/protocol-driver/mod.js
- w3sper.js/tests/index.html
We're not going to publish on JSR yet, but it would be useful to have this changes already in master.
> w3sper: prepare the SDK to be pulished on jsr

- w3sper.js/tests/balances_test.js
- w3sper.js/tests/stake_info_test.js
This is needed for #2874 to land
> w3sper: fix outdated tests

- contracts/transfer/tests/common/utils.rs
- contracts/transfer/tests/moonlight.rs
- contracts/transfer/tests/phoenix.rs
> transfer-contract: Add tests for failing conversions

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/constants/documentationLinks.js
> web-wallet: Broken link in the stake warning

- contracts/stake/src/state.rs
- contracts/transfer/src/state.rs
transfer-contract: fix checks in the `mint` function
stake-contract: remove unnecessary copy of bls
stake-contract: panic when withdraw no reward
> stake-contract: fix withdrawal of reward

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/DashboardNav/DashboardNav.svelte
- web-wallet/src/lib/components/__tests__/DashboardNav.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/DashboardNav.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Refactor DashboardNav component

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Enhance Allocate flow on full amount allocation

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ContractStatusesList/ContractStatusesList.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/ContractStatusesList.spec.js
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- web-wallet/src/lib/contracts/contracts.d.ts
- web-wallet/src/routes/(app)/dashboard/staking/+page.svelte
- web-wallet/src/routes/(app)/dashboard/staking/__tests__/__snapshots__/page.spec.js.snap
Resolves #3006
**Note:** See the linked issue for details
> web-wallet: Update Staking-Related functionality

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/OperationResult/OperationResult.svelte
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/OperationResult.spec.js
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/OperationResult.spec.js.snap
- web-wallet/src/lib/constants/index.js
- web-wallet/src/lib/constants/messages.js
> web-wallet: Change "Transaction Created" copy

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/constants/documentationLinks.js
> web-wallet: update stake warning's text

- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
- removed dead code about `stakeInput`
Resolves #3017
> web-wallet: streamline number types in `Stake` component

- rusk-wallet/src/bin/io/prompt.rs
> rusk-wallet: Specify LUX in the gas price prompt

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/ExistingWalletNotice/ExistingWalletNotice.svelte
- web-wallet/src/lib/dusk/components/Mnemonic/Mnemonic.svelte
- web-wallet/src/lib/dusk/components/__tests__/Mnemonic.spec.js
- web-wallet/src/routes/(welcome)/setup/create/MnemonicPreSetup.svelte
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/create/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js
- web-wallet/src/routes/components-showcase/Checkboxes.svelte
> web-wallet: Fix inconsistent terminology usage for "Mnemonic Phrase"

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/setup/restore/NetworkSyncProgress.svelte
> web-wallet: auto-sync doesn't work after restoring a wallet

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
> web-wallet: Fix application crash on empty amount (Stake Flow)

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/DashboardNav/DashboardNav.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/DashboardNav.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Fix button hover in Dashboard Menu

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/Footer.spec.js.snap
- explorer/src/lib/components/footer/Footer.svelte
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
> explorer: Change hosted Explorer links

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/setup/create/MnemonicPreSetup.svelte
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Fix "passphrase" terminology usage

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Remove "Shield More Dusk" CTA

- consensus/benches/merkle.rs
- consensus/src/aggregator.rs
- consensus/src/commons.rs
- consensus/src/config.rs
- consensus/src/consensus.rs
- consensus/src/errors.rs
- consensus/src/execution_ctx.rs
- consensus/src/iteration_ctx.rs
- consensus/src/msg_handler.rs
- consensus/src/operations.rs
- consensus/src/phase.rs
- consensus/src/proposal/block_generator.rs
- consensus/src/proposal/handler.rs
- consensus/src/proposal/step.rs
- consensus/src/queue.rs
- consensus/src/quorum/verifiers.rs
- consensus/src/ratification/handler.rs
- consensus/src/ratification/step.rs
- consensus/src/step_votes_reg.rs
- consensus/src/user/committee.rs
- consensus/src/user/provisioners.rs
- consensus/src/user/sortition.rs
- consensus/src/validation/handler.rs
- consensus/src/validation/step.rs
https://github.com/dusk-network/rusk/issues/2947 for consensus
> consensus: reorder imports to align with convention

- contracts/stake/src/state.rs
- contracts/stake/tests/events.rs
- contracts/stake/tests/stake.rs
- execution-core/src/stake.rs
- rusk-recovery/src/state.rs
- rusk-wallet/src/wallet/transaction.rs
- test-wallet/src/imp.rs
- wallet-core/src/ffi.rs
- wallet-core/src/transaction.rs
> stake-contract: remove `nonce` from `Stake`

- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/Stake/Unstake.svelte
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/Unstake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/components/__tests__/__snapshots__/Unstake.spec.js.snap
- web-wallet/src/lib/components/index.js
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
> web-wallet: Refactor Stake Component

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Stake.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/containers/StakeContract/StakeContract.svelte
> web-wallet: Fix "Stake" flow validation

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/__tests__/Send.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Send.spec.js.snap
- web-wallet/src/lib/contracts/__tests__/executeSend.spec.js
- web-wallet/src/lib/contracts/executeSend.js
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
> web-wallet: Add user feedback for "Send" flow

- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/clients/sync.rs
Insert last pos after we insert notes
> rusk-wallet: Fix syncing check

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
Resolves #3106
- Add "Support" section under Settings [#3071]
- Add user feedback for "Send" flow validation [#3098]
- Add validation for self-referential transactions [#3099]
- Reword "Withdraw Rewards" operation to "Claim Rewards" [#3076]
- Reword "Shield/Unshield" operation to "Allocate" [#3081]
- Remove "Shield More Dusk" CTA (Send flow) [#3073]
- Fix "passphrase" terminology usage with "Mnemonic Phrase" [#3069]
- Fix "Stake" flow validation [#3089]
> web-wallet: Release v.0.9.0

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
Resolves #3109
- Add error message for failed transactions [#2220]
- Add tooltips to current and pending stake to show exact amounts [#2363]
- Add `memo` and `isDeploy` fields to transactions [#2362]
- Add `txType` fields in transactions [#2347]
- Add `json` payload to block details [#2364]
- Add decode feature for the `memo` field [#2527]
- Add top node info to StatisticsPanel [#2613]
- Add Provisioners page [#2649]
- Add check for transaction existence in mempool [#2877]
- Change `raw` payload to `json` in transaction details [#2364]
- Change average gas price display value to “lux” [#2416]
- Update blocks table headers – `FEE` to `GAS`, `AVG` to `AVG PRICE`, and `TOTAL` to `USED` [#2416]
- Update block rewards tooltip information [#2166]
- Hide "Show More" button when error occurs …
> explorer: Release v.0.3.0

- Dockerfile
- README.md
Enables the archive feature by default for the Rusk Dockerfile.
> dockerfile: Make archive default

- .github/workflows/benchmarks.yml
- .github/workflows/ruskwallet_build.yml
- .github/workflows/ruskwallet_ci.yml
This PR:
- Fixes an inconsistent behavior in the benchmark CI
- Introduces ARM/Linux Rusk wallet building & `cargo check`
> Add ARM/Linux rusk wallet build

- Cargo.toml
- contracts/Makefile
- contracts/charlie/Cargo.toml
- contracts/charlie/LICENSE
- contracts/charlie/Makefile
- contracts/charlie/src/lib.rs
- contracts/charlie/src/state.rs
- contracts/stake/Cargo.toml
- contracts/stake/src/lib.rs
- contracts/stake/src/state.rs
- contracts/stake/tests/events.rs
- contracts/transfer/src/lib.rs
- contracts/transfer/src/state.rs
- execution-core/src/stake.rs
- execution-core/src/transfer.rs
- rusk-abi/src/lib.rs
- rusk-recovery/src/state.rs
- rusk-recovery/src/state/snapshot/stake.rs
- rusk/Makefile
- rusk/tests/common/state.rs
- rusk/tests/config/stake_from_contract.toml
- rusk/tests/services/contract_stake.rs
- rusk/tests/services/finalization.rs
- rusk/tests/services/mod.rs
- test-wallet/src/imp.rs
> stake-contract: allow stake from contract

- web-wallet/src/lib/components/ApproveMigration/ApproveMigration.svelte
- web-wallet/src/lib/components/ExecuteMigration/ExecuteMigration.svelte
> web-wallet: Fix incrementStep Dispatched Before Approval

- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
> web-wallet: Improve UX when connected Wallet has no DUSK (Migration)

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/migration/migration.js
- web-wallet/src/lib/migration/walletConnection.js
- web-wallet/vite-setup.js
> web-wallet: Upgrade Migration Feature to Use Reown AppKit

- .github/workflows/rusk_build.yml
> ci: Add Rusk build workflow

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(app)/settings/+page.svelte
- web-wallet/src/routes/(app)/settings/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Remove "Network" section from Settings

- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/migration/walletConnection.js
- web-wallet/src/lib/navigation/logout.js
> web-wallet: Refactor MigrationContract

- web-wallet/src/lib/components/__tests__/__snapshots__/Stake.spec.js.snap
- web-wallet/src/lib/constants/documentationLinks.js
> web-wallet: Update docs URLs

- .github/workflows/rusk_build.yml
- .github/workflows/ruskwallet_build.yml
- Updates Mac version for Rusk & Rusk wallet build
- Adds WASM build step
- Update to artifact@v4 on Rusk builds
> ci: Fix mac build versions & wasm

- contracts/stake/Cargo.toml
- contracts/stake/tests/common/assert.rs
- contracts/stake/tests/common/init.rs
- contracts/stake/tests/common/utils.rs
- contracts/stake/tests/events.rs
- contracts/stake/tests/partial_stake.rs
- contracts/stake/tests/stake.rs
Add tests for:
- stake top-up
- partial unstake
- partial withdraw
> stake-contract: Add tests

- web-wallet/CHANGELOG.md
- web-wallet/src/style/main.css
> web-wallet: Remove outer padding on small screens

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
- web-wallet/src/__mocks__/AddressSyncer.js
- web-wallet/src/lib/mock-data/cache-sync-info.js
- web-wallet/src/lib/stores/__tests__/networkStore.spec.js
- web-wallet/src/lib/stores/__tests__/walletStore.spec.js
- web-wallet/src/lib/stores/networkStore.js
- web-wallet/src/lib/stores/stores.d.ts
- web-wallet/src/lib/stores/walletStore.js
- web-wallet/src/lib/test-helpers/getCacheDatabase.js
- web-wallet/src/lib/wallet-cache/__tests__/index.spec.js
- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
- web-wallet/src/lib/wallet-treasury/__tests__/index.spec.js
- web-wallet/src/lib/wallet-treasury/index.js
> web-wallet: Update sync and cache to handle cases of rejected blocks

- web-wallet/src/lib/components/ExecuteMigration/ExecuteMigration.svelte
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
> web-wallet: Add Migration Successful Step

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/AddressPicker/AddressPicker.svelte
- web-wallet/src/lib/components/__tests__/AddressPicker.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/AddressPicker.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
Resolves #3179
Note: A temporary solution until a proper Profile Management is introduced!
> web-wallet: Update AddressPicker to show Default Profile label

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
Resolves #3221
- Fix gas settings reset and validation in preferences [#3212]
> web-wallet: Release v.0.10.1

- consensus/src/proposal/step.rs
- consensus/src/validation/handler.rs
- node/src/chain.rs
- node/src/chain/acceptor.rs
- node/src/chain/consensus.rs
> Reduce logs

- web-wallet/CHANGELOG.md
- web-wallet/src/style/main.css
Resolves #3164
To be merged before the 1.0.0 release.
> web-wallet: Remove Beta ribbon

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Allocate/Allocate.svelte
- web-wallet/src/lib/components/Balance/Balance.svelte
- web-wallet/src/lib/components/__tests__/Balance.spec.js
- web-wallet/src/lib/components/__tests__/__snapshots__/Balance.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/allocate/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/receive/+page.svelte
- web-wallet/src/routes/(app)/dashboard/receive/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/receive/__tests__/page.spec.js
- web-wallet/src/routes/(app)/dashboard/send/+page.svelte
- web-wallet/src/routes/(app)/dashboard/send/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/send/__tests__/page.spec.js
> web-wallet: Prioritize Public Account in the interface

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/components/Send/Send.svelte
- web-wallet/src/lib/components/Stake/Stake.svelte
- web-wallet/src/lib/components/Stake/Unstake.svelte
- web-wallet/src/lib/dusk/components/Stepper/Stepper.svelte
- web-wallet/src/lib/dusk/components/__tests__/Stepper.spec.js
- web-wallet/src/lib/dusk/components/__tests__/__snapshots__/Stepper.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/create/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/components-showcase/Steppers.svelte
> web-wallet: Fix labels in Stepper not displaying properly

- web-wallet/src/routes/(welcome)/+layout.svelte
Resolves #3271
Note: Does not require a changelog entry, as this is a tweak to a functionality that has not yet been released.
> web-wallet: Remove margin from Welcome Layout

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
> web-wallet: Disable source wallet option on migration initialization

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
Resolves #3256
- Add stake maturity information (Provisioners page) [#3218]
- Add "owner" field to provisioners [#3215]
- Change Stake details labels [#3218]
- Change Transaction Type tooltips [#3249]
- Fix inactive stake shown as active on mobile [#3218]
> explorer: Release v1.0.0

- web-wallet/src/routes/(welcome)/+layout.svelte
> web-wallet: Fix Retry button event handler (Welcome Layout)

- web-wallet/src/lib/vendor/w3sper.js/src/rues/mod.js
> web-wallet: Bump Rues version to 1.0.0.rc.0

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
Resolves #3255
- Add "VITE_REOWN_PROJECT_ID" ENV variable [#3267]
- Add additional notices to the Migrate flow [#3267]
- Prioritize Public Account in the interface and transaction flows [#3259]
- Enhance Migrate flow layout, aligning it to the rest of the transaction-based flows [#3267]
- Display the Migration Requirements details using the `Banner` component [#3267]
- Update the Approval Success copy for clarity (Migrate flow) [#3267]
- Trigger sync after a successful migration [#3267]
- Disable source wallet option on migration initialization (Migrate flow) [#3270]
- Remove Beta ribbon [#3164]
- Remove "UsageIndicator" component [#3245]
- Remove "VITE_FEATURE_MOONLIGHT_TRANSACTIONS" flag [#3246]
- Fix wrong error shown in the login screen [#3226] [#3097]
- Fix wallet not waiting for the …
> web-wallet: Release v1.0.0

- explorer/src/lib/components/navbar/Navbar.svelte
> explorer: Temporarily add dry-run badges

- rusk-recovery/config/mainnet.toml
- rusk-recovery/config/mainnet_remote.toml
> rusk-recovery: add mainnet.toml

- explorer/src/lib/components/navbar/Navbar.svelte
Remove the Chain ID for dry-run #1 and update the Chain ID for dry-run #2.
> explorer: Update dry-run chain ID

- web-wallet/src/lib/containers/MigrateContract/tokenConfig.js
> web-wallet: Update Migration Contracts (Bridge)

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
> web-wallet: Version 1.1.0 release

- node-data/src/bls.rs
> node-data: remove leftover println

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/containers/MigrateContract/MigrateContract.svelte
- web-wallet/src/lib/migration/walletConnection.js
> web-wallet: Reown Issues

- web-wallet/CHANGELOG.md
- web-wallet/src/app.html
> web-wallet: Remove version number from app title

- explorer/CHANGELOG.md
- explorer/src/app.html
> explorer: Remove version number from app title

- web-wallet/src/lib/wallet-cache/index.js
- web-wallet/src/lib/wallet-cache/wallet-cache.d.ts
> web-wallet: Simplify criteria creation for cache queries

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/services/loginInfoStorage/index.js
- web-wallet/src/lib/wallet/__tests__/decryptBuffer.spec.js
- web-wallet/src/lib/wallet/__tests__/encryptBuffer.spec.js
- web-wallet/src/lib/wallet/__tests__/encryptMnemonic.spec.js
- web-wallet/src/lib/wallet/__tests__/profileGeneratorFrom.spec.js
- web-wallet/src/lib/wallet/decryptBuffer.js
- web-wallet/src/lib/wallet/decryptMnemonic.js
- web-wallet/src/lib/wallet/encryptBuffer.js
- web-wallet/src/lib/wallet/encryptMnemonic.js
- web-wallet/src/lib/wallet/index.js
- web-wallet/src/lib/wallet/initializeWallet.js
- web-wallet/src/lib/wallet/profileGeneratorFrom.js
- web-wallet/src/lib/wallet/wallet.d.ts
- web-wallet/src/routes/(welcome)/setup/create/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/setup/restore/__tests__/page.spec.js
- web-wallet/src/routes/(welcome)/unlock/+page.svelte
- web-wallet/src/routes/(welcome)/unlock/__tests__/page.spec.js
> web-wallet: Secure seed with ephemeral encryption

- web-wallet/CHANGELOG.md
- web-wallet/package-lock.json
- web-wallet/package.json
Resolves #3368
- Add ephemeral encryption to secure the seed while in memory [#3354]
- Ensure connected wallet is disconnected when closing the app [#3269]
- Update Wallet Access terminology [#3356]
- Remove version number from app title [#3339]
- Fix Migration UI sometimes stuck while loading balance [#3269]
- Fix Reown modal's disconnect failing to disconnect [#3269]
> web-wallet: Release v.1.2.0

- w3sper.js/README.md
> w3sper: Add dev section to README

- explorer/CHANGELOG.md
- explorer/src/lib/components/provisioners-table/ProvisionersTable.svelte
> explorer: Fix wrong owner key shown in provisioners table

- Makefile
- README.md
> rusk: Fix Makefile and README with dusk-rusk package reference

- Cargo.lock
- Cargo.toml
- consensus/CHANGELOG.md
- consensus/Cargo.toml
- core/CHANGELOG.md
- core/Cargo.toml
- node-data/CHANGELOG.md
- node-data/Cargo.toml
- node/CHANGELOG.md
- node/Cargo.toml
- release.toml
- rusk-profile/CHANGELOG.md
- rusk-profile/Cargo.toml
- rusk-prover/CHANGELOG.md
- rusk-prover/Cargo.toml
- rusk-recovery/CHANGELOG.md
- rusk-recovery/Cargo.toml
- vm/CHANGELOG.md
- vm/Cargo.toml
- wallet-core/CHANGELOG.md
- wallet-core/Cargo.toml
All crates needs to be released again due to #3405
> workspace: release workspace packages

- explorer/CHANGELOG.md
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
> explorer: Replace legacy event system with RUES

- wallet-core/CHANGELOG.md
- wallet-core/src/ffi.rs
> wallet-core: Update phoenix function

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(welcome)/unlock/+page.svelte
- web-wallet/src/routes/(welcome)/unlock/__tests__/__snapshots__/page.spec.js.snap
> web-wallet: Auto-focus text field (Unlock page)

- web-wallet/CHANGELOG.md
> web-wallet: Fix changelog

- web-wallet/CHANGELOG.md
- web-wallet/src/routes/(app)/dashboard/+layout.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/layout.spec.js.snap
> web-wallet: Fix width discrepancy in footer icons

- w3sper.js/CHANGELOG.md
- w3sper.js/src/protocol-driver/mod.js
- w3sper.js/src/transaction.js
- w3sper.js/tests/transfer_test.js
> w3sper: Update AddressTransfer to support memo data

- web-wallet/CHANGELOG.md
- web-wallet/src/lib/stores/__tests__/networkStore.spec.js
- web-wallet/src/lib/stores/networkStore.js
> web-wallet: Fix network methods not reusing the existing connection

- Cargo.lock
- Cargo.toml
- node-data/CHANGELOG.md
- node-data/Cargo.toml
- node-data/src/events/contract.rs
- node/src/archive/moonlight.rs
- node/src/archive/sqlite.rs
- node/src/archive/transformer.rs
- node/src/chain/acceptor.rs
- rusk/src/lib/http.rs
- rusk/src/lib/http/chain/graphql/archive/data.rs
- rusk/src/lib/http/chain/graphql/archive/events.rs
- rusk/src/lib/http/event.rs
> Remove WrappedContractId

- Makefile
> workspace: fix makefile for `contracts`

- w3sper.js/tests/network_test.js
For https://github.com/dusk-network/rusk/issues/3523
> w3sper: fix network connection test

- web-wallet/src/lib/containers/Cards/IconHeadingCard.svelte
- web-wallet/src/lib/containers/Cards/WarningCard.svelte
- web-wallet/src/lib/dusk/components/Card/Card.svelte
> web-wallet: Add immutable option to Cards

- .github/workflows/docker_image_build.yml
> Fix docker image build action

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/Footer.spec.js
- explorer/src/lib/components/__tests__/__snapshots__/Footer.spec.js.snap
- explorer/src/lib/components/footer/Footer.svelte
- explorer/src/routes/__tests__/__snapshots__/layout.spec.js.snap
- explorer/src/routes/__tests__/layout.spec.js
> explorer: Fix current year not displayed in footer

- Cargo.lock
- Cargo.toml
- Makefile
- data-drivers/Makefile
- data-drivers/data-driver/CHANGELOG.md
- data-drivers/data-driver/Cargo.toml
- data-drivers/data-driver/Makefile
- data-drivers/data-driver/src/error.rs
- data-drivers/data-driver/src/lib.rs
- data-drivers/stake-contract/CHANGELOG.md
- data-drivers/stake-contract/Cargo.toml
- data-drivers/stake-contract/LICENSE
- data-drivers/stake-contract/Makefile
- data-drivers/stake-contract/src/bindgen.rs
- data-drivers/stake-contract/src/lib.rs
- data-drivers/transfer-contract/CHANGELOG.md
- data-drivers/transfer-contract/Cargo.toml
- data-drivers/transfer-contract/LICENSE
- data-drivers/transfer-contract/Makefile
- data-drivers/transfer-contract/src/bindgen.rs
- data-drivers/transfer-contract/src/lib.rs
- rust-toolchain.toml
This PR introduces a **data-driver interface** that can be implemented by any third-party contract. The primary purpose of this interface is to facilitate **conversion between native Rkyv and JSON** formats, allowing seamless data serialization and deserialization.
- Introduces a new **data-driver interface** that third-party contracts must implement.  
- Enables conversion between **native Rkyv and JSON**, improving compatibility and data handling.
- These modules provide an **additional output** that generates WebAssembly (`.wasm`) and TypeScript bindings for Node.js using **bindgen**.  
- This output is available via a new `data-driver` Makefile recipe
- Ensures data drivers can be compiled to WASM and utilized in JavaScript-based environments.
- Add `wasm32-unknown-unknown` as a …
> rusk: introduces a data-driver interface

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
Resolves #3562
- Add Account page [#3454]
- Replace legacy event system with RUES [#3425]
- Remove version number from app title [#3338]
- Fix wrong owner key shown in provisioners table [#3377]
- Fix current year not displayed in footer [#3545]
> explorer: Release v.1.1.0

- explorer/CHANGELOG.md
- explorer/src/lib/components/account-overview/AccountOverview.svelte
- explorer/src/lib/mock-data/AccountStatus.d.ts
- explorer/src/lib/services/duskAPI.js
- explorer/src/routes/accounts/+page.svelte
> explorer: Add account balance details

- web-wallet/CHANGELOG.md
- web-wallet/src/hooks.js
- web-wallet/src/lib/dusk/polyfill/index.js
- web-wallet/src/routes/+layout.js
> Polyfills are not loaded in time in some older browsers

- Cargo.lock
- rusk-wallet/CHANGELOG.md
- rusk-wallet/Cargo.toml
- rusk-wallet/src/gql.rs
For https://github.com/dusk-network/rusk/issues/3598
> rusk-wallet: fix transaction history deserialization

- explorer/CHANGELOG.md
- explorer/src/routes/accounts/+page.svelte
> explorer: Fix Account page does not reload content on key change

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsCard.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsList.spec.js.snap
- explorer/src/lib/components/__tests__/__snapshots__/TransactionsTable.spec.js.snap
- explorer/src/lib/components/transaction-type/TransactionType.svelte
- explorer/src/lib/services/duskAPI.js
- explorer/src/routes/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/__tests__/__snapshots__/page.spec.js.snap
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: Add "in/out" indicator for transfers (Account page)

- rusk/src/lib/node/vm/config.rs
Fix feature activation.
A following PR will remove the feature completely as it's not needed anymore
> rusk: fix feature activation

- explorer/CHANGELOG.md
- explorer/src/lib/components/account-overview/AccountOverview.svelte
- explorer/src/lib/components/account-overview/AccountOverviewFull.svelte
- explorer/src/lib/components/overview-panel-details-item/OverviewPanelDetailsItem.svelte
- explorer/src/lib/components/token-overview/TokenOverview.svelte
> Change balance appearance (Account overview page)

- Cargo.lock
- node/.sqlx/query-05fce30d5a98ddd16d99e514ca67ed00e2a1d3831b158e665e9f6204d9d7c314.json
- node/.sqlx/query-7a2dc6e116073e92b9f72fd9ae7ec75934ba4a9eca28397dfb38f9ba4707965a.json
- node/CHANGELOG.md
- node/Cargo.toml
- node/migrations/20250410201902_active_accounts.sql
- node/src/archive/moonlight.rs
- node/src/archive/sqlite.rs
> node: add active accounts table in archive

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/BlockDetails.spec.js.snap
- explorer/src/lib/components/block-details/BlockDetails.css
- explorer/src/lib/components/block-details/BlockDetails.svelte
- explorer/src/lib/components/search-notification/SearchNotification.css
- explorer/src/lib/components/table/Table.css
- explorer/src/lib/components/transaction-details/TransactionDetails.css
- explorer/src/routes/blocks/block/__tests__/__snapshots__/page.spec.js.snap
> explorer: Change Addresses and IDs to monospaced font

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive/command_menu.rs
> rusk-wallet: add optional deposit to ContractCall

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
Resolves #3669
- Change address to use mono font family (Account page) [#3667]
> explorer: Release v1.3.1

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/bin/main.rs
- rusk-wallet/src/cache.rs
- rusk-wallet/src/clients.rs
- rusk-wallet/src/clients/sync.rs
- rusk-wallet/src/currency.rs
- rusk-wallet/src/dat.rs
- rusk-wallet/src/error.rs
- rusk-wallet/src/gas.rs
- rusk-wallet/src/gql.rs
- rusk-wallet/src/lib.rs
- rusk-wallet/src/rues.rs
- rusk-wallet/src/store.rs
- rusk-wallet/src/wallet.rs
- rusk-wallet/src/wallet/address.rs
- rusk-wallet/src/wallet/file.rs
- rusk-wallet/src/wallet/transaction.rs
> rusk-wallet: Add clippy pedantic to lib

- node/src/archive/moonlight.rs
> node: remove default max_count in archive

- consensus/src/errors.rs
- consensus/src/validation/step.rs
Improve code readability and maintainability of Validation `try_vote`
---
Tests:
> consensus: Refactor try_vote

- explorer/CHANGELOG.md
- explorer/src/lib/components/transaction-type/TransactionType.svelte
> explorer: Fix Badge doesn't have content width

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/command/history.rs
Fixes https://github.com/dusk-network/rusk/issues/3702
> rusk-wallet: order entire tx history by block height

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
Resolves https://github.com/dusk-network/rusk/issues/3707.
> rusk-wallet: improve error message for tx history failure

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command/history.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/gql.rs
Fixes https://github.com/dusk-network/rusk/issues/3700
> rusk-wallet: fix tx history fail on empty history

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
> explorer: Release v.1.3.3

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command/history.rs
Fixes https://github.com/dusk-network/rusk/issues/3704
> rusk-wallet: separate phoenix tx history item amount from its gas fee

- Cargo.lock
- rusk-wallet/CHANGELOG.md
- rusk-wallet/Cargo.toml
- Add deploy contract output (display the new contractId)
- Add optional deposit to ContractCall [#3650]
- Add pagination for transaction history to not pollute the stdout [#3292]
- Change dependency declaration to not require strict equal [#3405]
- Change key derivation to PBKDF2 and wallet encryption to AES-GCM [#3391]
- Change default deploy gas limit to be accepted by std mempool
- Change transaction history error message to a more helpful one [#3707]
- Remove `async` from `State::register_sync` [#3623]
- Remove return of `Result<(), Error>` from `State::register_sync` [#3623]
- Fix wrong lower limit for stake operation when performing topup [#3394]
- Fix `is_synced()` method in the wallet to avoid overflow [#3593]
- Fix transaction history deserialization [#3598]
- Fix contract init …
> rusk-wallet: release 0.2.0

- explorer/CHANGELOG.md
- explorer/src/lib/components/__tests__/__snapshots__/TransactionDetails.spec.js.snap
- explorer/src/lib/components/transaction-details/TransactionDetails.svelte
- explorer/src/routes/transactions/transaction/__tests__/__snapshots__/page.spec.js.snap
> explorer: Change transaction details arrangement (Transaction Details page)

- explorer/CHANGELOG.md
- explorer/src/lib/components/account-overview/AccountOverview.svelte
> explorer: Add account address copy button (Account page)

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/interactive/command_menu.rs
For https://github.com/dusk-network/rusk/issues/3734.
> rusk-wallet: fix tx history error when wallet has no stake

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/command/history.rs
- rusk-wallet/src/gql.rs
- rusk-wallet/src/gql/tests/assets/full_moonlight_history.json
- rusk-wallet/src/lib.rs
Fixes https://github.com/dusk-network/rusk/issues/3600.
> rusk-wallet: fix tx history failure after shield/unshield conversions

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command/history.rs
Follow up of https://github.com/dusk-network/rusk/issues/3600.
- Change transaction history fee display to be negative
- Change transaction history item type to display public/shielded
> History format

- explorer/CHANGELOG.md
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/src/lib/services/gql-queries.js
> explorer: Change transaction list to use a single GraphQL query

- explorer/CHANGELOG.md
- explorer/package-lock.json
- explorer/package.json
> explorer: Release v1.4.0

- rusk-wallet/Cargo.toml
- rusk-wallet/Makefile
- rusk-wallet/src/bin/command.rs
- rusk-wallet/src/bin/command/history.rs
- rusk-wallet/src/bin/command/tests.rs
- rusk-wallet/src/bin/command/tests/utils.rs
- rusk-wallet/src/bin/interactive.rs
- rusk-wallet/src/bin/io/prompt.rs
- rusk-wallet/src/bin/main.rs
- scripts/run-rusk-wallet-tests.sh
For https://github.com/dusk-network/rusk/issues/3683.
https://github.com/dusk-network/rusk/pull/3630, https://github.com/dusk-network/rusk/issues/3704, https://github.com/dusk-network/rusk/issues/3702 and https://github.com/dusk-network/rusk/issues/3700 need to be resolved for the tests to pass.
> Tx history tests

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/command/history.rs
- rusk-wallet/src/bin/command/tests.rs
- rusk-wallet/src/bin/command/tests/utils.rs
- rusk-wallet/src/gql.rs
- rusk-wallet/src/gql/tests/assets/full_moonlight_history.json
For https://github.com/dusk-network/rusk/issues/3712
> rusk-wallet: fix tx history fail after staking

- web-wallet/package-lock.json
- web-wallet/package.json
> web-wallet: Update to latest Svelte 4

- explorer/package-lock.json
- explorer/package.json
> explorer: Update to latest Svelte 4

- rusk-wallet/src/bin/command/history.rs
For https://github.com/dusk-network/rusk/issues/3736
> rusk-wallet: error when notes without origin are found in the history

- README.md
- contracts/stake/README.md
- contracts/transfer/README.md
- core/README.md
- rusk/README.md
Resolves #3592 
Also creates a module overview on the topmost README & a preliminary README for rusk, partially addressing #2016
> workspace: add READMEs

- explorer/CHANGELOG.md
- explorer/src/lib/services/__tests__/duskAPI.spec.js
- explorer/src/lib/services/duskAPI.js
- explorer/vite.config.js
> explorer: Use supply.dusk.network for circulating supply

- rusk-wallet/CHANGELOG.md
- rusk-wallet/src/bin/README.md
- rusk-wallet/src/bin/settings.rs
Closes https://github.com/dusk-network/rusk/issues/3775
> rusk-wallet: add config to change the default wallet directory

- Cargo.lock
- node-data/Cargo.toml
- node-data/src/bls.rs
For https://github.com/dusk-network/rusk/issues/3391
> Provisioner keys encryption

- web-wallet/package-lock.json
- web-wallet/package.json
> web-wallet: Fix `engine` semver range in web wallet's `package.json`

- node-data/src/bls.rs
Closes https://github.com/dusk-network/rusk/issues/3808
> node-data: better error message on auto migration to new file format failure

- web-wallet/README.md
- web-wallet/src/lib/containers/BridgeContract/BridgeContract.svelte
- web-wallet/src/lib/containers/index.js
- web-wallet/src/lib/contracts/contract-descriptors.js
- web-wallet/src/routes/(app)/dashboard/+page.svelte
- web-wallet/src/routes/(app)/dashboard/__tests__/__snapshots__/page.spec.js.snap
- web-wallet/src/routes/(app)/dashboard/bridge/+page.svelte
- web-wallet/vite.config.js
> web-wallet: replace migrate menu item with bridge

- rusk/CHANGELOG.md
- rusk/src/lib/http/chain.rs
- rusk/src/lib/node/rusk.rs
- rusk/src/lib/test_utils.rs
- rusk/tests/services/phoenix_stake.rs
> rusk: Add `/on/contract:<contract_id>/status` endpoint
